"""Reproduce the generic MyCareer template using GNU gcc/binutils."""
from pathlib import Path
import argparse
import struct
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[2]
SOURCE = Path(__file__).resolve().parent
TARGET = ROOT / "mod_editor/core/nfl2k5_my_career_mode_code.py"


def generate():
    with tempfile.TemporaryDirectory(prefix="mycareer-mode-code-") as folder:
        d = Path(folder).resolve()
        subprocess.run(["gcc", "-m32", "-Os", "-ffreestanding", "-fno-builtin", "-fno-pic", "-fno-pie",
                        "-fno-stack-protector", "-fno-asynchronous-unwind-tables", "-fno-unwind-tables",
                        "-mpreferred-stack-boundary=2", "-mno-sse", "-mno-mmx", "-Wall", "-Wextra", "-Werror",
                        "-c", str(SOURCE / "runtime.c"), "-o", str(d / "c.o")], check=True)
        for source, name, extra in ((SOURCE / "runtime.S", "s", []),
                                    (ROOT / "tools/nfl2k5_my_career.S", "binder", ["--defsym", "MYCAREER_INLINE=1"])):
            subprocess.run(["as", "--32", *extra, str(source), "-o", str(d / (name + ".o"))], check=True)
        (d / "link.ld").write_text("SECTIONS { .text 0 : { *(.text*) *(.rodata*) } "
                                  "/DISCARD/ : { *(.comment) *(.note*) *(.eh_frame*) } }")
        subprocess.run(["ld", "-r", "-m", "elf_i386", "-T", str(d / "link.ld"),
                        "-o", str(d / "runtime.o"), *[str(d / (s + ".o")) for s in ("binder", "c", "s")]], check=True)
        data = (d / "runtime.o").read_bytes()
    shoff = struct.unpack_from("<I", data, 32)[0]
    entsize, count, strings = struct.unpack_from("<3H", data, 46)
    sections = [struct.unpack_from("<10I", data, shoff + i * entsize) for i in range(count)]

    def content(s):
        return data[s[4]:s[4] + s[5]]

    def name(table, off):
        return table[off:table.index(0, off)].decode("ascii")

    names = content(sections[strings])
    by_name = {name(names, s[0]): (i, s) for i, s in enumerate(sections)}
    for n in (".data", ".bss"):
        if n in by_name and by_name[n][1][5]:
            raise ValueError("mutable runtime data must use owned RW")
    text_index, text_section = by_name[".text"]
    symtab = by_name[".symtab"][1]
    symnames = content(sections[symtab[6]])
    symbols, labels = [], {}
    for off in range(0, symtab[5], 16):
        n, value, _, _, _, section = struct.unpack_from("<IIIBBH", content(symtab), off)
        n = name(symnames, n)
        symbols.append((n, value, section))
        if section == text_index and n:
            if n in labels and labels[n] != value:
                raise ValueError(f"ambiguous native symbol: {n}")
            labels[n] = value
    relocations = []
    for off, info in struct.iter_unpack("<II", content(by_name[".rel.text"][1])):
        n, value, section = symbols[info >> 8]
        if section == text_index:
            n = "code"
        elif section not in (0, 0xFFF1):
            raise ValueError("unexpected relocation section")
        kind = info & 255
        if kind not in (1, 2):
            raise ValueError("unsupported relocation")
        relocations.append((off, kind, n, value))
    code = content(text_section)
    lines = ['"""Generated by tools/mycareer_mode/build_runtime.py. EXPERIMENTAL / UNWITNESSED."""',
             "", "CODE = bytes.fromhex("]
    lines += ['    "' + code[i:i + 40].hex() + '"' for i in range(0, len(code), 40)]
    lines += [")", "RELOCATIONS = ("] + [f"    {r!r}," for r in relocations]
    lines += [")", "LABELS = {"] + [f"    {n!r}: {v}," for n, v in sorted(labels.items())]
    return "\n".join(lines + ["}", ""])


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = generate()
    if args.check:
        if TARGET.read_text() != result:
            raise SystemExit("MyCareer mode runtime differs; rebuild it")
    else:
        TARGET.write_text(result)
    print("MyCareer mode runtime verified" if args.check else "MyCareer mode runtime generated")
