"""b77 p9: CPU decisions "Modern 2" (sourced fourth-down table, overtime branch, two-point chart, kick guard, defensive exponents).

Offline only: the pinned USA default.xbe and bounded Unicorn replays of the real instructions. Nothing here is a played game.
Run one class at a time: ``python3 tests/mod_editor/test_nfl2k5_cpu_money_downs_m2.py Modern2NativeTests``.
"""
from pathlib import Path
import hashlib
import itertools
import json
import sys
import unittest

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from mod_editor.core import nfl2k5_cpu_money_downs as patch
from mod_editor.core import nfl2k5_xbe_space as space
from mod_editor.core.nfl2k5_cave_oracle import XbeImage
from tests.mod_editor.test_nfl2k5_owner_pairwise_composition import OWNERS, prerequisites, repin_edit, retail_xbe
from tests import nfl2k5_allocator_stack as stack

SOURCES = ROOT / "docs/mod_editor/nfl2k5_cpu_decisions_modern2_sources.json"
# The beta-76.5 / SOFTDRINK 2K28 v0.5 owner template (levels Modern and Aggressive) must never change, or a v0.5 disc stops being
# recognised as "Modern installed" and the native upgrade has no known input. Pins taken from the unchanged blob (b77 p9).
V05_TEMPLATE_CODE_SHA256 = "53a73b092d3063adf320062a48eddc631c5556ef8c631b7e13989cf17ae3468f"
V05_TEMPLATE_LAYOUT_SHA256 = "15d9e15af7403b76663ea2cda02bfbf52de6e62cad99fa0ef125ffad669a07e7"
SHIFT_AXES = (6, 7, 3)


class Modern2PolicyTests(unittest.TestCase):
    """Pure Python oracle and the data file."""

    def test_tables_equal_the_sourced_data_file(self):
        data = json.loads(SOURCES.read_text(encoding="utf-8"))
        limit, shift, thr = patch.m2_tables()
        self.assertEqual(list(limit), data["tables"]["limit_x"])
        self.assertEqual(list(shift), data["tables"]["shift"])
        self.assertEqual(list(thr), data["tables"]["thr10"])
        self.assertEqual((len(limit), len(shift), len(thr)), (81, 126, 33))
        self.assertLessEqual(len(patch.assembly.CODE2), patch.CODE_SIZE)
        # the generated byte tables match the file the generator reads
        self.assertEqual(data["fourth_down"]["limit_x_shipped_0_to_80"], data["tables"]["limit_x"])

    def test_every_threshold_is_cited_and_deviations_are_declared(self):
        data = json.loads(SOURCES.read_text(encoding="utf-8"))
        ids = {s["id"] for s in data["sources"]}
        self.assertTrue({"espn_cheat_sheet", "espn_ot_2025", "nfl4th", "nflverse_pbp"} <= ids)
        for source in data["sources"]:
            self.assertTrue(source["url"].startswith("https://"), source["id"])
            self.assertTrue(source["used_for"], source["id"])
        self.assertEqual(len(data["two_point"]["readings"]), 30)         # margins -15..+14, as the chart
        for margin, reading in data["two_point"]["readings"].items():
            self.assertTrue(reading.strip(), margin)
        self.assertIn("unmeasured", data["honesty"])
        self.assertTrue(any("own 20" in d for d in data["fourth_down"]["deliberate_deviations"]))
        validation = data["fourth_down"]["validation"]
        self.assertGreater(validation["modern2"]["accuracy"], validation["v05_modern"]["accuracy"])
        self.assertGreater(validation["modern2"]["recall"], validation["v05_modern"]["recall"])
        self.assertEqual(data["overtime"]["source"], "espn_ot_2025, nfl_rule16")
        self.assertNotIn("\u2014", SOURCES.read_text(encoding="utf-8"))

    def test_typical_table_is_the_published_chart(self):
        limit = patch.m2_tables()[0]
        self.assertEqual(max(limit), 10)                       # the 4th-and-10 sliver near the opponent 41
        self.assertEqual(limit[41], 10)
        self.assertEqual([limit[x] for x in (62, 67, 68, 75, 76, 80)], [4, 4, 3, 3, 2, 2])
        self.assertEqual(limit[20], 4)                         # field goal range: the chart prefers the kick from 4th and 5
        # retail inside the own 20 in a typical state (first quarter of a 15 minute game, 3500 s left): the table is zero there and
        # only a clock or score shift can make the CPU go (tied with 600 s left the middle shift of +2 does)
        typical = dict(level="modern2", quarter=1, seconds=800, quarter_seconds=900)
        self.assertEqual(patch.decision(own_yard=15, distance=1, **typical), "retail")
        self.assertEqual(patch.decision(own_yard=19, distance=1, **typical), "retail")      # 81 yards to goal: outside the table
        self.assertEqual(patch.decision(own_yard=20, distance=2, **typical), "go")
        self.assertEqual(patch.decision(own_yard=15, distance=2, level="modern2", quarter=4, seconds=600, quarter_seconds=900), "go")

    def test_regulation_examples(self):
        d = lambda **kw: patch.decision(level="modern2", quarter_seconds=300, **kw)
        self.assertEqual(d(own_yard=25, distance=1, quarter=1, seconds=250), "go")
        self.assertEqual(d(own_yard=25, distance=8, quarter=1, seconds=250), "retail")
        self.assertEqual(d(own_yard=50, distance=6, quarter=2, seconds=250), "go")     # middle of the field, 4th and 6
        self.assertEqual(d(own_yard=50, distance=8, quarter=2, seconds=250), "go")     # limit 7 plus 1 for 850 game seconds, tied
        self.assertEqual(d(own_yard=50, distance=9, quarter=2, seconds=250), "retail")
        self.assertEqual(d(own_yard=2, distance=5, quarter=2, seconds=250), "retail")
        self.assertEqual(d(own_yard=90, distance=3, quarter=1, seconds=250), "go")
        # last two minutes of the first half keep the retail clock logic
        self.assertEqual(d(own_yard=50, distance=1, quarter=2, seconds=120), "retail")
        # behind by two scores with two minutes left: go on every fourth down, from anywhere
        for own, dist in ((5, 20), (30, 12), (60, 25)):
            self.assertEqual(d(own_yard=own, distance=dist, quarter=4, seconds=100, score_margin=-9), "go")
            self.assertEqual(d(own_yard=own, distance=dist, quarter=4, seconds=100, score_margin=-4), "go")
        # leading late: fewer attempts than the typical chart
        self.assertEqual(d(own_yard=50, distance=6, quarter=4, seconds=200, score_margin=9), "retail")
        self.assertEqual(d(own_yard=50, distance=6, quarter=4, seconds=200, score_margin=-9), "go")
        # tied or trailing by a field goal near the goal: prefer the kick
        self.assertEqual(d(own_yard=80, distance=3, quarter=4, seconds=100, score_margin=-3), "retail")

    def test_late_lead_field_goal_rule(self):
        base = dict(level="modern2", quarter=4, seconds=90, quarter_seconds=300, score_margin=3, own_yard=70, kick_range=45)
        self.assertEqual(patch.decision(distance=9, **base), "fg")
        self.assertEqual(patch.decision(distance=7, **base), "fg")
        self.assertEqual(patch.decision(distance=6.5, **base), "retail")
        self.assertEqual(patch.decision(distance=9, **dict(base, own_yard=50)), "retail")          # outside range
        self.assertEqual(patch.decision(distance=9, **dict(base, kick_range=None)), "retail")
        self.assertEqual(patch.decision(distance=9, **dict(base, score_margin=4)), "retail")
        self.assertEqual(patch.decision(distance=9, **dict(base, score_margin=0)), "retail")
        self.assertEqual(patch.decision(distance=9, **dict(base, seconds=121)), "retail")
        self.assertEqual(patch.decision(distance=9, **dict(base, quarter=3)), "retail")

    def test_overtime_examples(self):
        away_both = dict(level="modern2", quarter=5, seconds=400, quarter_seconds=300, ot_bits=3, home=False)
        # behind by 7 on the last possession: never punt, never kick
        for own, dist in ((40, 2), (45, 1), (60, 8), (85, 3), (30, 15)):
            self.assertEqual(patch.decision(own_yard=own, distance=dist, score_margin=-7, **away_both), "go")
            self.assertEqual(patch.decision(own_yard=own, distance=dist, score_margin=-4, native_fg=True, **away_both), "go")
        # behind by a field goal: a native kick stays, anything else goes (never a punt)
        self.assertEqual(patch.decision(own_yard=40, distance=8, score_margin=-3, native_fg=False, **away_both), "go")
        self.assertEqual(patch.decision(own_yard=75, distance=3, score_margin=-3, native_fg=True, **away_both), "retail")
        # sudden death (tied after both possessions) and leading keep the retail logic
        self.assertEqual(patch.decision(own_yard=40, distance=2, score_margin=0, **away_both), "retail")
        self.assertEqual(patch.decision(own_yard=40, distance=2, score_margin=3, **away_both), "retail")
        # first possession: the typical table without clock or score terms
        first = dict(away_both, ot_bits=2)
        self.assertEqual(patch.decision(own_yard=50, distance=6, score_margin=0, **first), "go")
        self.assertEqual(patch.decision(own_yard=50, distance=8, score_margin=0, **first), "retail")
        # the home team reads bit 0 as its own and bit 1 as the opponent's
        self.assertEqual(patch.decision(own_yard=50, distance=6, score_margin=0, **dict(first, home=True)), "retail")
        self.assertEqual(patch.decision(own_yard=50, distance=6, score_margin=0, **dict(first, home=True, ot_bits=1)), "go")
        # no possession tracking (retail sudden death, an era profile): retail
        self.assertEqual(patch.decision(own_yard=40, distance=2, score_margin=-7, **dict(away_both, ot_bits=0)), "retail")
        self.assertEqual(patch.decision(own_yard=40, distance=2, score_margin=-7, **dict(away_both, ot_bits=1)), "retail")

    def test_two_point_chart_examples(self):
        def c(margin, quarter, seconds, **kw):
            return patch.two_point_decision(margin=margin, quarter=quarter, seconds=seconds, quarter_seconds=900, **kw)
        for quarter, seconds in ((1, 800), (2, 100), (3, 500), (4, 700), (4, 5)):
            self.assertTrue(c(-2, quarter, seconds))                 # retail already goes at -2 at any time: kept
            for kick in (-3, 0, 6, 7):
                self.assertFalse(c(kick, quarter, seconds), (kick, quarter, seconds))
        # only the final 20 seconds when one point down after the touchdown
        self.assertTrue(c(-1, 4, 20))
        self.assertFalse(c(-1, 4, 21))
        # down 8 before a touchdown that leaves -2 is handled above; the ESPN readings by margin (game seconds, 15 minute quarters)
        self.assertTrue(c(-8, 3, 450))         # 450 + 900 = 1350 s left: midway through the third quarter or later
        self.assertFalse(c(-8, 3, 460))
        self.assertFalse(c(-8, 2, 100))        # 100 + 900 + 900 = 1900 s left
        self.assertTrue(c(-10, 4, 300))
        self.assertFalse(c(-10, 4, 600))       # eight to nine minutes
        self.assertTrue(c(-5, 3, 600))
        self.assertFalse(c(-5, 1, 400))        # first half
        self.assertTrue(c(1, 3, 600))
        self.assertFalse(c(1, 1, 400))
        self.assertTrue(c(5, 4, 100))
        self.assertFalse(c(5, 2, 400))
        self.assertTrue(c(4, 4, 250))
        self.assertFalse(c(4, 4, 400))
        self.assertTrue(c(12, 4, 500))
        self.assertFalse(c(12, 3, 400))
        # overtime: -2 as retail; -1 only on the last possession (both possession bits); never after the first touchdown (+6)
        self.assertTrue(c(-2, 5, 300))
        self.assertTrue(c(-1, 5, 300, ot_bits=3))
        self.assertFalse(c(-1, 5, 300, ot_bits=2))
        self.assertFalse(c(-1, 5, 300))
        self.assertFalse(c(6, 5, 300, ot_bits=2))
        self.assertFalse(c(6, 5, 300, ot_bits=3))
        self.assertFalse(c(-1, 0, 300))
        self.assertFalse(c(17, 4, 100))
        self.assertFalse(c(-17, 4, 100))

    def test_clock_semantics_follow_the_native_half_clock(self):
        # periods 1 and 3: the half clock adds one quarter; the first half counts both second-half quarters
        self.assertEqual(patch._game_seconds(1, 100, 300), 100 + 300 + 600)
        self.assertEqual(patch._game_seconds(2, 100, 300), 100 + 600)
        self.assertEqual(patch._game_seconds(3, 100, 300), 100 + 300)
        self.assertEqual(patch._game_seconds(4, 100, 300), 100)

    def test_level_names_and_mapping(self):
        self.assertEqual(patch.LEVELS, ("retail", "modern", "aggressive", "modern2"))
        mapped = patch.mapping("modern2")
        self.assertEqual(mapped["presets"], {"basic": "retail", "advanced": "modern2", "experimental": "modern2"})
        self.assertEqual(mapped["defensive_lottery_exponent"], {"front": 2, "coverage": 2, "retail": 3})
        self.assertEqual(mapped["sources"], "docs/mod_editor/nfl2k5_cpu_decisions_modern2_sources.json")
        json.dumps(mapped)
        self.assertEqual(patch.decision(level="modern2", cpu=False), "retail")
        for bad in ({"down": 3}, {"phase": 3}, {"quarter": 0}, {"distance": 0}, {"distance": 26}, {"own_yard": 101}, {"seconds": -1},
                    {"score_margin": True}):
            self.assertEqual(patch.decision(level="modern2", **bad), "retail", bad)

    def test_presets_use_modern_two_and_basic_stays_retail(self):
        from mod_editor.core import mod_build
        self.assertEqual(mod_build.PRESETS["softdrink_basic"]["cpu_money_downs"], "retail")
        self.assertEqual(mod_build.PRESETS["softdrink_advanced"]["cpu_money_downs"], "modern2")
        self.assertEqual(mod_build.PRESETS["softdrink_experimental"]["cpu_money_downs"], "modern2")
        recipe = json.loads((ROOT / "pb/recipes/all_teams.json").read_text())["overrides"]
        self.assertEqual(recipe["cpu_money_downs"], "modern2")
        from mod_editor.gui import beta62_options
        self.assertIn(("Modern 2", "modern2"), beta62_options.LEVELS["cpu_money_downs"])

    def test_v05_template_bytes_are_unchanged(self):
        self.assertEqual(hashlib.sha256(patch.assembly.CODE).hexdigest(), V05_TEMPLATE_CODE_SHA256)
        layout = repr((patch.assembly.RELOCATIONS, sorted(patch.assembly.LABELS.items())))
        self.assertEqual(hashlib.sha256(layout.encode()).hexdigest(), V05_TEMPLATE_LAYOUT_SHA256)
        self.assertEqual(len(patch.assembly.CODE), 1248)
        self.assertEqual(patch.assembly.LABELS["level"], 1204)
        self.assertEqual(patch.assembly.LABELS["code_end"], 1248)


class Modern2OwnerTests(unittest.TestCase):
    """Real XBE bytes: sites, recognition, refusal, upgrade."""

    @classmethod
    def setUpClass(cls):
        cls.retail = retail_xbe()
        cls.outputs = {level: patch.apply(cls.retail, level=level)[0] for level in patch.LEVELS[1:]}

    def test_apply_status_sites_and_untouched_shotgun_rule(self):
        out = self.outputs["modern2"]
        self.assertEqual(patch.status(out), "applied")
        self.assertEqual(patch.read_settings(out)["level"], "modern2")
        self.assertEqual(space.status(out), "applied")
        row = next(a for a in space.layout(out)["allocations"] if a["owner"] == patch.OWNER)
        self.assertEqual((row["kind"], row["size"], row["align"]), ("code", 2048, 16))
        image, base = XbeImage(out), XbeImage(self.retail)
        sites = patch.sites(row["va"], "modern2")
        self.assertEqual([s[0] for s in sites], ["fourth", "play", "target", "two_point", "fg_dispatch", "fg_commit", "exponent_front", "exponent_cover"])
        for name, va, before, after in sites:
            self.assertEqual(base.read(va, len(before)), before, name)
            self.assertEqual(image.read(va, len(after)), after, name)
        by = {s[0]: s for s in sites}
        self.assertEqual(by["exponent_front"][2:], (b"\x03", b"\x02"))
        self.assertEqual(by["exponent_cover"][2:], (b"\x03", b"\x02"))
        # the exponent operands are push imm8 3 in retail
        self.assertEqual(base.read(0x20AA1E, 2), b"\x6a\x03")
        self.assertEqual(base.read(0x20AC4D, 2), b"\x6a\x03")
        self.assertEqual(image.read(0x20AA1E, 2), b"\x6a\x02")
        self.assertEqual(image.read(0x20AC4D, 2), b"\x6a\x02")
        # the shotgun 10-yard rule (jne at 0x207F85) belongs to the books job: untouched, with its constants
        self.assertEqual(base.read(0x207F85, 2), bytes.fromhex("7520"))
        self.assertEqual(image.read(0x207F85, 2), bytes.fromhex("7520"))
        self.assertEqual(image.read(0x207EF0, 0x120), base.read(0x207EF0, 0x120))
        # call sites keep their opcode, the chart entry and the three older hooks are jumps
        self.assertEqual(by["fg_dispatch"][3][0], 0xE8)
        self.assertEqual(by["fg_commit"][3][0], 0xE8)
        for name in ("fourth", "play", "target", "two_point"):
            self.assertEqual(by[name][3][0], 0xE9)
        replay, receipt = patch.apply(out, level="modern2")
        self.assertIs(replay, out)
        self.assertEqual(receipt["changed_bytes"], 0)

    def test_modern_and_aggressive_levels_are_unchanged_by_the_new_template(self):
        for level in ("modern", "aggressive"):
            out = self.outputs[level]
            self.assertEqual(patch.read_settings(out)["level"], level)
            self.assertEqual([s[0] for s in patch.sites(0, level)], ["fourth", "play", "target"])
            image = XbeImage(out)
            for va in (0x206E70, 0x20B1A4, 0x20B6DD, 0x20AA1F, 0x20AC4E):
                self.assertEqual(image.read(va, 1), XbeImage(self.retail).read(va, 1), hex(va))

    def test_every_modern2_site_and_guard_refuses_when_changed_and_mixed_states_refuse(self):
        active = self.outputs["modern2"]
        for source in (self.retail, active):
            image = XbeImage(source)
            for va, _size, _digest in patch.GUARDS:
                self.assert_refused(repin_edit(source, va, bytes([image.read(va, 1)[0] ^ 1])))
            for va, _before in patch.HOOKS2.values():
                self.assert_refused(repin_edit(source, va, bytes([image.read(va, 1)[0] ^ 1])))
        for va, before in patch.HOOKS2.values():
            self.assert_refused(repin_edit(active, va, before))

    def assert_refused(self, payload):
        from unittest import mock
        self.assertEqual(patch.status(payload), "foreign")
        with mock.patch.object(space, "apply", side_effect=AssertionError("premature allocation")), \
             mock.patch.object(space, "install_code", side_effect=AssertionError("premature write")):
            with self.assertRaises(ValueError):
                patch.apply(payload, level="modern2")

    def test_native_upgrade_equals_a_fresh_build_and_is_idempotent(self):
        for before in ("modern", "aggressive"):
            upgraded, receipt = patch.upgrade_to_modern2(self.outputs[before])
            self.assertEqual(upgraded, self.outputs["modern2"], before)
            self.assertEqual(receipt["from_level"], before)
            self.assertEqual(patch.status(upgraded), "applied")
            self.assertEqual(patch.read_settings(upgraded)["level"], "modern2")
            self.assertEqual(space.status(upgraded), "applied")
            again, repeated = patch.upgrade_to_modern2(upgraded)
            self.assertIs(again, upgraded)
            self.assertTrue(repeated["already_applied"])
        # sections: only the owner's code region, the allocator seals and the .text digest differ
        a, b = self.outputs["modern"], self.outputs["modern2"]
        changed = [i for i in range(len(a)) if a[i] != b[i]]
        # 1884 bytes of the 2048-byte owner allocation, 19 bytes at the seven re-pointed sites (the hook at 0x20B180 keeps its
        # target), and 124 bytes of derived seals (.text digest, two section digests, the directory page copy and its seal)
        self.assertEqual(len(changed), 2027)

    def test_upgrade_refuses_retail_foreign_and_mixed_inputs(self):
        with self.assertRaises(ValueError):
            patch.upgrade_to_modern2(self.retail)
        modern = self.outputs["modern"]
        image = XbeImage(modern)
        for va, _before in patch.HOOKS.values():
            bad = repin_edit(modern, va, bytes([image.read(va, 1)[0] ^ 1]))
            with self.assertRaises(ValueError):
                patch.upgrade_to_modern2(bad)
        # a hook that already carries a Modern 2 site next to Modern code is a mixed state
        mixed = repin_edit(modern, 0x20AA1F, b"\x02")
        with self.assertRaises(ValueError):
            patch.upgrade_to_modern2(mixed)
        with self.assertRaises(ValueError):
            patch.upgrade_to_modern2(b"")

    def test_cli_accepts_the_new_level(self):
        import subprocess
        import tempfile
        from tests.mod_editor.test_nfl2k5_owner_pairwise_composition import XBE
        with tempfile.TemporaryDirectory(prefix="money-downs-m2-") as directory:
            target = Path(directory).resolve() / "m2.xbe"
            result = subprocess.run([sys.executable, "-m", "mod_editor.core.nfl2k5_cpu_money_downs", "--xbe", str(XBE), "--apply",
                                     "--level", "modern2", "--output", str(target)], cwd=ROOT, capture_output=True, text=True)
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(target.read_bytes(), self.outputs["modern2"])


try:
    from tests.nfl2k5_cpu_money_downs_native import Machine, uc, x86
except ImportError:      # pragma: no cover
    uc = None


@unittest.skipUnless(uc is not None, "Unicorn is required for bounded instruction replay")
class Modern2NativeTests(unittest.TestCase):
    """The real Modern 2 machine code against the Python oracle, plus the guards and the dispatcher."""
    RANGE = 38
    CODE = {0: "retail", 1: "go", 2: "fg"}

    @classmethod
    def setUpClass(cls):
        cls.retail = retail_xbe()
        cls.payload = patch.apply(cls.retail, level="modern2")[0]
        cls.m = Machine(cls.payload)
        cls.m.supply_fg_range(cls.RANGE)
        cls.base = Machine(cls.retail)
        cls.base.supply_fg_range(cls.RANGE)

    def native_fg(self, **state):
        """The unmodified field goal test 20AF80 on this state (retail machine)."""
        self.base.configure(**state)
        self.base.run(0x20AF80)
        return bool(self.base.uc.reg_read(x86.UC_X86_REG_EAX))

    def native_hail_mary(self, **state):
        """The unmodified Hail Mary test 206DD0 on this state (retail machine); a go never overrides it."""
        self.base.configure(**state)
        self.base.run(0x206DD0)
        return bool(self.base.uc.reg_read(x86.UC_X86_REG_EAX))

    def test_regulation_grid_matches_the_oracle(self):
        cells = mismatches = 0
        for q, secs, margin, qs in itertools.product((1, 2, 3, 4), (3, 95, 125, 400, 1100), (-20, -8, -3, 0, 3, 9), (300, 900)):
            for own, dist in itertools.product((5, 20, 33, 50, 62, 80, 95), (0.5, 1, 3, 6, 7, 12, 20)):
                state = dict(quarter=q, seconds=secs, score_margin=margin, own_yard=own, distance=dist, quarter_seconds=qs)
                got = self.CODE[self.m.policy(**state)]
                want = patch.decision(level="modern2", kick_range=self.RANGE, hail_mary=self.native_hail_mary(**state), **state)
                cells += 1
                if got != want:
                    mismatches += 1
                    self.fail((state, got, want))
                self.assertTrue(all(self.m.STACK - 160 <= a < self.m.STACK for a, _ in self.m.writes), self.m.writes)
        self.assertEqual(mismatches, 0)
        self.assertEqual(cells, 4 * 5 * 6 * 2 * 7 * 7)

    def test_regulation_boundaries_float_and_direction(self):
        for direction, own, dist in itertools.product((-1, 1), (19.99, 20, 20.01, 29.99, 30, 59.99, 60, 79.99, 80), (1, 1.0001, 1.01, 2, 2.01, 3, 4.01)):
            state = dict(own_yard=own, distance=dist, direction=direction, quarter=1, seconds=250, quarter_seconds=300)
            self.assertEqual(self.CODE[self.m.policy(**state)],
                             patch.decision(level="modern2", own_yard=own, distance=dist, quarter=1, seconds=250, quarter_seconds=300,
                                            hail_mary=self.native_hail_mary(**state)),
                             state)
        for state in ({"down": 1}, {"down": 2}, {"down": 3}, {"cpu": False}, {"phase": 3}, {"quarter": 0}, {"distance": 0},
                      {"distance": 26}, {"distance": float("nan")}, {"own_yard": float("nan")}, {"own_yard": -1},
                      {"own_yard": 101}, {"seconds": 10001}, {"direction": 0}, {"direction": 2}, {"direction": float("nan")}):
            self.assertEqual(self.m.policy(**state), 0, state)

    def test_late_lead_range_edge_is_inclusive_for_every_kicker_range(self):
        """Yards to goal exactly equal to the kicker range minus 5 kicks (inclusive, 0.0001 yard tolerance) whatever the FPU rounding;
        the harness found 44 cells at ranges 30 and 50 where the first version rounded the wrong way at the edge."""
        try:
            for rng in (30, 33, 35, 38, 40, 45, 50, 55, 60):
                self.m.supply_fg_range(rng)
                edge = 105 - rng            # own yard line whose yards to goal equal rng - 5
                for own, want_fg in ((edge, True), (edge + 0.5, True), (edge - 0.5, False), (edge - 0.01, False)):
                    state = dict(quarter=4, seconds=90, score_margin=3, own_yard=own, distance=9, quarter_seconds=300)
                    got = self.CODE[self.m.policy(**state)]
                    want = patch.decision(level="modern2", kick_range=rng, hail_mary=self.native_hail_mary(**state), **state)
                    self.assertEqual(got, want, (rng, state))
                    self.assertEqual(got == "fg", want_fg, (rng, state, got))
        finally:
            self.m.supply_fg_range(self.RANGE)

    def test_overtime_grid_matches_the_oracle_home_and_away(self):
        for q, bits, home, margin in itertools.product((5, 6), (0, 1, 2, 3), (False, True), (-9, -7, -4, -3, -1, 0, 3)):
            for own, dist, secs in itertools.product((8, 40, 70, 90), (0.5, 2, 8, 15), (60, 400)):
                state = dict(quarter=q, seconds=secs, score_margin=margin, own_yard=own, distance=dist, quarter_seconds=300,
                             ot_bits=bits, home=home)
                native = self.native_fg(**state) if (q >= 5 and bits & 3 == 3 and -3 <= margin <= -1) else False
                got = self.CODE[self.m.policy(**state)]
                want = patch.decision(level="modern2", kick_range=self.RANGE, native_fg=native, **state)
                self.assertEqual(got, want, state)

    def test_two_point_chart_matches_the_oracle_through_the_real_entry(self):
        def go(margin, quarter, seconds, qs, bits=0, home=False):
            self.m.configure(quarter=quarter, seconds=seconds, score_margin=margin, quarter_seconds=qs, ot_bits=bits, home=home,
                             phase=3, down=1)
            self.m.run(0x206E70, ecx=Machine.HOME if home else self.m.OFF)
            return bool(self.m.uc.reg_read(x86.UC_X86_REG_EAX))
        cells = 0
        for q, secs, qs, bits, home in itertools.product((0, 1, 2, 3, 4, 5, 6), (0, 20, 21, 130, 250, 400, 590, 700, 1000, 1700), (300, 900),
                                                         (0, 1, 2, 3), (False, True)):
            if q < 5 and (bits or home):
                continue
            for margin in range(-20, 21):
                cells += 1
                self.assertEqual(go(margin, q, secs, qs, bits, home),
                                 patch.two_point_decision(margin=margin, quarter=q, seconds=secs, quarter_seconds=qs, ot_bits=bits, home=home),
                                 (margin, q, secs, qs, bits, home))
        self.assertGreater(cells, 8000)

    def test_dispatcher_forced_kick_go_and_the_fake_guard(self):
        # leading by 3, 0:50 left, 4th and 9 at the opponent 30 (inside range - 5): the policy forces the kick
        state = dict(quarter=4, seconds=50, score_margin=3, own_yard=70, distance=9, quarter_seconds=300)
        self.assertEqual(self.m.policy(**state), 2)
        self.assertEqual(self.m.category(**state), 0x13)
        self.assertFalse(self.native_fg(**state))                    # the unmodified test says no: retail would go for it
        self.assertGreater(self.base.category(**state), -1)
        self.assertLessEqual(self.base.category(**state), 10)
        # the commit-time test (the call at 20B6DD) goes through the guard, which agrees, so no fake is lined up
        self.m.configure(**state)
        self.m.run(self.m.owner + self.m.labels["fg_guard"])
        self.assertEqual(self.m.uc.reg_read(x86.UC_X86_REG_EAX), 1)
        # an ordinary retail state goes straight to the native test
        calm = dict(quarter=2, seconds=400, score_margin=0, own_yard=90, distance=5, quarter_seconds=300)
        self.m.configure(**calm)
        self.m.run(self.m.owner + self.m.labels["fg_guard"])
        self.base.configure(**calm)
        self.base.run(0x20AF80)
        self.assertEqual(self.m.uc.reg_read(x86.UC_X86_REG_EAX), self.base.uc.reg_read(x86.UC_X86_REG_EAX))
        # behind by 7 on the last possession of overtime (the fixture offense is the away team): always go, never kick or punt
        for own, dist in ((40, 2), (45, 1), (70, 8), (90, 4), (30, 15)):
            ot = dict(quarter=5, seconds=400, score_margin=-7, own_yard=own, distance=dist, quarter_seconds=300, ot_bits=3)
            for draw in (0.5, 0.97):
                self.m.f32(0xBF1244, draw)
                self.m.f32(0xBF1484, draw)
                cat = self.m.category(**ot)
                self.assertLessEqual(cat, 10, (ot, draw, cat))

    def test_overtime_first_possession_has_no_early_down_field_goal(self):
        for down, own, dist in itertools.product((1, 2, 3), (82, 90, 95), (10, 6)):
            state = dict(quarter=5, seconds=420, score_margin=0, own_yard=own, distance=dist, down=down, quarter_seconds=300, ot_bits=2)
            self.m.configure(**state)
            self.m.run(self.m.owner + self.m.labels["fg_guard"])
            self.assertEqual(self.m.uc.reg_read(x86.UC_X86_REG_EAX), 0, state)
        # sudden death (both bits, tied) and a missing possession record keep the native early-down field goal logic
        for bits in (3, 0):
            state = dict(quarter=5, seconds=420, score_margin=0, own_yard=95, distance=5, down=1, quarter_seconds=300, ot_bits=bits)
            self.m.configure(**state)
            self.m.run(self.m.owner + self.m.labels["fg_guard"])
            self.base.configure(**state)
            self.base.run(0x20AF80)
            self.assertEqual(self.m.uc.reg_read(x86.UC_X86_REG_EAX), self.base.uc.reg_read(x86.UC_X86_REG_EAX), state)

    def test_chart_tail_and_registers_are_preserved(self):
        m = self.m
        m.configure(quarter=4, seconds=300, score_margin=-2, quarter_seconds=300, phase=3, down=1)
        m.run(0x206E70, ecx=m.OFF, ebx=0x1111, esi=0x2222, edi=0x3333, ebp=0x4444)
        # EBX/ESI/EDI/EBP are preserved; ECX and EDX are volatile, as in retail (the native half clock helper at 0x205F80 reuses its
        # saved ECX slot as a float scratch and pops it back), and the callers of 0x208470 reload both after the call
        for name, value in dict(EBX=0x1111, ESI=0x2222, EDI=0x3333, EBP=0x4444).items():
            self.assertEqual(m.uc.reg_read(getattr(x86, "UC_X86_REG_" + name)), value, name)
        self.assertEqual(m.uc.reg_read(x86.UC_X86_REG_FPTAG), 0xFFFF)
        policy_regs = dict(EBX=0x1111, ESI=0x2222, EDI=0x3333, EBP=0x4444)
        m.configure(quarter=1, seconds=250, score_margin=0, own_yard=50, distance=2, quarter_seconds=300)
        m.run(m.owner + m.labels["policy"], **policy_regs)
        for name, value in policy_regs.items():
            self.assertEqual(m.uc.reg_read(getattr(x86, "UC_X86_REG_" + name)), value, name)
        self.assertEqual(m.uc.reg_read(x86.UC_X86_REG_FPTAG), 0xFFFF)


class Modern2PairTests(unittest.TestCase):
    """Modern 2 beside every other owner in the pair matrix, both orders, exact replay and equal bytes."""

    @classmethod
    def setUpClass(cls):
        cls.seed, _ = space.apply(prerequisites(retail_xbe()), stack.REQUESTS, scaleout=True)

    def check_pair(self, other):
        class Modern2:
            OWNER = patch.OWNER
            status = staticmethod(patch.status)
            apply = staticmethod(lambda payload: patch.apply(payload, level="modern2"))
        digests = []
        for order in ((Modern2, other), (other, Modern2)):
            with self.subTest(order=" -> ".join(owner.OWNER for owner in order)):
                result = self.seed
                for owner in order:
                    result, _ = owner.apply(result)
                self.assertEqual(patch.read_settings(result)["level"], "modern2")
                for owner in (Modern2, other):
                    self.assertEqual(owner.status(result), "applied", owner.OWNER)
                    replay, receipt = owner.apply(result)
                    self.assertEqual(replay, result, owner.OWNER)
                    if other is not stack.StaticScorebar:
                        self.assertEqual(receipt["changed_bytes"], 0, owner.OWNER)
                digests.append(hashlib.sha256(result).digest())
        self.assertEqual(digests[0], digests[1], "installation order changed the pair output")


def _pair_test(other):
    def test(self):
        self.check_pair(other)
    return test


for _name, _owner in OWNERS:
    if _owner.OWNER == patch.OWNER:
        continue
    setattr(Modern2PairTests, f"test_modern2__{_name}", _pair_test(_owner))


if __name__ == "__main__":
    unittest.main()
