"""The ESPN scorebug's inputs come from the user's disc, and produce the same bytes.

Nothing the scorebug needs ships: the retail scene, its span and the three P8 atlases are
retail bytes, and our repaints of those atlases are derived from them.  They are read out of
the user's own image at build time and the art is regenerated by the shipped generator.  The
tests that matter here are therefore:

* availability is about this BUILD, not about files on the maintainer's disk;
* with the developer asset folder hidden and no extracted pack archive in sight, every
  replacement span is byte-for-byte the one the developer route produces;
* the full step over a real copy of the disc leaves the same resource bytes behind.

The last two are gated on the retail extraction and image; every other test runs anywhere.
"""

from __future__ import annotations

import hashlib
import os
from pathlib import Path
import shutil
import sys
import tempfile
import unittest
from unittest import mock

ROOT = Path(__file__).resolve().parents[2]
for entry in (ROOT, ROOT / "tools"):
    if str(entry) not in sys.path:
        sys.path.insert(0, str(entry))

from mod_editor.core import nfl2k5_scorebug_source_art as art  # noqa: E402

EXTRACTION = Path(os.environ.get("NFL2K5_RETAIL_EXTRACTION",
                                 "/media/noah/Storage/for codex 1.0/extracted"))
RETAIL_PACK0 = EXTRACTION / "ESPN NFL 2K5 (USA)" / "vc_53450030" / "0"
RETAIL_XISO = Path(os.environ.get("NFL2K5_RETAIL_XISO",
                                  "/media/noah/Storage/for codex 1.0/ESPN NFL 2K5 (USA).xiso.iso"))
AUDIT = ROOT / "reports" / "assets" / "scorebug_presentation_audit.json"
DEVELOPER = ROOT / "mod_editor" / "assets" / "nfl2k5_scorebug_espn"
FULL_DISC_HEADROOM = 20 * 1024 * 1024 * 1024


def _sha(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


class AvailabilityTests(unittest.TestCase):
    """``available()`` answers "can this build do the work", never "does this machine have art"."""

    def test_available_without_the_developer_asset_folder(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            with mock.patch.object(art, "DEVELOPER_ASSETS", Path(tmp) / "nothing"):
                self.assertTrue(art.available())

    def test_available_with_reference_pins_without_the_legacy_audit(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            with mock.patch.object(art, "AUDIT", Path(tmp) / "no-audit.json"):
                self.assertTrue(art.available())

    def test_texture_targets_carry_the_four_atlases(self) -> None:
        targets = art.texture_targets()
        self.assertEqual(set(targets), set(art.TEXTURE_NAMES) | {"NAVTEXTURE"})
        for name, target in targets.items():
            self.assertEqual(target["pack_path"], art.PACK0_PATH, name)
            self.assertGreater(int(target["span_size"]), 0, name)
            self.assertEqual(len(str(target["span_sha256"])), 64, name)

    def test_a_non_image_source_is_not_a_disc_image(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            loose = Path(tmp) / "default.xbe"
            loose.write_bytes(b"XBEH" + bytes(4096))
            self.assertFalse(art.is_disc_image(loose))
            self.assertFalse(art.is_disc_image(Path(tmp) / "missing.iso"))

    def test_resolve_art_without_a_source_or_cache_refuses_the_two_the_bar_needs(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            with mock.patch.object(art, "DEVELOPER_ASSETS", Path(tmp) / "nothing"), \
                    mock.patch.object(art, "cache_root", lambda: Path(tmp) / "cache"):
                with self.assertRaises(art.ScorebugArtError):
                    art.resolve_art(None)


@unittest.skipUnless(RETAIL_XISO.is_file(), "retail disc image not present")
class DiscSourcedArtTests(unittest.TestCase):
    """Everything the writer needs, produced from the image alone."""

    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        tmp = Path(self._tmp.name)
        self._patches = [
            mock.patch.object(art, "DEVELOPER_ASSETS", tmp / "no-developer-assets"),
            mock.patch.object(art, "cache_root", lambda root=tmp: root / "cache"),
        ]
        for patch in self._patches:
            patch.start()

    def tearDown(self) -> None:
        for patch in reversed(self._patches):
            patch.stop()
        self._tmp.cleanup()

    def test_the_retail_scene_decodes_out_of_the_image_and_caches(self) -> None:
        decoded = art.retail_scne(RETAIL_XISO)
        self.assertEqual(len(decoded), art.SCNE_SIZE)
        self.assertEqual(_sha(decoded), art.SCNE_SHA256)
        cached = art.cache_dir() / "score_bug_retail.scne"
        self.assertTrue(cached.is_file())
        # a second read needs no image at all
        self.assertEqual(art.retail_scne(None), decoded)

    def test_the_modern_art_regenerates_byte_for_byte(self) -> None:
        resolved = art.resolve_art(RETAIL_XISO)
        for role in ("score_buga", "shield_espn"):
            self.assertIn(role, resolved["art"], role)
            self.assertEqual(resolved["origin"][role], "derived", role)
            self.assertEqual(_sha(Path(resolved["art"][role]).read_bytes()),
                             art.ART_REFERENCE_SHA256[role], role)
        # the digit sheet is drawn with a real font: produced where DejaVu is installed,
        # named as skipped where it is not, but never silently replaced by a fallback face
        import nfl2k5_scorebug_espn_art as generator
        if generator.have_text_font():
            self.assertEqual(_sha(Path(resolved["art"]["digital_font"]).read_bytes()),
                             art.ART_REFERENCE_SHA256["digital_font"])
        else:
            self.assertIn("digital_font", resolved["skipped"])
        # the ticker-band atlas was hand-painted and has no generator: named, never faked
        self.assertNotIn("NAVTEXTURE", resolved["art"])
        self.assertIn("NAVTEXTURE", resolved["skipped"])

    def test_a_second_resolve_comes_from_the_private_cache(self) -> None:
        first = art.resolve_art(RETAIL_XISO)
        second = art.resolve_art(None)
        for role, path in first["art"].items():
            self.assertEqual(second["art"][role], path, role)
            self.assertEqual(second["origin"][role], "cache", role)

    def test_a_changed_generator_restales_the_cached_art(self) -> None:
        """Derived art has no version but the code that made it, so the cache records that."""

        art.retail_scne(RETAIL_XISO)
        first = art.resolve_art(RETAIL_XISO)
        self.assertTrue(all(o == "derived" for o in first["origin"].values()))
        self.assertEqual(art.resolve_art(None)["origin"]["score_buga"], "cache")
        with mock.patch.object(art, "_generator_digest", lambda: "a different generator"):
            again = art.resolve_art(RETAIL_XISO)
            self.assertEqual(again["origin"]["score_buga"], "derived")
            # the retail scene is retail bytes with a fixed digest: never restaled by this
            self.assertEqual(_sha(art.retail_scne(None)), art.SCNE_SHA256)

    def test_a_pinned_span_read_from_a_foreign_image_is_refused(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            fake = Path(tmp) / "not-a-disc.iso"
            fake.write_bytes(bytes(1 << 20))
            with self.assertRaises(art.ScorebugArtError):
                art.retail_texture_span(fake, "score_buga")


@unittest.skipUnless(RETAIL_XISO.is_file() and RETAIL_PACK0.is_file(),
                     "retail disc image and extracted pack archive not both present")
class ByteIdentityTests(unittest.TestCase):
    """The user route and the developer route build the same replacement spans.

    The developer route cuts the retail template out of the extracted pack archive and quantizes
    the checked-in PNGs; the user route cuts the same template out of the disc image and
    quantizes art regenerated from that image.  Both are compared span for span -- these are the
    exact bytes that land in the field pack.
    """

    def test_every_texture_span_is_identical_either_way(self) -> None:
        if not AUDIT.is_file():
            self.skipTest("legacy typed-importer audit evidence absent; v7 has independent pins")
        import nfl_scorebug_png_import as importer
        import nfl_txtr
        import nfl_vc_lz_fill

        with tempfile.TemporaryDirectory() as tmp:
            cache = Path(tmp) / "cache"
            with mock.patch.object(art, "DEVELOPER_ASSETS", Path(tmp) / "no-developer-assets"), \
                    mock.patch.object(art, "cache_root", lambda: cache):
                derived = art.resolve_art(RETAIL_XISO)["art"]
            for role in art.TEXTURE_NAMES:
                if role not in derived:
                    continue
                shipped = DEVELOPER / art.ART_FILE_NAMES[role]
                if not shipped.is_file():
                    self.skipTest(f"{shipped.name} is not in this tree")
                developer_span, _preview, _report = importer.build_import(
                    RETAIL_PACK0, AUDIT, role, shipped)
                template = art.retail_texture_span(RETAIL_XISO, role)
                user_span, _preview, _report = importer.build_import(
                    None, AUDIT, role, Path(derived[role]), template_span=template)
                self.assertEqual(developer_span, user_span, role)
                # ... and after the retail-wrapper refill both writers finish with
                filled = []
                for span in (developer_span, user_span):
                    chunk = nfl_txtr.parse_chunks(span, allow_trailing=True)[0]
                    decoded, _info = nfl_txtr.decode_chunk(span, chunk)
                    refilled, _fill = nfl_vc_lz_fill.rebuild_fixed_span_filled(template, decoded)
                    filled.append(refilled)
                self.assertEqual(filled[0], filled[1], role)

    def test_the_scene_span_is_identical_either_way(self) -> None:
        import nfl2k5_scorebug_layout as layout

        shipped = DEVELOPER / "score_bug_retail.scne"
        if not shipped.is_file():
            self.skipTest("the developer copy of the retail scene is not in this tree")
        with tempfile.TemporaryDirectory() as tmp:
            cache = Path(tmp) / "cache"
            with mock.patch.object(art, "DEVELOPER_ASSETS", Path(tmp) / "no-developer-assets"), \
                    mock.patch.object(art, "cache_root", lambda: cache):
                from_disc = art.retail_scne(RETAIL_XISO)
        self.assertEqual(from_disc, shipped.read_bytes())
        template = art.retail_scne_span(RETAIL_XISO)
        spans = []
        for scene in (shipped.read_bytes(), from_disc):
            mesh = layout.Mesh(scene)
            layout.espn_layout(mesh)
            span, _info = layout.refit(template, mesh.serialize())
            spans.append(span)
        self.assertEqual(spans[0], spans[1])


def _enough_room_for_a_disc_copy(directory: Path) -> bool:
    try:
        usage = shutil.disk_usage(directory)
    except OSError:
        return False
    return usage.free > RETAIL_XISO.stat().st_size + FULL_DISC_HEADROOM


@unittest.skipUnless(RETAIL_XISO.is_file(), "retail disc image not present")
@unittest.skipIf(os.environ.get("NFL2K5_SCOREBUG_DISC_TEST") == "0",
                 "full-disc scorebug test disabled")
class FullDiscWriteTests(unittest.TestCase):
    """The whole step, over a real copy of the disc, with the asset folder hidden.

    One copy: the developer route's bytes for the same four resources are computed in memory
    from the extracted archive, because a second 6 GB copy proves nothing the first does not.
    """

    def test_the_step_writes_the_expected_resource_bytes(self) -> None:
        import nfl_scorebug_png_import as importer
        import nfl_txtr
        import nfl_uniform_color_xiso_direct_patch as xc
        import nfl_vc_lz_fill
        import nfl2k5_scorebug_layout as layout

        if not RETAIL_PACK0.is_file():
            self.skipTest("extracted pack archive not present")
        if not (DEVELOPER / "score_bug_retail.scne").is_file():
            self.skipTest("the developer copies this is compared against are not in this tree")
        with tempfile.TemporaryDirectory() as tmp:
            room = Path(tmp)
            if not _enough_room_for_a_disc_copy(room):
                self.skipTest("not enough free space for a disc copy")
            target = room / "scorebug.iso"
            shutil.copyfile(RETAIL_XISO, target)

            cache = room / "cache"
            with mock.patch.object(art, "DEVELOPER_ASSETS", room / "no-developer-assets"), \
                    mock.patch.object(art, "cache_root", lambda: cache), \
                    mock.patch.object(layout, "ESPN_TEXTURES", room / "no-developer-assets"):
                receipt = layout.apply_in_place(target)

            self.assertEqual(receipt["layout"], f"espn-horizontal-v{layout.LAYOUT_VERSION}")
            self.assertTrue(receipt["wrapper_identical"])
            self.assertIn("score_buga", receipt["textures"])
            self.assertIn("shield_espn", receipt["textures"])
            self.assertTrue(all(receipt["art_reference_match"].values()))
            # the hand-painted ticker atlas is not in a release, and the receipt says so
            self.assertIn("NAVTEXTURE", receipt.get("art_skipped", {}))
            self.assertNotIn("NAVTEXTURE", receipt["textures"])

            expected: dict[str, bytes] = {}
            scene = layout.Mesh((DEVELOPER / "score_bug_retail.scne").read_bytes())
            layout.espn_layout(scene)
            expected["score_bug"] = layout.refit(
                art.retail_scne_span(RETAIL_XISO), scene.serialize())[0]
            for role in art.TEXTURE_NAMES:
                shipped = DEVELOPER / art.ART_FILE_NAMES[role]
                if role not in receipt["textures"] or not shipped.is_file():
                    continue
                span, _preview, _report = importer.build_import(RETAIL_PACK0, AUDIT, role, shipped)
                chunk = nfl_txtr.parse_chunks(span, allow_trailing=True)[0]
                decoded, _info = nfl_txtr.decode_chunk(span, chunk)
                template = art.retail_texture_span(RETAIL_XISO, role)
                expected[role], _fill = nfl_vc_lz_fill.rebuild_fixed_span_filled(template, decoded)

            targets = art.texture_targets()
            places = {"score_bug": (art.SCNE_PACK_OFFSET, art.SCNE_SPAN_SIZE)}
            for role in art.TEXTURE_NAMES:
                places[role] = (int(targets[role]["pack_offset"]), int(targets[role]["span_size"]))
            descriptor = os.open(target, os.O_RDONLY | getattr(os, "O_BINARY", 0))
            try:
                size = os.fstat(descriptor).st_size
                base, _pack_size = xc.pack_extent(descriptor, size, "0")
                for role, want in expected.items():
                    offset, span_size = places[role]
                    got = art._pread(descriptor, span_size, base + offset)
                    self.assertEqual(_sha(got), _sha(want), role)
                # untouched: the ticker atlas is still the retail resource
                offset, span_size = (int(targets["NAVTEXTURE"]["pack_offset"]),
                                     int(targets["NAVTEXTURE"]["span_size"]))
                self.assertEqual(_sha(art._pread(descriptor, span_size, base + offset)),
                                 targets["NAVTEXTURE"]["span_sha256"])
            finally:
                os.close(descriptor)


if __name__ == "__main__":
    unittest.main()
