"""Synthetic composition tests for APF exact-slot build overlays.

Every byte in this module is generated by the test.  No retail game payload,
preimage, archive table, or audio packet is embedded here.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from types import SimpleNamespace
import tempfile
import unittest
from unittest.mock import patch

from mod_editor.apf_studio.build import (
    ApfBuildService,
    BuildError,
    _CompiledBuildSpan,
)
from mod_editor.apf_studio.models import (
    AUDO_EXACT_SLOT_KIND,
    AUDO_EXACT_SLOT_WRITER_SCHEMA,
    ApfSource,
    Modification,
)
import apf_audo_exact_slot


PACKET_SIZE = 0x800
OUTER_LAYOUT = (
    (0, 0x0000, 0x1800),
    (1, 0x1800, 0x1000),
    (2, 0x3000, 0x0100),
)
OVERLAY_OFFSETS = {(0, 0): 0x1000, (1, 0): 0x2000, (0, 1): 0x1000}


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _packet(fill: int) -> bytes:
    # 0x08000000 is the synthetic APF-compatible XMA1 packet header shape:
    # sequence 0, metadata 2, first-frame offset 0, packet skip 0.
    return b"\x08\x00\x00\x00" + bytes((fill,)) * (PACKET_SIZE - 4)


def _source(root: Path) -> ApfSource:
    data = (bytes(range(256)) * 64)[:0x4000]
    (root / "0A").write_bytes(data)
    return ApfSource(
        selected_path=root,
        game_root=root,
        index_0a=root / "0A",
        source_sha256=_sha256(data),
        source_size=len(data),
        xex_sha256="f" * 64,
        display_name="Synthetic overlay fixture",
    )


def _complete_tree(root: Path) -> dict[str, tuple[int, str]]:
    siblings = {
        "0B": b"synthetic-0b",
        "1A": b"synthetic-1a",
        "1B": b"synthetic-1b",
        "default.xex": b"synthetic-xex",
        "$SystemUpdate/su20076000_00000000": b"synthetic-update",
    }
    for relative, data in siblings.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
    values = {"0A": (root.joinpath("0A").stat().st_size, _sha256(root.joinpath("0A").read_bytes()))}
    values.update(
        (relative, (len(data), _sha256(data)))
        for relative, data in siblings.items()
    )
    return values


def _copy_complete_tree(
    source_root: Path,
    output_root: Path,
    tree: dict[str, tuple[int, str]],
) -> None:
    output_root.mkdir()
    for relative in tree:
        destination = output_root / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes((source_root / relative).read_bytes())


def _future_span(
    source: ApfSource,
    pack_name: str,
    offset: int,
    data: bytes,
    *,
    outer_index: int,
    reparse_owner: bool,
) -> _CompiledBuildSpan:
    source_data = (source.game_root / pack_name).read_bytes()
    return _CompiledBuildSpan(
        pack_name=pack_name,
        offset=offset,
        data=data,
        outer_index=outer_index,
        asset_ids=(f"synthetic:{pack_name}:{offset}",),
        kind="synthetic_future_typed_audio",
        writer_schema="synthetic_future_typed_audio/v1",
        reparse_owner=reparse_owner,
        source_span_sha256=_sha256(source_data[offset : offset + len(data)]),
    )


def _archive(index_path: Path) -> object:
    entries = []
    for table_index, offset, size in OUTER_LAYOUT:
        entries.append(
            SimpleNamespace(
                table_index=table_index,
                name_id=0x1000 + table_index,
                offset_blocks=offset,
                size_blocks=size,
                size=size,
                head_hex="ff3bef94",
                segments=(
                    SimpleNamespace(
                        pack_ordinal=0,
                        pack_name="0A",
                        pack_offset=offset,
                        size=size,
                    ),
                ),
            )
        )
    return SimpleNamespace(
        alignment=1,
        entries=tuple(entries),
        packs=(SimpleNamespace(ordinal=0, path=Path(index_path)),),
    )


def _target() -> apf_audo_exact_slot.ExactSlotTarget:
    return apf_audo_exact_slot.ExactSlotTarget(
        channels=1,
        sample_rate=22_050,
        encoded_size=PACKET_SIZE,
        declared_sample_count=1_024,
        loop_start_bit=0,
        loop_end_bit=PACKET_SIZE * 8,
        loop_subframe=0,
    )


def _audio_modification(
    root: Path, outer_index: int, inner_index: int, fill: int
) -> Modification:
    asset_id = f"apf:audio:audo:{outer_index}:{inner_index}"
    payload = _packet(fill)
    path = root / f"replacement-{outer_index}-{inner_index}.xma1-packets"
    path.write_bytes(payload)
    target = _target()
    return Modification(
        asset_id=asset_id,
        kind=AUDO_EXACT_SLOT_KIND,
        replacement_path=path,
        replacement_sha256=_sha256(payload),
        metadata={
            "outer_table_index": outer_index,
            "inner_file_index": inner_index,
            "encoded_size": target.encoded_size,
            "sample_rate": target.sample_rate,
            "channel_count": target.channels,
            "declared_sample_count": target.declared_sample_count,
            "packet_count": 1,
            "writer_schema": AUDO_EXACT_SLOT_WRITER_SCHEMA,
        },
    )


def _resolved(source: ApfSource, outer_index: int, inner_index: int) -> object:
    offset = OVERLAY_OFFSETS[(outer_index, inner_index)]
    return apf_audo_exact_slot.ResolvedExactSlot(
        asset_id=f"apf:audio:audo:{outer_index}:{inner_index}",
        name=f"synthetic_{outer_index}_{inner_index}",
        outer_index=outer_index,
        inner_index=inner_index,
        target=_target(),
        pack_name="0A",
        pack_offset=offset,
        encoded_size=PACKET_SIZE,
        source_payload_sha256=_sha256(
            source.index_0a.read_bytes()[offset : offset + PACKET_SIZE]
        ),
    )


class RawSpanOverlayBuildTests(unittest.TestCase):
    def setUp(self) -> None:
        # Composition fixtures use a synthetic archive, so the real complete
        # retail-domain scan is covered by dedicated audio safety tests.
        self.audio_gate = patch.object(
            ApfBuildService, "_reject_any_source_audio_reuse"
        )
        self.audio_gate.start()

    def tearDown(self) -> None:
        self.audio_gate.stop()

    def _patches(self, source: ApfSource, tree: dict[str, tuple[int, str]]):
        def resolve_many(
            _path: Path, coordinates: object
        ) -> dict[tuple[int, int], object]:
            return {
                coordinate: _resolved(source, *coordinate)
                for coordinate in tuple(coordinates)  # type: ignore[arg-type]
            }

        return (
            patch("mod_editor.apf_studio.build.EXPECTED_TREE", tree),
            patch(
                "mod_editor.apf_studio.build.EXPECTED_0A_SHA256",
                tree["0A"][1],
            ),
            patch(
                "mod_editor.apf_studio.build.apf_outer.parse_archive",
                side_effect=lambda path: _archive(Path(path)),
            ),
            patch(
                "mod_editor.apf_studio.build.apf_inner.parse_iff",
                side_effect=lambda _reader, entry: SimpleNamespace(
                    entry=entry, warnings=[]
                ),
            ),
            patch(
                "mod_editor.apf_studio.build.apf_audo_exact_slot.resolve_targets",
                side_effect=resolve_many,
            ),
        )

    def test_two_disjoint_audio_overlays_publish_one_exact_atomic_build(self) -> None:
        with tempfile.TemporaryDirectory(prefix="apf-overlay-compose-") as temporary:
            root = Path(temporary)
            game = root / "game"
            game.mkdir()
            source = _source(game)
            tree = _complete_tree(game)
            modifications = (
                _audio_modification(root, 0, 0, 0x41),
                _audio_modification(root, 1, 0, 0x52),
            )
            source_before = source.index_0a.read_bytes()
            output = root / "output"
            contexts = self._patches(source, tree)
            with contexts[0], contexts[1], contexts[2], contexts[3], contexts[4] as resolve_many:
                receipt = ApfBuildService(source).build(modifications, output)
            resolve_many.assert_called_once_with(
                source.index_0a, ((0, 0), (1, 0))
            )

            expected = bytearray(source_before)
            for modification in modifications:
                fields = modification.asset_id.split(":")
                offset = OVERLAY_OFFSETS[(int(fields[3]), int(fields[4]))]
                expected[offset : offset + PACKET_SIZE] = (
                    modification.replacement_path.read_bytes()
                )
            self.assertEqual((output / "0A").read_bytes(), bytes(expected))
            self.assertEqual(source.index_0a.read_bytes(), source_before)
            self.assertEqual(receipt.changed_outer_entries, (0, 1))
            self.assertEqual(
                receipt.modified_assets,
                ("apf:audio:audo:0:0", "apf:audio:audo:1:0"),
            )
            manifest = json.loads(receipt.manifest.read_text(encoding="utf-8"))
            self.assertEqual(manifest["compiled_entry_count"], 0)
            self.assertEqual(manifest["compiled_span_count"], 2)
            self.assertEqual(manifest["compiled_raw_overlay_count"], 2)
            self.assertEqual(manifest["compiled_span_packs"], ["0A"])
            self.assertTrue(manifest["output"]["published_atomically"])
            self.assertTrue(
                manifest["verification"]["all_changed_entries_reparsed"]
            )
            self.assertTrue(
                manifest["verification"][
                    "all_bytes_outside_compiled_spans_identical"
                ]
            )
            self.assertEqual(list(root.glob(".output.building-*")), [])

    def test_overlapping_audio_slots_are_rejected_before_any_output_exists(self) -> None:
        with tempfile.TemporaryDirectory(prefix="apf-overlay-collision-") as temporary:
            root = Path(temporary)
            game = root / "game"
            game.mkdir()
            source = _source(game)
            tree = _complete_tree(game)
            modifications = (
                _audio_modification(root, 0, 0, 0x61),
                _audio_modification(root, 0, 1, 0x62),
            )
            source_before = source.index_0a.read_bytes()
            output = root / "output"
            contexts = self._patches(source, tree)
            with contexts[0], contexts[1], contexts[2], contexts[3], contexts[4]:
                with self.assertRaisesRegex(BuildError, "spans overlap"):
                    ApfBuildService(source).build(modifications, output)
            self.assertFalse(output.exists())
            self.assertEqual(source.index_0a.read_bytes(), source_before)
            self.assertEqual(list(root.glob(".output.building-*")), [])

    def test_audio_overlay_composes_with_disjoint_whole_entry_writer(self) -> None:
        with tempfile.TemporaryDirectory(prefix="apf-overlay-whole-entry-") as temporary:
            root = Path(temporary)
            game = root / "game"
            game.mkdir()
            source = _source(game)
            tree = _complete_tree(game)
            audio = _audio_modification(root, 0, 0, 0x71)
            png = root / "synthetic.png"
            png.write_bytes(b"synthetic replacement token")
            whole = Modification(
                asset_id="apf:uniform:jersey:00",
                kind="uniform",
                replacement_path=png,
                replacement_sha256=_sha256(png.read_bytes()),
                metadata={
                    "family": "jersey",
                    "asset_index": 0,
                    "outer_index": 2,
                },
            )
            source_before = source.index_0a.read_bytes()
            output = root / "output"
            contexts = self._patches(source, tree)
            with contexts[0], contexts[1], contexts[2], contexts[3], contexts[4], patch.object(
                ApfBuildService,
                "_compile",
                return_value=(2, b"W" * 0x100, "synthetic_whole_entry/v1"),
            ):
                receipt = ApfBuildService(source).build((audio, whole), output)

            expected = bytearray(source_before)
            expected[0x1000 : 0x1800] = audio.replacement_path.read_bytes()
            expected[0x3000 : 0x3100] = b"W" * 0x100
            self.assertEqual((output / "0A").read_bytes(), bytes(expected))
            self.assertEqual(source.index_0a.read_bytes(), source_before)
            self.assertEqual(receipt.changed_outer_entries, (0, 2))
            manifest = json.loads(receipt.manifest.read_text(encoding="utf-8"))
            self.assertEqual(manifest["compiled_entry_count"], 1)
            self.assertEqual(manifest["compiled_raw_overlay_count"], 1)
            self.assertEqual(manifest["compiled_span_count"], 2)

    def test_span_overlap_is_scoped_to_each_physical_pack(self) -> None:
        with self.assertRaisesRegex(BuildError, "invalid pack name"):
            _CompiledBuildSpan(
                pack_name="default.xex",
                offset=0,
                data=b"X",
                outer_index=0,
                asset_ids=("synthetic:invalid-pack",),
                kind="synthetic",
                writer_schema="synthetic/v1",
                reparse_owner=False,
            )

        same_offset_different_packs = (
            _CompiledBuildSpan(
                pack_name="0A",
                offset=4,
                data=b"AAAA",
                outer_index=0,
                asset_ids=("synthetic:0A",),
                kind="synthetic",
                writer_schema="synthetic/v1",
                reparse_owner=True,
            ),
            _CompiledBuildSpan(
                pack_name="0B",
                offset=4,
                data=b"BBBB",
                outer_index=0,
                asset_ids=("synthetic:0B",),
                kind="synthetic",
                writer_schema="synthetic/v1",
                reparse_owner=False,
            ),
        )
        ordered = ApfBuildService._normalize_compiled_spans(
            same_offset_different_packs
        )
        self.assertEqual([span.pack_name for span in ordered], ["0A", "0B"])

        overlapping_0b = same_offset_different_packs + (
            _CompiledBuildSpan(
                pack_name="0B",
                offset=6,
                data=b"CC",
                outer_index=1,
                asset_ids=("synthetic:0B:overlap",),
                kind="synthetic",
                writer_schema="synthetic/v1",
                reparse_owner=False,
            ),
        )
        with self.assertRaisesRegex(BuildError, "overlap in 0B"):
            ApfBuildService._normalize_compiled_spans(overlapping_0b)

    def test_future_0b_span_applies_and_verifies_without_owner_reparse(self) -> None:
        with tempfile.TemporaryDirectory(prefix="apf-overlay-future-0b-") as temporary:
            root = Path(temporary)
            game = root / "game"
            game.mkdir()
            source = _source(game)
            tree = _complete_tree(game)
            output = root / "output"
            _copy_complete_tree(game, output, tree)
            original_0a = (game / "0A").read_bytes()
            original_0b = (game / "0B").read_bytes()
            span = _future_span(
                source,
                "0B",
                2,
                b"WXYZ",
                outer_index=1,
                reparse_owner=False,
            )

            ApfBuildService._apply_compiled_spans(output, (span,))
            service = ApfBuildService(source)
            with patch(
                "mod_editor.apf_studio.build.EXPECTED_TREE", tree
            ), patch(
                "mod_editor.apf_studio.build.apf_outer.parse_archive",
                side_effect=lambda path: _archive(Path(path)),
            ), patch(
                "mod_editor.apf_studio.build.apf_inner.parse_iff"
            ) as parse_iff:
                output_0a_sha256 = service._verify_composed(
                    output, [span], lambda _stage, _done, _total: None
                )

            expected_0b = bytearray(original_0b)
            expected_0b[2:6] = b"WXYZ"
            self.assertEqual((output / "0B").read_bytes(), bytes(expected_0b))
            self.assertEqual((output / "0A").read_bytes(), original_0a)
            self.assertEqual(output_0a_sha256, _sha256(original_0a))
            parse_iff.assert_not_called()

            with (output / "0B").open("r+b") as stream:
                stream.seek(0)
                stream.write(b"!")
            with patch(
                "mod_editor.apf_studio.build.EXPECTED_TREE", tree
            ), patch(
                "mod_editor.apf_studio.build.apf_outer.parse_archive",
                side_effect=lambda path: _archive(Path(path)),
            ), self.assertRaisesRegex(
                BuildError, "0B changed outside the compiled APF edit spans"
            ):
                service._verify_composed(
                    output, [span], lambda _stage, _done, _total: None
                )

    def test_future_1a_and_1b_spans_apply_and_verify_in_their_own_packs(self) -> None:
        with tempfile.TemporaryDirectory(prefix="apf-overlay-future-1x-") as temporary:
            root = Path(temporary)
            game = root / "game"
            game.mkdir()
            source = _source(game)
            tree = _complete_tree(game)
            output = root / "output"
            _copy_complete_tree(game, output, tree)
            original_0a = (game / "0A").read_bytes()
            span_1a = _future_span(
                source,
                "1A",
                1,
                b"AA",
                outer_index=0,
                reparse_owner=False,
            )
            span_1b = _future_span(
                source,
                "1B",
                1,
                b"BB",
                outer_index=0,
                reparse_owner=False,
            )
            spans = [span_1b, span_1a]

            ApfBuildService._apply_compiled_spans(output, spans)
            with patch(
                "mod_editor.apf_studio.build.EXPECTED_TREE", tree
            ), patch(
                "mod_editor.apf_studio.build.apf_outer.parse_archive",
                side_effect=lambda path: _archive(Path(path)),
            ), patch(
                "mod_editor.apf_studio.build.apf_inner.parse_iff"
            ) as parse_iff:
                output_0a_sha256 = ApfBuildService(source)._verify_composed(
                    output, spans, lambda _stage, _done, _total: None
                )

            self.assertEqual((output / "1A").read_bytes()[1:3], b"AA")
            self.assertEqual((output / "1B").read_bytes()[1:3], b"BB")
            self.assertEqual(output_0a_sha256, _sha256(original_0a))
            parse_iff.assert_not_called()

    def test_failed_overlay_verification_never_publishes_partial_output(self) -> None:
        with tempfile.TemporaryDirectory(prefix="apf-overlay-atomic-failure-") as temporary:
            root = Path(temporary)
            game = root / "game"
            game.mkdir()
            source = _source(game)
            tree = _complete_tree(game)
            audio = _audio_modification(root, 0, 0, 0x7A)
            source_before = source.index_0a.read_bytes()
            output = root / "output"
            contexts = self._patches(source, tree)
            with contexts[0], contexts[1], contexts[2], contexts[3], contexts[4], patch.object(
                ApfBuildService,
                "_verify_composed",
                side_effect=BuildError("synthetic overlay verification failure"),
            ):
                with self.assertRaisesRegex(BuildError, "overlay verification failure"):
                    ApfBuildService(source).build((audio,), output)
            self.assertFalse(output.exists())
            self.assertEqual(source.index_0a.read_bytes(), source_before)
            self.assertEqual(list(root.glob(".output.building-*")), [])


if __name__ == "__main__":
    unittest.main()
