"""Standalone offline playlist proofs. No disc/pack is loaded; no audio runs."""
from pathlib import Path
import os
import shutil
import struct
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from mod_editor.core import nfl2k5_music_playlist as playlist
from mod_editor.core import nfl2k5_music_playlist_code as assembly
from mod_editor.core import nfl2k5_xbe_space as space
from mod_editor.core.nfl2k5_cave_oracle import XbeImage
from mod_editor.core.nfl2k5_bump_strength import _sections, section_digest

try:
    import unicorn as u
    from unicorn.x86_const import (UC_X86_REG_EAX, UC_X86_REG_EBX, UC_X86_REG_ECX,
        UC_X86_REG_EDX, UC_X86_REG_ESI, UC_X86_REG_EDI, UC_X86_REG_EBP,
        UC_X86_REG_ESP, UC_X86_REG_EIP)
except ImportError:
    u = None
XBE = Path(os.environ.get('NFL2K5_RETAIL_EXTRACTION', '/media/noah/Storage/for codex 1.0/extracted')) / 'ESPN NFL 2K5 (USA)/default.xbe'


def repin(payload):
    out = bytearray(payload)
    for s in _sections(payload):
        out[s.header_offset + 36:s.header_offset + 56] = section_digest(out, s)
    return bytes(out)


class ConfigurationTests(unittest.TestCase):
    def test_defaults_outtakes_and_audited_beds(self):
        self.assertEqual(len(playlist.Selection().enabled), 66)
        self.assertEqual(len(playlist.selection(include_outtakes=False).enabled), 54)
        self.assertEqual(len(playlist.selection(include_beds=True).enabled), 76)
        self.assertEqual(len(playlist.selection(include_beds=True, include_outtakes=False).enabled), 64)
        self.assertFalse(any(b == 'drafta' for b, _ in playlist.BEDS))
        self.assertEqual([i for b, i in playlist.BEDS if b == 'halftimeaudio'], [3])

    def test_source_resolution_and_invalid_configuration(self):
        playlist.validate_source(playlist.Selection(), playlist.BANK_COUNTS)
        for selected, counts in ((playlist.Selection(), {}),
                                 (playlist.Selection(), dict(playlist.BANK_COUNTS, cribmusic=58))):
            with self.assertRaises(playlist.PlaylistError):
                playlist.validate_source(selected, counts)
        for records, enabled in (((('femusic', -1),), None), ((('femusic', True),), None),
                                 ((('bad', 0),), None), (playlist.CORE, (66,)),
                                 (playlist.CORE, (0, 0)), (playlist.CORE, (True,)),
                                 ((('femusic', 0), ('femusic', 0)), None),
                                 (tuple(('cribmusic', i) for i in range(101)), None)):
            with self.assertRaises(playlist.PlaylistError):
                playlist.Selection(records, enabled)
        selected = playlist.Selection(tuple(('cribmusic', i) for i in range(100)))
        playlist.validate_source(selected, {'cribmusic': 200})
        ro = playlist.ro_for(selected, 0x1506000)
        self.assertEqual(playlist._decode_ro(ro, 0x1506000), selected)
        self.assertEqual(len(ro), 1024)

    @unittest.skipUnless(shutil.which('as'), 'GNU assembler is absent; generated bytes remain runtime independent')
    def test_assembler_reproduction(self):
        subprocess.run([sys.executable, 'tools/nfl2k5_music_playlist_assemble.py', '--check'], check=True)
        self.assertLessEqual(len(assembly.CODE), 2048)
        self.assertEqual(playlist.REQUESTS, ((playlist.OWNER, 'code', 2048, 16),
                         (playlist.OWNER, 'data', 512, 16), (playlist.OWNER, 'read_only', 1024, 16)))


@unittest.skipUnless(XBE.is_file(), 'USA retail default.xbe evidence is absent')
class PatchTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.retail = XBE.read_bytes()
        cls.patched, cls.receipt = playlist.apply(cls.retail)

    def test_exact_replay_sections_zero_state_and_report(self):
        self.assertEqual(playlist.status(self.retail), 'retail')
        self.assertEqual(playlist.status(self.patched), 'applied')
        self.assertEqual(playlist.apply(self.patched)[0], self.patched)
        self.assertFalse(self.receipt['runtime_witnessed'])
        code, data, ro = playlist.sites(self.patched)
        image = XbeImage(self.patched)
        self.assertFalse(image.runtime_writable(code['va'], code['size']))
        self.assertFalse(image.runtime_writable(ro['va'], ro['size']))
        self.assertTrue(image.runtime_writable(data['va'], data['size']))
        self.assertEqual(image.read(data['va'], data['size']), bytes(512))
        self.assertTrue(all(section_digest(self.patched, s) == s.stored_digest for s in _sections(self.patched)))
        with self.assertRaises(playlist.PlaylistError):
            playlist.apply(self.patched, selection=playlist.selection(include_outtakes=False))

    def test_module_command_writes_only_new_bounded_executable(self):
        with tempfile.TemporaryDirectory() as folder, patch('builtins.print'):
            root = Path(folder).resolve()
            source, target = root/'source.xbe', root/'target.xbe'
            source.write_bytes(self.patched)
            self.assertEqual(playlist.main(['status',str(source)]), 0)
            self.assertEqual(playlist.main(['apply',str(source),str(target)]), 0)
            self.assertEqual(target.read_bytes(),self.patched)
            with self.assertRaises(FileExistsError):
                playlist.main(['apply',str(source),str(target)])
            with source.open('wb') as handle: handle.truncate(16*1024**2+1)
            with self.assertRaisesRegex(ValueError,'16 MiB'):
                playlist.main(['status',str(source)])

    def test_mixed_hook_code_ro_state_and_dependency_refuse_before_mutation(self):
        image = XbeImage(self.patched)
        code, data, ro = playlist.sites(self.patched)
        # Repin ordinary section digests so rejection is deeper than a stale SHA1.
        for va in (0x2801A0, 0x28021A, code['va'], ro['va'] + 192, data['va']):
            with self.subTest(va=hex(va)):
                bad = bytearray(self.patched)
                bad[image.offset(va)] ^= 1
                bad = repin(bad)
                before = bytes(bad)
                self.assertEqual(playlist.status(bad), 'foreign')
                with self.assertRaises(playlist.PlaylistError):
                    playlist.apply(bad)
                self.assertEqual(bad, before)
        allocated, _ = space.apply(self.retail, playlist.REQUESTS, scaleout=True)
        code, data, ro = playlist.sites(allocated)
        partial, _ = space.install_read_only(allocated, playlist.OWNER, playlist.ro_for(playlist.Selection(), ro['va']))
        self.assertEqual(playlist.status(partial), 'foreign')
        with self.assertRaises(playlist.PlaylistError):
            playlist.apply(partial)

    def test_empty_one_two_and_filtered_on_disc(self):
        for n in (0, 1, 2, 66):
            with self.subTest(n=n):
                selected = playlist.Selection(playlist.CORE[:n])
                out, _ = playlist.apply(self.retail, selection=selected)
                self.assertEqual(playlist.read_settings(out)['enabled'], list(range(n)))
                self.assertEqual(selected.status(out), 'applied')
                self.assertEqual(selected.apply(out)[0], out)


class Machine:
    """Bounded x86 with actual packet/range/modal routines, stubbed I/O only.

    Every entry is capped at 30,000 instructions / 200,000 microseconds and
    must reach a return sentinel with preserved callee-saved registers/stack.
    """
    STACK, STOP, DESCRIPTORS = 0x3000000, 0x3010000, 0x4000000

    def __init__(self, payload, selected=None):
        self.uc = u.Uc(u.UC_ARCH_X86, u.UC_MODE_32)
        self.uc.mem_map(0x10000, 0x1600000)
        image = XbeImage(payload)
        for sec in image.sections:
            if sec.raw_size:
                self.uc.mem_write(sec.start, payload[sec.raw:sec.raw + sec.raw_size])
        self.code, self.data, self.ro = playlist.sites(payload)
        self.state = self.data['va']
        _, self.labels = playlist.code_for(self.code['va'], self.state, self.ro['va'])
        if selected is not None:
            self.uc.mem_write(self.ro['va'], playlist.ro_for(selected, self.ro['va']))
        self.uc.mem_map(self.STACK, 0x20000)
        self.uc.mem_map(self.DESCRIPTORS, 0x10000)
        for row in (self.code, self.ro):
            start = row['va'] & -4096
            self.uc.mem_protect(start, ((row['va'] + row['size'] - start + 4095) & -4096),
                                u.UC_PROT_READ | (u.UC_PROT_EXEC if row is self.code else 0))
        text = image.section(0x2801A0)
        self.uc.mem_protect(text.start & -4096, ((text.end & -4096) - (text.start & -4096)), u.UC_PROT_READ | u.UC_PROT_EXEC)
        self.bank_descriptors = {}
        for n, (bank, count) in enumerate(playlist.BANK_COUNTS.items()):
            at = self.DESCRIPTORS + n * 4096
            self.bank_descriptors[bank] = at
            self.write(at + 0x40, count)
            self.write(at + 0x48, 72)
            self.write(at + 0x4c, 22050)
            for i in range(count + 1):
                self.write(at + 0x58 + 4 * i, i * 720)
        self.queued, self.calls, self.writes = [], [], []
        self.rng = 0x10203040
        self.stub_addresses = {playlist.SYMBOLS[k]: k for k in (
            'retail_rng', 'resource_lookup', 'bind_bank', 'stop_stream', 'bind_volume',
            'queue_packet', 'stop_hdd', 'game_music_switch', 'loading_start')}
        # Native modal tails dispatch through these I/O wrappers.
        self.stub_addresses.update({0xCF060: 'pause_stream', 0xCF070: 'resume_stream'})
        self.uc.hook_add(u.UC_HOOK_CODE, self._hook)
        self.uc.hook_add(u.UC_HOOK_MEM_WRITE, lambda uc, access, at, size, value, _: self.writes.append((at, size)))

    def read(self, at):
        return struct.unpack('<I', self.uc.mem_read(at, 4))[0]

    def write(self, at, value):
        self.uc.mem_write(at, struct.pack('<I', value & 0xffffffff))

    def field(self, off):
        return self.read(self.state + off)

    def _return(self, eax=0, pop=0):
        sp = self.uc.reg_read(UC_X86_REG_ESP)
        self.uc.reg_write(UC_X86_REG_EAX, eax)
        self.uc.reg_write(UC_X86_REG_EIP, self.read(sp))
        self.uc.reg_write(UC_X86_REG_ESP, sp + 4 + pop)

    def _hook(self, uc, at, size, _):
        if at == self.STOP:
            uc.emu_stop()
            return
        name = self.stub_addresses.get(at)
        if name is None:
            return
        self.calls.append(name)
        if name == 'retail_rng':
            self.rng = (1664525 * self.rng + 1013904223) & 0xffffffff
            self._return(self.rng)
        elif name == 'resource_lookup':
            ptr = self.read(uc.reg_read(UC_X86_REG_ESP) + 4)
            chars = bytearray()
            while len(chars) < 64:
                pair = bytes(uc.mem_read(ptr + len(chars), 2))
                if pair == b'\0\0':
                    break
                chars.extend(pair)
            self._return(self.bank_descriptors.get(chars.decode('utf-16le'), 0), 4)
        elif name == 'queue_packet':
            ptr = uc.reg_read(UC_X86_REG_EDX)
            self.queued.append((self.field(40), bytes(uc.mem_read(ptr, 0x3d4)), self.field(48)))
            self._return()
        else:
            self._return()

    def run(self, label, *, ecx=0, edx=0, arg=None, args=()):
        at = self.labels[label] if isinstance(label, str) else label
        sp = self.STACK + 0xf000
        self.write(sp, self.STOP)
        assert arg is None or not args
        args = (arg,) if arg is not None else args
        for index, value in enumerate(args):
            self.write(sp + 4 + index * 4, value)
        uc = self.uc
        preserved = {UC_X86_REG_EBX: 0x11111111, UC_X86_REG_ESI: 0x22222222,
                     UC_X86_REG_EDI: 0x33333333, UC_X86_REG_EBP: 0x44444444}
        for reg, value in preserved.items():
            uc.reg_write(reg, value)
        uc.reg_write(UC_X86_REG_ESP, sp)
        uc.reg_write(UC_X86_REG_ECX, ecx)
        uc.reg_write(UC_X86_REG_EDX, edx)
        uc.emu_start(at, self.STOP + 1, timeout=200000, count=30000)
        assert uc.reg_read(UC_X86_REG_EIP) == self.STOP, 'Bound expired without return'
        assert uc.reg_read(UC_X86_REG_ESP) == sp + 4 + 4 * len(args), 'Stack ABI'
        for reg, value in preserved.items():
            assert uc.reg_read(reg) == value, f'Callee-saved register {reg}'
        return uc.reg_read(UC_X86_REG_EAX)

    def complete(self):
        return self.run('completion', ecx=0, edx=self.field(48))


@unittest.skipUnless(XBE.is_file() and u is not None, 'USA retail XBE or Unicorn is absent; bounded native proof unavailable')
class InstructionTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.patched, _ = playlist.apply(XBE.read_bytes())

    def machine(self, n=66, enabled=None):
        return Machine(self.patched, playlist.Selection(playlist.CORE[:n], enabled))

    def test_full_cycles_zero_one_two_66_and_no_boundary_repeat(self):
        for n in (0, 1, 2, 66):
            with self.subTest(n=n):
                vm = self.machine(n)
                previous = None
                for cycle in range(4):
                    got = [vm.run('next_item') for _ in range(max(n, 1))]
                    self.assertEqual(set(got), set(range(n)) if n else {0xffffffff})
                    if n > 1:
                        self.assertEqual(len(set(got)), n)
                        self.assertNotEqual(previous, got[0])
                    previous = got[-1]
                if n > 1:
                    self.assertEqual(vm.calls.count('retail_rng'), 4 * (n - 1))

    def test_100_items_and_actual_memo_rng(self):
        selected = playlist.Selection(tuple(('cribmusic', i) for i in range(100)))
        vm = Machine(self.patched, selected)
        # Run the actual 48BC0 -> 48B50 generator with a bounded synthetic
        # 55-pair retail RNG state. No stub determines the shuffle here.
        del vm.stub_addresses[0x48BC0]
        vm.write(0xB12680, 54)
        vm.write(0xB12684, 31)
        for i in range(110):
            vm.write(0xB12688 + 4 * i, (i + 1) * 7919)
        first = [vm.run('next_item') for _ in range(100)]
        second = [vm.run('next_item') for _ in range(100)]
        self.assertEqual(set(first), set(range(100)))
        self.assertEqual(set(second), set(range(100)))
        self.assertNotEqual(first[-1], second[0])
        self.assertNotEqual(first, second)
        self.assertNotEqual(vm.field(16), 0)

    def test_actual_enqueue_two_banks_callback_and_native_frame(self):
        vm = self.machine()
        vm.run(0xF6510, ecx=1)
        for _ in range(65):
            vm.complete()
            self.assertEqual(vm.field(32), 1)
            vm.run(0x280620, arg=0)
        self.assertEqual(set(q[0] for q in vm.queued), set(range(66)))
        self.assertEqual(len(vm.queued), 66)
        # Real packet builders must encode our callback and generation cookie.
        for ordinal, packet, generation in vm.queued:
            self.assertIn(struct.pack('<2I', vm.labels['completion'], generation), packet)
        allowed_globals = {0xC5D398, 0xC5D3A4, 0xC3CC0C, 0xC3AC90, 0xB9E290, 0xC3CC08}
        for at, size in vm.writes:
            self.assertTrue(vm.state <= at < vm.state + 512 or vm.STACK <= at < vm.STACK + 0x20000
                            or at in allowed_globals, f'Unexpected runtime write {at:#x}/{size}')

    def test_retail_manual_advance_uses_bag_and_retains_modal_pause(self):
        vm = self.machine(2)
        vm.run('enqueue')
        first = vm.field(40)
        vm.run(0x27F040)
        vm.run(0x27F040)
        vm.run(0x280620, arg=0)
        self.assertEqual(len(vm.queued), 2)
        self.assertNotEqual(vm.field(40), first)
        vm.run(0x27F6B0)
        vm.run(0x27F040)
        vm.run(0x280620, arg=0)
        self.assertEqual(len(vm.queued), 2)
        self.assertEqual(vm.field(24), 1)
        vm.run(0x27F6F0)
        vm.run(0x280620, arg=0)
        self.assertEqual(len(vm.queued), 3)
        self.assertEqual(vm.field(40), first)

    def test_modal_pause_resume_pending_completion_and_generation(self):
        vm = self.machine(2)
        vm.run('enqueue')
        first, cursor, token = vm.field(40), vm.field(8), vm.field(48)
        vm.run(0x27F6B0)
        vm.run('enqueue')
        self.assertEqual(len(vm.queued), 1)
        self.assertEqual(vm.field(8), cursor)
        vm.run(0x27F6F0)
        self.assertIn('pause_stream', vm.calls)
        self.assertIn('resume_stream', vm.calls)
        self.assertEqual(vm.field(40), first)
        vm.run(0x27F6B0)
        vm.complete()
        vm.run(0x280620, arg=0)
        self.assertEqual(len(vm.queued), 1)
        self.assertEqual(vm.field(32), 1)
        vm.run(0x27F6F0)
        vm.run(0x280620, arg=0)
        self.assertEqual(len(vm.queued), 2)
        self.assertNotEqual(vm.field(40), first)
        vm.run('completion', ecx=0, edx=token)
        self.assertEqual(vm.field(28), 1)
        vm.complete()
        vm.complete()
        vm.run('frame')
        self.assertEqual(len(vm.queued), 3)

    def test_invalid_descriptor_index_and_boundary_never_bind_or_enqueue(self):
        for failure in ('missing', 'invalid', 'equal', 'reversed'):
            with self.subTest(failure=failure):
                vm = self.machine(1)
                ptr = vm.bank_descriptors['femusic']
                if failure == 'missing': vm.bank_descriptors['femusic'] = 0
                elif failure == 'invalid': vm.write(ptr + 0x40, 0)
                elif failure == 'equal': vm.write(ptr + 0x5c, 0)
                else: vm.write(ptr + 0x58, 1440)
                vm.run('enqueue')
                self.assertEqual(vm.queued, [])
                self.assertNotIn('bind_bank', vm.calls)
                self.assertEqual(vm.field(44), 1)
                self.assertEqual(vm.field(28), 0)
                self.assertEqual(vm.field(32), 0)

    def test_mask_changes_and_corrupt_cursor_or_ordinal_are_bounded(self):
        vm = self.machine()
        vm.run('next_item')
        for i in range(4): vm.write(vm.state + 64 + i * 4, 0)
        self.assertEqual(vm.run('next_item'), 0xffffffff)
        vm.write(vm.state + 64, 3)
        self.assertEqual({vm.run('next_item'), vm.run('next_item')}, {0, 1})
        vm.write(vm.state + 8, 0xffffffff)
        self.assertIn(vm.run('next_item'), (0, 1))
        vm.write(vm.state + 8, 0)
        vm.write(vm.state + 4, 2)
        vm.write(vm.state + 96, 0xffff)
        self.assertEqual(vm.run('next_item'), 0xffffffff)

    def test_modes_keep_position_loading_bed_and_unknown_mode_refuses(self):
        vm = self.machine(2)
        vm.run(0xF6510, ecx=1)
        first, cursor = vm.field(40), vm.field(8)
        for mode in (3, 4, 1):
            vm.run(0xF6510, ecx=mode)
            self.assertEqual(vm.field(40), first)
            self.assertEqual(vm.field(8), cursor)
            self.assertEqual(len(vm.queued), 1)
        vm.run(0xF6510, ecx=2)
        self.assertIn('loading_start', vm.calls)
        self.assertEqual(vm.field(28), 0)
        vm.run(0xF6510, ecx=1)
        self.assertEqual(vm.field(40), first)
        self.assertEqual(vm.field(8), cursor)
        self.assertEqual(len(vm.queued), 2)
        vm.run(0xF6510, ecx=0)
        vm.run(0xF6510, ecx=4)
        self.assertEqual(vm.field(40), first)
        before = bytes(vm.uc.mem_read(vm.state, 512))
        vm.run(0xF6510, ecx=5)
        self.assertEqual(bytes(vm.uc.mem_read(vm.state, 512)), before)


if __name__ == '__main__':
    unittest.main()
