"""Regenerate a game module's fragments from the canonical registry and allowlist.

While a game's rows also live in ``mod_editor/capabilities/registry.v1.json``
and its files in ``packaging/release-allowlist.txt``, the module's
``registry.fragment.json`` and ``allowlist.fragment.txt`` are mirrors, and
``pins.json`` records counts derived from them.  This module recomputes all
three from the canonical files so a mirror never drifts by hand:

    python -m mod_editor.games fragments <game-id> --check    # report differences
    python -m mod_editor.games fragments <game-id> --write    # rewrite them

Rules:

* the registry fragment is ``registry_merge.fragment_for(canonical, game_id)``
  -- when the canonical registry has no entry for the game, the committed
  fragment is authoritative and is left alone;
* the allowlist fragment is every non-comment canonical line matching one of
  the manifest's ``allowlist_patterns`` (case-insensitive globs), in canonical
  order, under the fragment's own comment header -- when no canonical line
  matches, the committed fragment is authoritative;
* ``pins.json`` keeps its schema and game id and gets the derived counts.

Standard library only.
"""

from __future__ import annotations

import argparse
import fnmatch
import json
from pathlib import Path
import sys
from typing import Optional, Sequence

from . import discover, manifests
from .contract import PINS_SCHEMA, ContractError, GameManifest
from .registry_merge import canonical_bytes, fragment_for

REPO_ROOT = Path(__file__).resolve().parents[2]
REGISTRY_RELATIVE = "mod_editor/capabilities/registry.v1.json"
ALLOWLIST_RELATIVE = "packaging/release-allowlist.txt"

#: Derived pins every module carries; a game may add its own keys beside them.
DERIVED_PINS = (
    "capability_rows", "surfaces", "hidden_disc_writers", "save_writer_ids",
    "shipped_files", "product_modules", "windows", "lanes_on_contract", "retail_identity",
)


def _read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _allowlist_lines(repo_root: Path) -> list[str]:
    path = repo_root / ALLOWLIST_RELATIVE
    if not path.is_file():
        return []
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


def matches(line: str, patterns: Sequence[str]) -> bool:
    folded = line.casefold()
    return any(fnmatch.fnmatchcase(folded, pattern.casefold()) for pattern in patterns)


def _header(existing: Optional[str], manifest: GameManifest) -> list[str]:
    if existing:
        header = []
        for raw in existing.splitlines():
            if raw.startswith("#"):
                header.append(raw)
            else:
                break
        if header:
            return header
    return [
        f"# Files {manifest.title} ships, one per line, repository-relative.",
        "# Regenerated by `python -m mod_editor.games fragments <game-id> --write` from",
        "# packaging/release-allowlist.txt using the manifest's allowlist_patterns.",
    ]


def expected_registry(manifest: GameManifest, repo_root: Path) -> Optional[bytes]:
    path = repo_root / REGISTRY_RELATIVE
    if not path.is_file():
        return None
    canonical = _read_json(path)
    if not any(game.get("id") == manifest.game_id for game in canonical.get("games", [])):
        return None
    return canonical_bytes(fragment_for(canonical, manifest.game_id))


def expected_allowlist(manifest: GameManifest, repo_root: Path) -> Optional[bytes]:
    selected = [line for line in _allowlist_lines(repo_root) if matches(line, manifest.allowlist_patterns)]
    if not selected:
        return None
    existing = None
    if manifest.allowlist_fragment_path.is_file():
        existing = manifest.allowlist_fragment_path.read_text(encoding="utf-8")
    return ("\n".join(_header(existing, manifest) + selected) + "\n").encode("utf-8")


def expected_pins(manifest: GameManifest, repo_root: Path, *, fragment: Optional[dict] = None,
                  allowlist: Optional[Sequence[str]] = None, games_root: Optional[Path] = None) -> bytes:
    fragment = fragment if fragment is not None else manifest.registry_document()
    lines = list(allowlist) if allowlist is not None else list(manifest.allowlist_lines())
    rows = fragment["capabilities"]
    existing: dict = {}
    if manifest.pins_path.is_file():
        try:
            existing = _read_json(manifest.pins_path)
        except ValueError:
            existing = {}
    report = discover(games_root)
    windows = lanes = 0
    for game in report.games:
        if game.game_id == manifest.game_id:
            windows, lanes = len(game.windows), len(game.lanes)
    document = dict(existing)
    document.update({
        "schema": PINS_SCHEMA,
        "game_id": manifest.game_id,
        "capability_rows": len(rows),
        "surfaces": list(fragment["surfaces"]),
        "hidden_disc_writers": sum(
            1 for row in rows if row["backend"]["operation"] == "write" and row["surface"] != "saves"
        ),
        "save_writer_ids": [
            row["id"] for row in rows if row["backend"]["operation"] == "write" and row["surface"] == "saves"
        ],
        "shipped_files": len(lines),
        "product_modules": len(manifest.product_modules),
        "windows": windows,
        "lanes_on_contract": lanes,
        "retail_identity": dict(fragment["game"]["retail_identity"]),
    })
    return (json.dumps(document, indent=2, sort_keys=True) + "\n").encode("utf-8")


def plan(game_id: str, *, repo_root: Path = REPO_ROOT, games_root: Optional[Path] = None
         ) -> tuple[GameManifest, dict[Path, Optional[bytes]], list[str]]:
    """``(manifest, {path: new bytes or None}, notes)`` without writing anything."""

    candidates = [item for item in manifests(games_root) if item.game_id == game_id]
    if not candidates:
        raise ContractError(f"No game module is called {game_id!r}.")
    manifest = candidates[0]
    notes: list[str] = []
    changes: dict[Path, Optional[bytes]] = {}

    registry = expected_registry(manifest, repo_root)
    if registry is None:
        notes.append(f"{REGISTRY_RELATIVE} has no {game_id!r} entry: the committed fragment is authoritative.")
        fragment = manifest.registry_document()
    else:
        changes[manifest.registry_fragment_path] = registry
        fragment = json.loads(registry.decode("utf-8"))

    allowlist = expected_allowlist(manifest, repo_root)
    if allowlist is None:
        notes.append(
            f"{ALLOWLIST_RELATIVE} has no line matching {list(manifest.allowlist_patterns)}: "
            "the committed allowlist fragment is authoritative."
        )
        lines = list(manifest.allowlist_lines())
    else:
        changes[manifest.allowlist_fragment_path] = allowlist
        lines = [line for line in allowlist.decode("utf-8").splitlines() if line and not line.startswith("#")]

    changes[manifest.pins_path] = expected_pins(
        manifest, repo_root, fragment=fragment, allowlist=lines, games_root=games_root
    )
    return manifest, changes, notes


def check(game_id: str, *, repo_root: Path = REPO_ROOT, games_root: Optional[Path] = None) -> list[str]:
    manifest, changes, _notes = plan(game_id, repo_root=repo_root, games_root=games_root)
    problems: list[str] = []
    for path, expected in changes.items():
        if expected is None:
            continue
        actual = path.read_bytes() if path.is_file() else b""
        if actual != expected:
            problems.append(f"{path.relative_to(manifest.root)} differs from the canonical files")
    return problems


def write(game_id: str, *, repo_root: Path = REPO_ROOT, games_root: Optional[Path] = None) -> list[Path]:
    _manifest, changes, _notes = plan(game_id, repo_root=repo_root, games_root=games_root)
    written: list[Path] = []
    for path, expected in changes.items():
        if expected is None:
            continue
        if not path.is_file() or path.read_bytes() != expected:
            path.write_bytes(expected)
            written.append(path)
    return written


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m mod_editor.games fragments", description=__doc__.splitlines()[0])
    parser.add_argument("game")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    parser.add_argument("--games-root", type=Path, help=argparse.SUPPRESS)
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT, help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    try:
        _manifest, _changes, notes = plan(args.game, repo_root=args.repo_root, games_root=args.games_root)
        for note in notes:
            print(f"note: {note}")
        if args.check:
            problems = check(args.game, repo_root=args.repo_root, games_root=args.games_root)
            for problem in problems:
                print(f"FRAGMENT DRIFT: {problem}")
            if problems:
                print(f"run: python -m mod_editor.games fragments {args.game} --write")
                return 1
            print(f"FRAGMENTS_OK game={args.game}")
            return 0
        written = write(args.game, repo_root=args.repo_root, games_root=args.games_root)
    except ContractError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    for path in written:
        print(f"wrote {path}")
    print(f"FRAGMENTS_WRITTEN game={args.game} files={len(written)}")
    return 0


__all__ = ["DERIVED_PINS", "check", "expected_allowlist", "expected_pins", "expected_registry", "matches", "plan", "write"]


if __name__ == "__main__":
    raise SystemExit(main())
