#!/usr/bin/env python3
"""PROVED OFFLINE: render cited staff and reproducible rate register."""
import json
from pathlib import Path
ROOT=Path(__file__).parent

def main():
    profiles=json.loads((ROOT/'defense_profiles.json').read_text());data=json.loads((ROOT/'defense_tendencies_2025.json').read_text())
    lines=['# INFERRED: 2026 defensive coordinators and scheme lineage','',
    'INFERRED: Staff names and prior jobs are sourced to each official biography below, cross-checked against [ESPN, current staffs, page 74, September 9](https://g.espncdn.com/s/ffldraftkit/26/NFLDK2026_CS_ClayProjections2026.pdf#page=74). Scheme families and odd/even base labels are coaching-lineage interpretations, not measured alignment rates. A DC title does not guarantee that coach calls the defense. The baseline column explicitly identifies the prior job for new coordinators; assistant-staff numbers are team tendencies, never personal playcalling percentages.','',
    'PROVED OFFLINE: Every percentage below is computed by [aggregate_defense.py](aggregate_defense.py) from the hashed [2025 release inputs, counts, denominators and coverage labels](defense_tendencies_2025.json). Sources: [nflverse participation](https://github.com/nflverse/nflverse-data/releases/tag/pbp_participation), [PBP](https://github.com/nflverse/nflverse-data/releases/tag/pbp), [public FTN charting](https://github.com/nflverse/nflverse-data/releases/tag/ftn_charting). Attribution: nflverse / FTN; derived charting data retains CC-BY-SA-4.0. No premium FTN access or unpublished numbers are claimed.','',
    'PROVED OFFLINE: Eligible snaps are regular-season run/pass plays excluding kneels and spikes. Nickel means exactly five DB positions; dime exactly six, among known eleven-player personnel. These include run snaps. Coverage and rush rates use QB dropbacks only, including sacks and scrambles, with separate known denominators. A missing coverage or zero/sentinel rusher count is excluded, not treated as zone or no blitz. Blitz means five or more counted rushers, not any off-ball rusher. [Participation dictionary](https://nflreadr.nflverse.com/articles/dictionary_participation.html), [FTN subset dictionary](https://nflreadr.nflverse.com/articles/dictionary_ftn_charting.html).','',
    'PROVED OFFLINE: The public FTN subset has no defensive shell, front or pressure-concept fields. Participation has coverage labels and aggregate rush counts but no rusher identities, alignment landmarks or pre-snap shell. Actual single-high/two-high, simulated-pressure and creeper rates are unavailable (NA) for every row. Single-family means Cover 1 + 3; split-family means Cover 2 + 2-Man + 4 + 6 + 9, divided by all known coverage labels. These post-snap family proxies are deliberately not called measured pre-snap shells. Cover 0 and combo/blown labels explain why family columns do not sum to 100.','',
    'DESIGN: The menu fit uses the available coverage-family counts and blitz rates. It merges Cover 9 into split-field Cover 6 because the encodable library has a fixed split-field orientation. Nickel/dime and aligned-front rates are research references, not promised menu-based personnel control. The engine responds to offensive personnel and game state. SD has no accessible Western Michigan coverage dataset; its real-rate cells remain NA and its design uses the disclosed 2025 LAC continuity fallback.','',
    '| Team | INFERRED 2026 DC / family / base | INFERRED 2025 baseline role | PROVED OFFLINE nickel / dime % | PROVED OFFLINE man / zone % | PROVED OFFLINE single / split family % | PROVED OFFLINE blitz / Cover 0 % | Actual shells / sim / creeper |','| --- | --- | --- | ---: | ---: | ---: | ---: | --- |']
    for t,p in profiles.items():
        r=data['teams'][p['baseline_team']]['rates'] if p['baseline_team'] else None
        def pair(a,b):return f"{r[a]:.1f} / {r[b]:.1f} [data](defense_tendencies_2025.json)" if r else 'NA / NA'
        lines.append(f"| {t} | [{p['dc']}]({p['source']}); {p['family']}; {p['base_front_inferred']} | {p['baseline_team'] or 'Western Michigan'}: {p['baseline_role']} | {pair('nickel','dime')} | {pair('man','zone')} | {pair('single_family','split_family')} | {pair('blitz','cover0')} | NA / NA / NA |")
    lines += ['', 'INFERRED: Front labels describe a family reference, not a promise to reproduce all current personnel. Authoring retains native roster/category codes. A Tite Look is authored geometry over that native personnel, not proof of three true NFL interior linemen or modern run-fit rules. Wide fronts use wider edge geometry; Bear is a retained stock formation with modern coverage assignments.','',
    'DESIGN: Stereotypes do not override the charted season. For example, Philadelphia has substantial man coverage in this source despite its Fangio lineage. Dallas inherits those disclosed staff rates rather than an invented two-high percentage. BAL reflects Weaver\'s last job, with the unmeasured Minter change noted. NYJ reflects Duker\'s last staff, with Glenn\'s 2026 playcalling noted.','',
    'PROVED OFFLINE: Reproduce with `python3 pb/research/aggregate_defense.py --data /media/noah/Storage/.b76-research/r1/data/nflverse --output pb/research/defense_tendencies_2025.json`, then `python3 pb/research/render_defenses.py`. Raw copyrighted charting and retail game assets are not copied into the repository.']
    (ROOT/'DEFENSES.md').write_text('\n'.join(lines)+'\n')
if __name__=='__main__':main()
