#!/usr/bin/env python3
"""Regenerate the shipped screen pins for the v2 books (beta 77, job p48o).

Screen timing (``nfl2k5_screen_timing``) recognises a book whose declared screens
(plays named "...screen...") were authored by the SOFTDRINK packs through
``COMPLETE_OFFENSE_D_PINS``: book-name hash -> screen signature of the compiled
offense.  A pinned book reports "applied" at level D and is left byte-for-byte alone.
This replaces pb/phase4.py --write-pins for the v2 generator (phase4 assumes the
v0.5 'RB Slip' shape).  PROVED OFFLINE; gameplay unwitnessed.
"""
from __future__ import annotations

import argparse
import hashlib
import pprint
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path[:0] = [str(ROOT), str(ROOT / "tools")]
from mod_editor.core import nfl2k5_playbook_inspector as insp  # noqa: E402
from mod_editor.core import nfl2k5_playbook_pack as packs  # noqa: E402
from mod_editor.core import nfl2k5_screen_timing as timing  # noqa: E402
from pb.v2.build import pack_path  # noqa: E402

PINS = ROOT / "mod_editor" / "core" / "nfl2k5_screen_authored_pins.py"


def team_pin(team: str, retail: bytes, xbe: bytes) -> tuple[str, str, int]:
    compiled = packs.apply_pack_to_resource(retail, packs.load_pack(pack_path(team)), asset_id="book:" + team, xbe=xbe)
    book = insp.parse_playbook_resource(compiled.replacement)
    screens = sum(1 for p in book.plays if "screen" in p.name.casefold())
    return hashlib.sha256(book.book_name.encode()).hexdigest(), timing._signature(book), screens


def write(pins: dict) -> None:
    PINS.write_text('"""PROVED OFFLINE: shipped D screen hashes, generated by pb/v2/pins.py (beta 77 p48o).\n'
                    "Each value is the declared-screen signature of the compiled SOFTDRINK offense for that book;\n"
                    "screen timing leaves a pinned book unchanged at level D.\n"
                    '"""\n\nCOMPLETE_OFFENSE_D_PINS = ' + pprint.pformat(pins, width=160, sort_dicts=True) + "\n",
                    encoding="utf-8", newline="\n")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--image", type=Path, required=True)
    ap.add_argument("--xbe", type=Path, required=True)
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--team", action="append", help="refresh only these teams, retaining the other shipped pins")
    args = ap.parse_args(argv)
    from nfl2k5_playbook_position_recode import OuterImage, BOOK_ENTRIES
    xbe = args.xbe.read_bytes()
    pins = dict(timing.COMPLETE_OFFENSE_D_PINS) if args.team else {}
    with OuterImage(args.image) as image:
        for team in args.team or packs.TEAM_BOOKS:
            key, signature, screens = team_pin(team, image.read_entry(BOOK_ENTRIES[team]), xbe)
            pins[key] = signature
            print(team, screens, "screens", signature[:16], flush=True)
    if args.write:
        write(pins)
        timing.COMPLETE_OFFENSE_D_PINS.clear()
        timing.COMPLETE_OFFENSE_D_PINS.update(pins)
    print(len(pins), "pins")


if __name__ == "__main__":
    main()
