"""Generated by tools/nfl2k5_music_playlist_assemble.py. EXPERIMENTAL / UNWITNESSED."""

CODE = bytes.fromhex(
    "833d0000000000753c60c7050000000001000000c7050c000000ffffffffc70528000000ffffffff"
    "c7051400000001000000be10000000bf40000000b904000000fcf3a561c35351525657e8fcffffff"
    "31c98b048d400000003b048d50000000741b89048d50000000c7050400000000000000c705080000"
    "00000000004183f90472cfa10800000083f8640f87d90000008b0d080000003b0d040000000f829b"
    "00000031db31ff3b3d0800000073150fa33d40000000730966893c5d600000004347ebe3891d0400"
    "0000c705080000000000000085db0f848e00000089de83fe017631e8fcffffffa31000000031d2f7"
    "f64e668b047560000000668b0c556000000066890c75600000006689045560000000ebca83fb0176"
    "230fb705600000003b050c0000007514668b0d6200000066890d6000000066a36200000031c983f9"
    "6473270fb7044d6000000041890d080000003b050800000073100fa305400000007307a30c000000"
    "eb05b8ffffffff5f5e5a595bc3e8fcffffff833d14000000000f84ce010000833d18000000000f85"
    "c1010000833d1c000000000f85b4010000833d34000000000f85a7010000833d38000000000f859a"
    "0100005589e583e4f881ecec03000056833d24000000007420a128000000c7052400000000000000"
    "3b050800000073090fa305400000007205e8fcffffffc70520000000000000003b05080000000f83"
    "2201000083f8640f830f010000a328000000ff34c5c0000000ba4155534231c9e8fcffffff85c00f"
    "84ef00000083f8ff0f84e600000089c6817e40000001000f87d7000000837e48000f84cd00000083"
    "7e4c000f84c3000000a1280000008b04c5c40000003b46400f83ae0000008b5486583b54865c0f83"
    "a0000000508d54241089f1e8fcffffff89f2b910ccc300e8fcffffffb910ccc300e8fcffffffc705"
    "a4d3c500010000008b1558ccc30085d2740ab910ccc300e8fcffffff8d4c2418e8fcffffffff0530"
    "000000ff3530000000ba000000008d4c241ce8fcffffff6a008d5424108d4c241ce8fcffffffc705"
    "1c00000001000000c7052c00000000000000c70590acc300010000008d542418b910ccc300e8fcff"
    "ffffeb2dc7052c00000001000000c7051c00000000000000c7052000000000000000c70598d3c500"
    "00000000e8fcffffff5e89ec5dc33b1530000000752c83f901742d833d1c00000001751ec7051c00"
    "000000000000c7052000000001000000c70598d3c50002000000b801000000c3c7051c0000000000"
    "0000c7052c00000002000000ebe4833d34000000007502ebd9c705340000000000000060e8fcffff"
    "ffc7052000000001000000c70598d3c5000200000061ebb2833d34000000007505e98ffdffff8b0d"
    "fccbc300e9b4000000e8fcffffff833d1c00000000740ac7052400000001000000c7051c00000000"
    "000000c7051800000000000000ff0530000000c70598d3c50000000000833da4d3c500027409833d"
    "a4d3c50004750ab95cccc300e8fcffffffe8fcffffffc70590acc30000000000c3c7051800000001"
    "000000a1a4d3c500e9fcffffffc7051800000000000000833d2000000000740ac70598d3c5000200"
    "0000a1a4d3c500e9fcffffff51e8fcffffff59c70534000000010000005589e583e4f8e9fcffffff"
    "85c974225689cebac0c0e600e8fcffffff85c0752589f1bad4c0e600e8fcffffff85c075155ee8fc"
    "ffffffc7051400000000000000e907ffffff5ee8fcffffff833d3400000000740fe8fcffffffc705"
    "3400000000000000c7051400000001000000c70508ccc30000000000e954fcffff83f90477555689"
    "cee8fcffffff893590e2b90085f6743383fe02741883fe04750731c9e8fcffffffb9c0c0e600e8fc"
    "ffffff5ec3c7051400000000000000e8fcffffffe8fcffffff5ec3c7051400000000000000e8fcff"
    "ffff5ec3833d90e2b900047505e9ebfbffffe921ffffff60e8fcffffff833d1c00000000740ac705"
    "2400000001000000c7051c00000000000000c7051800000000000000c7053400000000000000ff05"
    "3000000061e9fcffffff60e8fcffffff830d3800000001e8fcffffff615589e583e4f8e9fcffffff"
    "a1183bb700e8fcffffff60832538000000fee8fcffffff61c3e8fcffffff833d34000000000f8596"
    "fdffff833d14000000007431608b1d18000000e8fcffffff891d18000000c7052400000000000000"
    "c7052000000001000000c70598d3c5000200000061c3"
)
RELOCATIONS = (
    (2, 1, 'state_data', 0),
    (12, 1, 'state_data', 0),
    (22, 1, 'state_data', 0),
    (32, 1, 'state_data', 0),
    (42, 1, 'state_data', 0),
    (51, 1, 'playlist_ro', 0),
    (56, 1, 'state_data', 0),
    (76, 2, 'code', 0),
    (85, 1, 'state_data', 0),
    (92, 1, 'state_data', 0),
    (101, 1, 'state_data', 0),
    (107, 1, 'state_data', 0),
    (117, 1, 'state_data', 0),
    (132, 1, 'playlist_ro', 0),
    (147, 1, 'state_data', 0),
    (153, 1, 'state_data', 0),
    (169, 1, 'playlist_ro', 0),
    (178, 1, 'state_data', 0),
    (188, 1, 'state_data', 0),
    (198, 1, 'state_data', 0),
    (204, 1, 'state_data', 0),
    (228, 2, 'retail_rng', 0),
    (233, 1, 'state_data', 0),
    (246, 1, 'state_data', 0),
    (254, 1, 'state_data', 0),
    (262, 1, 'state_data', 0),
    (270, 1, 'state_data', 0),
    (284, 1, 'state_data', 0),
    (290, 1, 'state_data', 0),
    (299, 1, 'state_data', 0),
    (306, 1, 'state_data', 0),
    (312, 1, 'state_data', 0),
    (327, 1, 'state_data', 0),
    (334, 1, 'state_data', 0),
    (340, 1, 'playlist_ro', 0),
    (349, 1, 'state_data', 0),
    (356, 1, 'state_data', 0),
    (374, 2, 'code', 0),
    (380, 1, 'state_data', 0),
    (393, 1, 'state_data', 0),
    (406, 1, 'state_data', 0),
    (419, 1, 'state_data', 0),
    (432, 1, 'state_data', 0),
    (458, 1, 'state_data', 0),
    (466, 1, 'state_data', 0),
    (472, 1, 'state_data', 0),
    (482, 1, 'playlist_ro', 0),
    (491, 1, 'state_data', 0),
    (498, 2, 'code', 70),
    (504, 1, 'state_data', 0),
    (514, 1, 'playlist_ro', 0),
    (534, 1, 'state_data', 0),
    (541, 1, 'playlist_ro', 0),
    (553, 2, 'resource_lookup', 0),
    (610, 1, 'state_data', 0),
    (617, 1, 'playlist_ro', 0),
    (652, 2, 'range_copy', 0),
    (664, 2, 'bind_bank', 0),
    (674, 2, 'stop_stream', 0),
    (704, 2, 'bind_volume', 0),
    (713, 2, 'packet_init', 0),
    (719, 1, 'state_data', 0),
    (725, 1, 'state_data', 0),
    (730, 1, 'code', 854),
    (739, 2, 'packet_callback', 0),
    (754, 2, 'packet_range', 0),
    (760, 1, 'state_data', 0),
    (770, 1, 'state_data', 0),
    (798, 2, 'queue_packet', 0),
    (806, 1, 'state_data', 0),
    (816, 1, 'state_data', 0),
    (826, 1, 'state_data', 0),
    (845, 2, 'retail_stop_direct', 0),
    (856, 1, 'state_data', 0),
    (869, 1, 'state_data', 0),
    (878, 1, 'state_data', 0),
    (888, 1, 'state_data', 0),
    (914, 1, 'state_data', 0),
    (924, 1, 'state_data', 0),
    (936, 1, 'state_data', 0),
    (947, 1, 'state_data', 0),
    (957, 2, 'code', 1009),
    (963, 1, 'state_data', 0),
    (986, 1, 'state_data', 0),
    (1010, 2, 'code', 0),
    (1016, 1, 'state_data', 0),
    (1025, 1, 'state_data', 0),
    (1035, 1, 'state_data', 0),
    (1045, 1, 'state_data', 0),
    (1055, 1, 'state_data', 0),
    (1093, 2, 'stop_hdd', 0),
    (1098, 2, 'retail_stop_direct', 0),
    (1115, 1, 'state_data', 0),
    (1135, 1, 'state_data', 0),
    (1145, 1, 'state_data', 0),
    (1174, 2, 'code', 1009),
    (1181, 1, 'state_data', 0),
    (1213, 2, 'string_equal', 0),
    (1229, 2, 'string_equal', 0),
    (1239, 2, 'code', 0),
    (1245, 1, 'state_data', 0),
    (1260, 2, 'code', 0),
    (1266, 1, 'state_data', 0),
    (1274, 2, 'code', 1009),
    (1280, 1, 'state_data', 0),
    (1290, 1, 'state_data', 0),
    (1322, 2, 'code', 0),
    (1349, 2, 'game_music_switch', 0),
    (1359, 2, 'code', 1200),
    (1367, 1, 'state_data', 0),
    (1376, 2, 'code', 1009),
    (1381, 2, 'loading_start', 0),
    (1389, 1, 'state_data', 0),
    (1398, 2, 'code', 1009),
    (1425, 2, 'code', 0),
    (1431, 1, 'state_data', 0),
    (1440, 1, 'state_data', 0),
    (1450, 1, 'state_data', 0),
    (1460, 1, 'state_data', 0),
    (1470, 1, 'state_data', 0),
    (1480, 1, 'state_data', 0),
    (1492, 2, 'code', 0),
    (1498, 1, 'state_data', 0),
    (1504, 2, 'code', 1009),
    (1526, 2, 'retail_halftime_exit_tail', 0),
    (1533, 1, 'state_data', 0),
    (1539, 2, 'code', 373),
    (1546, 2, 'code', 0),
    (1552, 1, 'state_data', 0),
    (1565, 1, 'state_data', 0),
    (1575, 1, 'state_data', 0),
    (1580, 2, 'code', 1009),
    (1586, 1, 'state_data', 0),
    (1592, 1, 'state_data', 0),
    (1602, 1, 'state_data', 0),
    (1129, 2, 'retail_pause_tail', 0),
    (1168, 2, 'retail_resume_tail', 0),
    (1196, 2, 'retail_preview_tail', 0),
    (1486, 2, 'retail_player_init', 0),
    (1516, 2, 'retail_halftime_tail', 0),
)
LABELS = {
    'advance': 934,
    'boundary': 276,
    'callback_cancelled': 912,
    'callback_done': 906,
    'choose_next': 497,
    'completion': 854,
    'context': 1200,
    'context_start': 1258,
    'context_stop': 1238,
    'enqueue': 373,
    'enqueue_bad': 804,
    'enqueue_empty': 814,
    'enqueue_exit': 849,
    'enqueue_return': 853,
    'fill': 167,
    'filled': 196,
    'frame': 984,
    'halftime_enter': 1490,
    'halftime_exit': 1520,
    'init': 0,
    'init_done': 69,
    'manual_done': 1621,
    'manual_next': 1545,
    'mask_check': 82,
    'mask_same': 125,
    'mode': 1313,
    'mode_loading': 1365,
    'mode_play': 1353,
    'mode_return': 1403,
    'mode_stop': 1387,
    'native_advance': 945,
    'native_preview': 1189,
    'native_preview_next': 998,
    'next_done': 367,
    'next_item': 70,
    'no_item': 362,
    'omitted': 193,
    'packet': 708,
    'pause': 1113,
    'player_inactive': 1448,
    'player_init': 1423,
    'preview': 1172,
    'profile_context': 1404,
    'profile_other': 1418,
    'resume': 1133,
    'resume_tail': 1162,
    'selected': 502,
    'shared_start': 1288,
    'shuffle': 222,
    'stop_direct': 1097,
    'stop_hdd_player': 1087,
    'stopped': 1033,
    'suspend': 1009,
    'take_first': 316,
    'take_item': 318,
}
