"""Generated by tools/nfl2k5_qb_spy_runtime_assemble.py. EXPERIMENTAL / UNWITNESSED."""

CODE = bytes.fromhex(
    "68ee030000eb0568f90300005589e58d6424d09c6083e4f081ec000200000fae0424dbe389cbc745"
    "fc000000008b7320c745dc0000000085f60f8449030000817d047e06000072228b861003000085c0"
    "0f84320300008945dc8b108955d88b50408955d48b50488955d0bf4000000031d2b916000000391f"
    "7416833f00750289fa83c720e2f089d785ff0f84f80200008b861c040000397704750d3947087508"
    "8b4b3c394f187415891f8977048947088b433c894718c7471400000000837f14030f84c1020000f7"
    "862004000000000020750de82c03000085c00f849d020000833db802e6000e0f85900200008b4338"
    "3b058402e6000f85810200008b430c85c00f84760200008338ff0f856d020000f68684050000200f"
    "8560020000a1ec02e60085c00f84530200008b481881e1ffffff7f81f9002474490f833e02000083"
    "b8c4010000000f853102000083b8c8010000000f8524020000a100fce50085c00f84170200008b10"
    "85d20f840d020000837a1c010f85030200003b158c4fbe000f85de0100008b423c85c00f84ec0100"
    "00807835000f85e20100008b42383b058002e6000f85ba0100008b421885c00f84c8010000528d48"
    "30ba080000008b0125ffffff7f3d002474490f839101000083c1044a75e85a8b4218837f1400751f"
    "3b15000000000f859101000089570c8b0d04000000894f10c747140100000039570c0f855c010000"
    "8955f88b0d8002e6008b49088b490c8b410425ffffff7f3d0000807f0f8353010000d94104d9e4df"
    "e0ddd8c745f401000000f6c4417407c745f4ffffffff8b4218837f14027453d94030d86710d9e1d8"
    "1d08000000dfe0f6c44574378b4218d940388b0dec02e600d86118db45f4dec9d81d04000000dfe0"
    "f6c405752e8b4218d94048db45f4dec9d9e4dfe0ddd8f6c4457518c74714020000008b42188b4830"
    "894de08b4838894de8eb3f8b4218d94040d80d0c000000d84030d90510000000dbf1dbd1ddd9d905"
    "14000000dbf1dac1ddd9d95de0db45f4d80d000000008b0dec02e600d84118d95de88b8610030000"
    "895040c7404800000000c745e400000000c745ec0000000089d98d55e0837f140274136a00680000"
    "803f6a005231d2e8fcffffffeb2a6a00689a99193f6a0068ec51b83e68e17a743f6a006a0131c083"
    "7df4017505b80080000050e8fcffffffc745fc01000000eb275aeb19837f1400741ee85900000089"
    "dab930b32e00e8fcffffffebdb837f14007405e8400000008b45dc85c0741b39861003000075138b"
    "55d83910750c8b55d48950408b55d08950480fae0c24837dfc008d65ac6175059d89ec5dc39d89ec"
    "5d8d64240431c0c3c747140300000081a620040000ffffffdf8b8610030000c7404000000000c740"
    "4800000000c35589e583e4f0e9fcffffff5589e583e4f0e9fcffffff608bbe1c040000bb405ab700"
    "89f829d83d90330100721581c39033010089f829d83d903301000f83d30000002d043400003d3865"
    "00000f83c300000031d2b960000000f7f1f7c2070000000f85ae000000c1ea0383fa0b0f83a20000"
    "00c1e21009d00d000000018945f08b7330e8980000000f82870000008945f88b45f00fb7c06bc060"
    "8bb403fc330000e87a000000726d8945f48b0783e00f83f802756089feb904000000b8c59d1c81e8"
    "900000008b770489f229da81eadc9a000081fa506d0000773ab910000000e871000000be10000000"
    "8b0d0800000085c9742139460875178b55f0395604750f8b55f8391675088b55f439560c740983c6"
    "10e2db6131c0c361b801000000c389f229da81fa40080100722681fa10330100771eb8c59d1c81b9"
    "4000000066833e00741051b902000000e80700000059e2ecf9c3f8c30fb61631d069c09301000146"
    "e2f2c39c60fcbf0000000031c0b9c0000000f3aba18c4fbe0085c074258b501885d2741e8b523089"
    "d181e1ffffff7f81f900247449730ba300000000891504000000619dc705b802e6000e000000e9fc"
    "ffffff9c6089ca81ea1c040000e830000000619d31c039c2894104e9fcffffff9c608b512081a220"
    "040000ffffffdfe80e000000619d0fbe412e8b5e0ce9fcffffffbf40000000b91600000039570475"
    "14c70700000000c7470400000000c747140000000083c720e2e2c36800000000eb0c6800000000eb"
    "05680000000051ff5424049c608b4424248b5020e8b1ffffff619d8d642408c3687e060000e9caf9"
    "ffff6889060000e9c0f9ffff6894060000e9b6f9ffff689e060000e9acf9ffff68a9060000e9a2f9"
    "ffff68b7060000e998f9ffff68c2060000e98ef9ffff5589e583e4f0e9fcffffff5689ce8b4620e9"
    "fcffffff83ec185355e9fcffffff5589e583e4f0e9fcffffff8b41208b9010030000e9fcffffff8b"
    "41108b4004e9fcffffff5589e583e4f0e9fcffffffcccccc48e1b64348e1b6c2f62889430000003f"
    "48410745484107c5"
)
RELOCATIONS = (
    (1, 1, 'code', 0),
    (8, 1, 'code', 0),
    (66, 1, 'code', 0),
    (107, 1, 'state_data', 0),
    (482, 1, 'state_data', 0),
    (497, 1, 'state_data', 0),
    (601, 1, 'code', 1744),
    (634, 1, 'code', 1744),
    (699, 1, 'code', 1744),
    (708, 1, 'code', 1744),
    (720, 1, 'code', 1744),
    (738, 1, 'code', 1744),
    (808, 2, 'steer', 0),
    (852, 2, 'pursue', 0),
    (887, 2, 'transition', 0),
    (1236, 1, 'intent_table', 0),
    (1242, 1, 'intent_table', 0),
    (1367, 1, 'state_data', 0),
    (1416, 1, 'state_data', 0),
    (1422, 1, 'state_data', 0),
    (1507, 1, 'state_data', 0),
    (1548, 1, 'init_rush_native', 0),
    (1555, 1, 'init_lane_native', 0),
    (1562, 1, 'init_man_native', 0),
    (1593, 1, 'code', 0),
    (1603, 1, 'code', 0),
    (1613, 1, 'code', 0),
    (1623, 1, 'code', 0),
    (1633, 1, 'code', 0),
    (1643, 1, 'code', 0),
    (1653, 1, 'code', 0),
    (1013, 2, 'resume_first', 0),
    (1024, 2, 'resume_later', 0),
    (1439, 2, 'resume_snap', 0),
    (1468, 2, 'resume_assignment', 0),
    (1502, 2, 'resume_command', 0),
    (1669, 2, 'resume_rush', 0),
    (1680, 2, 'resume_delay', 0),
    (1690, 2, 'resume_lane', 0),
    (1701, 2, 'resume_man', 0),
    (1715, 2, 'resume_press', 0),
    (1726, 2, 'resume_release', 0),
    (1737, 2, 'resume_exchange', 0),
)
LABELS = {
    'buffer_found': 1072,
    'carrier_exit': 868,
    'chase': 674,
    'clear_loop': 1516,
    'clear_next': 1541,
    'clear_state': 1506,
    'code_end': 1768,
    'config': 1744,
    'direction_ok': 582,
    'dispatch': 12,
    'end_spy': 893,
    'ext_originals': 1662,
    'find_record': 118,
    'finish': 904,
    'finite_loop': 446,
    'first_original': 1006,
    'found': 144,
    'fresh': 168,
    'goal_ready': 754,
    'handled': 856,
    'hash_bytes': 1348,
    'identity_ok': 189,
    'init_lane': 1554,
    'init_man': 1561,
    'init_rush': 1547,
    'initialize': 1566,
    'latch': 667,
    'later_original': 1017,
    'lookup_intent': 1028,
    'lookup_no': 1283,
    'lookup_row': 1246,
    'lookup_yes': 1287,
    'man_exchange': 1652,
    'man_exchange_original': 1730,
    'man_main': 1622,
    'man_main_original': 1694,
    'man_press': 1632,
    'man_press_original': 1705,
    'man_release': 1642,
    'man_release_original': 1719,
    'move_pursuit': 814,
    'name_bad': 1344,
    'name_done': 1346,
    'name_hash': 1294,
    'name_loop': 1324,
    'next_row': 1278,
    'nonfinite': 865,
    'occupied': 129,
    'pursuit_heading': 850,
    'requested': 224,
    'reset_assignment': 1443,
    'reset_command': 1472,
    'retained': 511,
    'retire': 968,
    'return_spy': 957,
    'rush_delay': 1602,
    'rush_delay_original': 1673,
    'rush_lane': 1612,
    'rush_lane_original': 1684,
    'rush_main': 1592,
    'rush_main_original': 1662,
    'shadow': 691,
    'snap': 1363,
    'snap_done': 1426,
    'targets_restored': 938,
    'targets_saved': 106,
    'zone_first': 0,
    'zone_later': 7,
}
