"""Generated by tools/nfl2k5_historic_teams_quick_game_assemble.py. EXPERIMENTAL / UNWITNESSED."""

CODE = bytes.fromhex(
    "526a016a00e85000000083c40cc3526a016a01e84200000083c40cc3e8fcffffff506aff6a00e82f"
    "00000083c40cc3e8fcffffff506aff6a01e81c00000083c40cc3526a00e89b01000083c408c3526a"
    "01e88f01000083c408c3555356578b742414a114f6ac0083f803740e83f807740983f8010f853801"
    "0000e8fcffffff85c00f852b0100008b1cb53cf6ac0085db0f841c01000089f1e8ee01000089c789"
    "f189fae81402000089c585ed0f84a200000039fb0f859a00000083bf28010000040f858d00000089"
    "f189fae82402000083f8ff750f837c2418007f08a11829b7008b405803442418782e8b0d1829b700"
    "3b41587d2389c5565557e88002000083c40c85c0741289f189fa89e8e81502000089fae991000000"
    "89f189fae82f02000066c704f504000000000031c9837c2418007f098b0d1829b7008b491c8b5424"
    "1c528b54241c5251e8fc00000083c40c89c2eb558b54241c528b54241c5253e8e500000083c40c89"
    "c285ed743c837c2418007c0839da773131c0eb0d39da7229a11829b7008b40584889c552565557e8"
    "eb01000083c40c5a85c0740d89f189fa89e8e87f01000089fa89f1e890010000eb2e8b54241c8b44"
    "241885f6751285c07c07e8fcffffffeb17e8fcffffffeb1085c07c07e8fcffffffeb05e8fcffffff"
    "5f5e5b5dc3555356578b742414a114f6ac0083f803740a83f807740583f801752fe8fcffffff85c0"
    "75268b1cb53cf6ac0085db741b8b542418526a0153e82700000083c40c89c289f1e812010000eb14"
    "8b54241885f67507e8fcffffffeb05e8fcffffff5f5e5b5dc35356578b7424108b1d1829b7008b5b"
    "184389f18b542418837c2414007c07e8fcffffffeb05e8fcffffff89c685c0740c83b82801000004"
    "75034b75d589f05f5e5bc353a11829b7008b50188b401c85d27e1d8b982801000083fb02740583fb"
    "04750585c9740b4905f40100004aebdf31c05bc331c085d27431f7d93b148d40f6ac0074268b8a28"
    "01000083f904740e83f902751680ba1c01000000750d8b0d1829b700837958007e0140c3538d0ccd"
    "00000000391175210fb7410485c07419668b5906663b9a18010000750c488b0d1829b7003b415872"
    "0383c8ff5bc38d0ccd0000000089114066894104668b821801000066894106c385c989d17505e9fc"
    "ffffffe9fcffffff85d2742a535689d389ce89d9e8fcffffffc6831c01000000c783280100000200"
    "00008d465a668983180100005e5bc381ecb4000000535556578b9c24c80000008b8424cc0000008b"
    "0d1829b700c1e00403415c0fb64802894c241c8b500c895424180fb708894c24148d70048d542410"
    "52ba84f9e9008d4c242489742414e8fcffffff6a006a00e8fcffffff508d8424ac000000508d5424"
    "30b9a8f9e900e8fcffffffe8fcffffff68a8f9e900ba524f5354b9a8f9e900e8fcffffff85c00f84"
    "a400000089c589d9e8fcffffff89da89e9e8fcffffff85c0746cc78328010000040000008d4c2410"
    "51babcf9e9008d4c242489742414e8fcffffff31ff8b0d1829b7003b79187d2d8b711c69c7f40100"
    "0001c68b8e0c0100008d542420e8fcffffff85c0740c8b861001000089831001000047ebc8b9a8f9"
    "e900e8fcffffffb801000000eb2ec6831c01000000c78328010000020000008b8424d000000083c0"
    "5a66898318010000b9a8f9e900e8fcffffff31c05f5e5d5b81c4b4000000c3"
)
RELOCATIONS = (
    (29, 2, 'team_mask', 0),
    (48, 2, 'team_mask', 0),
    (123, 2, 'network_session', 0),
    (293, 1, 'state', 0),
    (451, 2, 'retail_home_next', 0),
    (458, 2, 'retail_home_prev', 0),
    (469, 2, 'retail_away_next', 0),
    (476, 2, 'retail_away_prev', 0),
    (514, 2, 'network_session', 0),
    (569, 2, 'retail_home_next', 0),
    (576, 2, 'retail_away_next', 0),
    (616, 2, 'iter_next', 0),
    (623, 2, 'iter_prev', 0),
    (760, 1, 'state', 0),
    (809, 1, 'state', 0),
    (861, 2, 'team_release', 0),
    (975, 2, 'text_format', 0),
    (984, 2, 'loader_heap', 0),
    (1007, 2, 'loader_queue', 0),
    (1012, 2, 'loader_wait', 0),
    (1032, 2, 'loader_lookup', 0),
    (1049, 2, 'team_release', 0),
    (1058, 2, 'team_import', 0),
    (1095, 2, 'text_format', 0),
    (1134, 2, 'text_equal', 0),
    (1163, 2, 'loader_pop', 0),
    (1214, 2, 'loader_pop', 0),
    (839, 2, 'set_home', 0),
    (844, 2, 'set_away', 0),
)
LABELS = {
    'away_next': 14,
    'away_prev': 47,
    'away_random': 78,
    'current_entry': 756,
    'entry_out': 804,
    'entry_unknown': 801,
    'home_next': 0,
    'home_prev': 28,
    'home_random': 66,
    'import_failed': 1174,
    'label_done': 1157,
    'label_loop': 1101,
    'label_next': 1154,
    'load_entry': 895,
    'load_failed': 1208,
    'load_out': 1220,
    'publish': 832,
    'publish_away': 843,
    'random_local': 513,
    'random_out': 580,
    'random_retail': 560,
    'random_retail_away': 575,
    'random_step': 485,
    'release_done': 894,
    'release_slot': 848,
    'remember': 806,
    'resident_done': 645,
    'resident_got': 627,
    'resident_loop': 602,
    'resident_prev': 622,
    'resident_step': 585,
    'slot_usable': 700,
    'spare_done': 698,
    'spare_loop': 663,
    'spare_match': 683,
    'spare_next': 688,
    'spare_none': 696,
    'spare_slot': 651,
    'step': 90,
    'step_enter': 393,
    'step_have_entry': 228,
    'step_leave': 280,
    'step_leave_target': 317,
    'step_local': 122,
    'step_out': 480,
    'step_publish': 425,
    'step_resident': 340,
    'step_resident_back': 380,
    'step_retail': 434,
    'step_retail_away': 464,
    'step_retail_away_prev': 475,
    'step_retail_home_prev': 457,
    'usable_done': 755,
    'usable_list': 742,
}
