"""Generated by tools/nfl2k5_rules_assemble.py. EXPERIMENTAL / UNWITNESSED."""

CODE = bytes.fromhex(
    "9c515250c7050000000000000000833dc402e60001755d833db402e600007554e8fcffffff85c075"
    "4bb9a0fce500e8fcffffff83f8ff74f131d2b911000000f7f183fa0f732e8935000000008b368935"
    "8826b70083358891c30001f7df83c70383ff017507e8fcffffffeb05e8fcffffff890424585a599d"
    "89c3a18c91c300e9fcffffff9c833d00000000007408c7442410000000009de9fcffffff50833dc4"
    "02e600037515a1000000003d20fce50074073d60fce50075028b0858e9fcffffff8b0d8c91c3008b"
    "158891c300833d0000000000740383f20131c039d10f94c0c3"
)
RELOCATIONS = (
    (6, 1, 'state', 0),
    (33, 2, 'human_query', 0),
    (47, 2, 'random_word', 0),
    (72, 1, 'state', 0),
    (102, 2, 'home_name', 0),
    (109, 2, 'away_name', 0),
    (135, 1, 'state', 0),
    (146, 1, 'notice', 0),
    (167, 1, 'state', 0),
    (207, 1, 'state', 0),
    (128, 2, 'choose_tail', 0),
    (152, 2, 'native_menu', 0),
    (189, 2, 'native_possession', 0),
)
LABELS = {
    'away': 108,
    'choose': 0,
    'draw': 41,
    'half_deferred': 185,
    'half_original': 187,
    'halftime': 156,
    'menu': 132,
    'menu_original': 150,
    'name_ready': 113,
    'original': 116,
    'result_original': 217,
    'winner_result': 193,
}
