"""Generated by tools/nfl2k5_era_rules_assemble.py. EXPERIMENTAL / UNWITNESSED."""

CODE = bytes.fromhex(
    "31c0833d80ffe500087515a15818bf0083f8327309c1e0050500000000c331c0c3833dc402e60005"
    "7c450fb6481783f901742a83f90275198b1528fce5008b128b0d68fce5002b117902f7da83fa0673"
    "21e8fcffffff0f94c00fb6c0c38b0d28fce5008b1568fce5008b093b0a750331c0c3b801000000c3"
    "8b4010a3b002e6008b0d8c02e60085c97403894110833d0000000000752dc7050000000001000000"
    "c605a802e600008b0d8402e60085c97412b00481f920fce500740200c00805a802e600c38b0d28fc"
    "e5008b1568fce5008b093b0a749cf6401604749380781702728d8b0d8002e60085c974838b51088b"
    "128b098b49083b110f8c74ffffffe96cffffffc7050800000000000000f64016207458833db402e6"
    "0002754f85d2744b8b4a388b49088b490c8b5218d94238d84904d81d6c010000dfe0f6c4057a2cd9"
    "4238d84904d81d70010000dfe0f6c4417519d94104d80d6c010000d91d04000000c7050800000001"
    "000000c300e00ec500e08ec5"
)
RELOCATIONS = (
    (25, 1, 'profiles', 0),
    (82, 2, 'native_ot_check', 0),
    (143, 1, 'state', 0),
    (152, 1, 'state', 0),
    (261, 1, 'state', 0),
    (308, 1, 'code', 0),
    (327, 1, 'code', 0),
    (343, 1, 'code', 0),
    (349, 1, 'state', 0),
    (355, 1, 'state', 0),
)
LABELS = {
    'both': 81,
    'clock_done': 195,
    'clock_no_object': 141,
    'clock_pending': 189,
    'fair_25': 364,
    'fair_catch': 259,
    'fair_done': 363,
    'fair_goal': 368,
    'magnitude': 76,
    'not_over': 111,
    'ot_check': 33,
    'ot_clock': 120,
    'ot_expiry': 196,
    'over': 114,
    'profile': 0,
    'profile_done': 32,
    'profile_none': 30,
    'sudden_death': 93,
}
