"""Generated by tools/nfl2k5_calendar_engine_assemble.py. EXPERIMENTAL / UNWITNESSED."""

CODE = bytes.fromhex(
    "51a903000000751b31d2b964000000f7f185d27507a9030000007507b80100000059c331c059c353"
    "56578d9094f8ffff81fa6301000077388b3495000000000fb6194b83fb0b7728e8fcffffff6bc01a"
    "8db8000000000fb7045f0fb7545f0229c201c60fb641014839d0730401f0eb05b8000000805f5e5b"
    "c35183c1030fb6410283f8627607056c070000eb0505d0070000e8fcffffff3d000000807405056d"
    "01000059c35183c103e8fcffffff59c3510fb6410205d0070000e8fcffffff3d00000080741483c0"
    "0599b907000000f7f989d085c0790383c00759c353565783f8007c603b05900500007d5889c6bb64"
    "0000003b349d040000007c0343ebf42b349d000000008d836c070000e8fcffffff6bc01a8db80000"
    "000031d20fb744570239c67c0342ebf40fb7045729c64689f04283eb648811884101885902b80100"
    "0000eb05b8000000805f5e5bc3f7da7020520fb6410205d0070000e8fcffffff5a3d000000807409"
    "01d07005e96bffffffb800000080c351a1b876e5000500000000680b01000089e1e8fcffffff83c4"
    "043d00000080741e5389c383c00599b907000000f7f9b80a00000029d031d2f7f18d4413c85b59c3"
    "52e8fcffffff5a3d0000008074ab01d070a7e90dffffff5152b96400000031d2f7f1a1b876e50005"
    "000000005029d031d2f7f15829d05a59c3a1b876e50005fcffffffc3a1b876e5000530f8ffff3dff"
    "0000000f8760ffffff884102c35183c103e8fcffffff59c351e8fcffffff5983f8020f8480feffff"
    "e9fcffffff"
)
RELOCATIONS = (
    (59, 1, 'year_starts', 0),
    (73, 2, 'code', 0),
    (82, 1, 'month_starts', 0),
    (147, 2, 'code', 39),
    (170, 2, 'code', 176),
    (187, 2, 'code', 39),
    (230, 1, 'year_starts', 0),
    (246, 1, 'year_starts', 0),
    (258, 1, 'year_starts', 0),
    (269, 2, 'code', 0),
    (278, 1, 'month_starts', 0),
    (348, 2, 'code', 39),
    (382, 1, 'base_year', 0),
    (394, 2, 'code', 39),
    (442, 2, 'code', 375),
    (480, 1, 'base_year', 0),
    (503, 1, 'base_year', 0),
    (514, 1, 'base_year', 0),
    (538, 2, 'code', 544),
    (546, 2, 'mode_getter', 0),
    (561, 2, 'retail_weekday', 0),
)
LABELS = {
    'add_days': 337,
    'arithmetic_bad': 369,
    'birth_year': 463,
    'display_weekday': 544,
    'grid_weekday': 533,
    'inverse': 220,
    'inverse_bad': 324,
    'inverse_done': 329,
    'inverse_month': 284,
    'inverse_months': 255,
    'inverse_store': 296,
    'inverse_year': 243,
    'leap': 0,
    'leap_no': 35,
    'leap_yes': 28,
    'legacy_2000': 141,
    'legacy_convert': 146,
    'legacy_done': 163,
    'legacy_ordinal': 121,
    'opening_day': 375,
    'opening_done': 438,
    'ordinal': 39,
    'ordinal_bad': 112,
    'ordinal_done': 117,
    'projection_year': 497,
    'redate': 440,
    'regular_anchor': 508,
    'sub_days': 333,
    'weekday': 176,
    'weekday_done': 218,
    'weekday_record': 165,
}
