"""Generated by tools/nfl2k5_abilities_runtime_assemble.py. EXPERIMENTAL / UNWITNESSED."""

CODE = bytes.fromhex(
    "31c085c9743983f9ff7434833d00000000ff741f833da076e500027516833da476e50008750da100"
    "0000003b05b476e500740a0fb7415225e01e0000c331c0c331f631d28d430183f801763b8b73108d"
    "460183f801762c8b530c8d420183f8017623833db802e6000e751ca100fce5004083f80176114839"
    "18750c837b1c017506f9c331f631d2f8c38b0283f8ff741a83f80377136bc02c8b8060b9a90083f8"
    "08740783f80a7402f8c3f9c331ff83f95c741683f95d741183e91883f91377080fb73c4d00000000"
    "c3bf80000000c385f6741583a690000000fcc7464400000000c74648000080bf85d27404836218fb"
    "c3e84affffff733e8b4b3ce800ffffff89c5a940000000750525fff7ffffa9801e000074218b8690"
    "00000083e00383f80175118b0ee882ffffff85ff740821fd39fd7502f9c3e894fffffff8c3e8afff"
    "ffffe8f9feffff732de83bffffff73268b4a1ce854ffffff85ff741a8b4b3ce89cfeffff21f839f8"
    "740cc7421c00000000e859ffffffc351ff742408e8fcffffff599c6083ec0cd91c24c7442404a470"
    "7d3fe869feffffa92000000074270fb6413683e86483f81b771b83c06489442408db442408d80d04"
    "000000d9542404d80c24d91c248b042485c078133d0000807f730c3b442404760b8b442404eb0231"
    "c0890424d9042483c40c619dc20400e8fcffffff9c60e842ffffff619dc39c6089cbe836ffffff61"
    "9d8b410c8b781c89fae9fcffffff9c6089cbe821feffff7377e863feffff73708b6c24148b0e83f9"
    "5d77093b2c8df067ad00742b8b4a1c83f95d77093b2c8df067ad00741abfec030000b9070000003b"
    "2f740783c708e2f7eb368b7f04eb05e840feffff85ff74288b4b3ce888fdffff21f839f8741ac744"
    "2414ecf45000c70600000000c7421c00000000e837feffff619d53565789cfe9fcffffff9c6089cb"
    "e844feffff730c619da180ffe500e9fcffffff619dc39c6089cbe82afeffff73f2619d8b41108b88"
    "90000000e9fcffffff9c6089cbe85efdffff73588b442424bf00000000b90f0000003b07740783c7"
    "08e2f7eb3f8b6f0485ed74388b0e83f95d77318b048df067ad003968047525e890fdffff85ff741c"
    "8b4b3ce8d8fcffff21f839f8750e619d568b7110d94644e9fcffffffe88efdffff619dc3ffffffff"
    "0ad7233c001000104008000200028000800000008000800080000004c000c000c000c000c000c000"
    "c000c000cbd218000000000081df18000000000043771e0000000000a77b1e0000000000d0192300"
    "00000000a008290080082900651d290000000000d1bb2d00c0bb2d0008c82d00f0c72d0098cf2d00"
    "70cf2d00fc6d3000e06d30001785300000000000c7d23000a0d23000aced30000000000042793100"
    "00000000480153000010000008cb510040080000f80053008002000064105300000400005c0f5300"
    "c000000034015300800000002001530080020000"
)
RELOCATIONS = (
    (13, 1, 'code', 836),
    (39, 1, 'code', 836),
    (196, 1, 'code', 844),
    (381, 2, 'retail_attribute', 0),
    (439, 1, 'code', 836),
    (496, 2, 'retail_decode', 0),
    (590, 1, 'code', 0),
    (745, 1, 'code', 884),
    (530, 2, 'retail_account', 0),
    (672, 2, 'retail_initialize_tail', 0),
    (695, 2, 'retail_generate_tail', 0),
    (725, 2, 'retail_ai_tail', 0),
    (824, 2, 'retail_consume_tail', 0),
)
LABELS = {
    'ai_ready': 702,
    'carrier': 64,
    'carrier_bad_state': 131,
    'carrier_bad_steer': 133,
    'carrier_no': 135,
    'clear_charge': 207,
    'clear_done': 240,
    'clear_request': 232,
    'code_end': 1060,
    'config': 836,
    'consume': 729,
    'consume_denied': 828,
    'consume_find': 754,
    'consume_found': 765,
    'consumers': 884,
    'decode': 495,
    'dispatch': 510,
    'effective': 0,
    'effective_done': 63,
    'effective_read': 51,
    'effective_zero': 61,
    'families': 1004,
    'filter': 317,
    'filter_done': 374,
    'generate': 676,
    'generate_denied': 699,
    'initialize': 534,
    'initialize_check': 620,
    'initialize_done': 664,
    'initialize_family': 589,
    'initialize_family_found': 610,
    'initialize_find': 599,
    'initialize_mask': 615,
    'initialize_steer': 572,
    'instructions_end': 836,
    'maintain': 241,
    'maintain_any': 270,
    'maintain_clear': 310,
    'maintain_yes': 308,
    'mask_done': 200,
    'mask_juke': 201,
    'move_mask': 172,
    'move_masks': 844,
    'running': 137,
    'running_no': 168,
    'running_yes': 170,
    'speed': 375,
    'speed_bound': 453,
    'speed_load': 484,
    'speed_store': 481,
    'speed_zero': 479,
}
