"""Generated by tools/nfl2k5_weekly_prep_assemble.py. EXPERIMENTAL / UNWITNESSED."""

CODE = bytes.fromhex(
    "31c983e80483f8020f96c1e9fcffffffe8fcffffff85c07518833da076e50002750f85ed7406b800"
    "000000c3b801000000c389e9e9fcffffffe814000000e9fcffffffe80a000000a18401e600e9fcff"
    "ffff9c605589e581ec1002000083e4f00fae0424fc833da076e50002756f833d1c01e60001756683"
    "3dac76e50020755da1a476e50083e80783f8027750a1b476e50083f81673468b15bc76e50083fa11"
    "733b6bc01101d08d34c5407ce5000fb60683e00783f80373240fb64e010fb6560283f920731783fa"
    "20731239d1740ee8130000000fb64e02e80a0000000fae0c2489ec5d619dc36089cb833c9d601ee5"
    "00010f8730010000e8fcffffff85c00f842301000089c50fb6851c0100004883f8400f8710010000"
    "31ff8b44bd0085c00f8402010000807835100f87f8000000470fb6851c01000039c772de69f3d007"
    "000081c66024e400833c9d5c77e50000740fb80000000085c00f84c9000000eb46b80000000085c0"
    "0f84ba00000089f7b9f4010000b800000001f3ab89f7b85d000082b905000000ab83c003ab83c003"
    "ab83e8060500000010e2edb8670000d1ab0500000010ab31ff31d28b04be89c181e1ff010000741f"
    "81f9ad0000007368c1e81889c183e10f4983f907775a83e07083f8707452424781fff401000072cb"
    "85d2744469d3c300000081c2601fe50031ff8b44bd008a484c880a8a4839884a018a483b884a0283"
    "c203470fb6851c01000039c772dcc7049d601ee5000200000089d9e8fcffffff61c351526083f920"
    "734f833da076e500027546833c8d5c77e500007407b800000000eb05b80000000085c0742c69f9d0"
    "07000081c76024e400b9f4010000f707ff0100007406810f0000008083c704e2edc7442420000000"
    "00615a59e9fcffffff"
)
RELOCATIONS = (
    (17, 2, 'native_human', 0),
    (39, 1, 'cpu_option', 0),
    (249, 2, 'native_team', 0),
    (339, 1, 'remember_option', 0),
    (354, 1, 'cpu_option', 0),
    (548, 2, 'native_apply', 0),
    (582, 1, 'remember_option', 0),
    (589, 1, 'cpu_option', 0),
    (12, 2, 'db_continue', 0),
    (53, 2, 'native_team_index', 0),
    (63, 2, 'native_sim_value', 0),
    (78, 2, 'play_continue', 0),
    (645, 2, 'native_clear', 0),
)
LABELS = {
    'before_play': 67,
    'before_sim': 57,
    'check_plan': 423,
    'check_roster': 282,
    'check_row': 427,
    'clear_cpu': 588,
    'clear_enabled': 593,
    'clear_retail': 641,
    'cpu_days': 392,
    'cpu_plan': 353,
    'current_done': 221,
    'db_group': 0,
    'gate_done': 49,
    'gate_yes': 44,
    'mark_next': 628,
    'mark_repeat': 614,
    'next_row': 471,
    'prepare_current': 82,
    'prepare_team': 231,
    'remember_clear': 554,
    'snapshot': 498,
    'team_done': 552,
    'team_gate': 16,
    'team_seed': 50,
}
