"""Generated by tools/nfl2k5_rules_assemble.py. EXPERIMENTAL / UNWITNESSED."""

CODE = bytes.fromhex(
    "e814000000a1b402e600e9fcffffffe805000000e9fcffffff9c60833d183aa800030f85a4000000"
    "833dc402e600040f8597000000833db402e600040f858a000000a1b802e60083f812740583f80c75"
    "7b8b358002e60081fe20fce500740f81fe60fce5007565bf20fce500eb05bf60fce500393d8402e6"
    "0075518b76088b7f0885f6744785ff74438b068b173dff000000773881faff000000773029d03b05"
    "000000007c268b358c02e60085f6741cf646180c75168b461085c0740f3b05040000007707c74610"
    "00000000619dc3"
)
RELOCATIONS = (
    (160, 1, 'options', 0),
    (191, 1, 'options', 0),
    (11, 2, 'huddle_tail', 0),
    (21, 2, 'native_lineup', 0),
)
LABELS = {
    'dead': 81,
    'dead_ball': 15,
    'decide': 25,
    'done': 204,
    'home': 110,
    'huddle': 0,
    'teams': 115,
}
