"""Generated by tools/nfl2k5_franchise_autosave_assemble.py. EXPERIMENTAL / UNWITNESSED."""

CODE = bytes.fromhex(
    "83350000000001c7050400000000000000c7051400000000000000b801000000c3a100000000c3a1"
    "0000000083e0018b048594d94e00c3e8fcffffff9c60e812000000619dc3e8fcffffff9c60e80300"
    "0000619dc3833da076e50002751d833d00000000017514c7050400000001000000c7051400000000"
    "000000c3e8fcffffff9c6085c07519833d080000000175108b0da4bdbd00ba80010000e8fcffffff"
    "619dc351e8fcffffff9c60833da076e50002750c8b542424a100000000894264619d8d642404c39c"
    "6083bdd4c1bd0009751b31c0833de4ffe500010f94c0a300000000c705e4ffe50000000000619de9"
    "fcffffffc7050400000000000000c7050c00000000000000c705140000000000000083ec14a1b8bd"
    "bd00e9fcffffff9c6083bdd4c1bd0009750b8b8dd0c1bd00e857000000c7050400000000000000c7"
    "051400000000000000619de9fcffffffc7050400000000000000c7050c00000000000000c7051400"
    "00000000000083f902750ac705e4ffe5000000000089c885c00f85fcffffffe9fcffffffc7050c00"
    "00000000000085c9745166833900744b31d266833c510074074283fa1172f3c389cebf2000000042"
    "89d1fc66f3a5a1b8bdbd0083f80973236bc0348b15bcbdbd0085d274168b040285c0740fa3100000"
    "00c7050c00000001000000c3833d08000000017508b802000000c21800e9fcffffff9c60837d0809"
    "75188b4d0ce87affffffc7050400000000000000ff0518000000619d833d080000000175d031c0c2"
    "180051e8fcffffff9c608b6c2424833d08000000000f85b1010000833d00000000010f85a0000000"
    "833da076e500020f85930000008b850001000083f8207379817cc50090215200756f833d103aa800"
    "007566833d0824aa0000755d8b154021aa0085d274538b42043d0000807f73493b050024aa007241"
    "833db0bdbd00017538a1a0bdbd0085c0740a83f807740583f8087525833d04000000000f842b0100"
    "00833d1400000000752ac7051400000001000000e913010000c7051400000000000000e904010000"
    "c7050400000000000000ebe5c7050400000000000000c7051400000000000000c705080000000100"
    "0000833d0c000000010f85b7000000ff35a4bdbd00892da4bdbd00833dbcbdbd00000f8485000000"
    "e8fcffffff31ff8b35bcbdbd0085f67474a1100000003906740b83c6344783ff0972eeeb6057e8fc"
    "ffffff837e080074548b5e1c81fb00010000774931ff39df73436bc71883b8d4c1bd000975258b90"
    "d0c1bd0085d2741b31c9668b044d20000000663b044a750b6685c074094183f91172e747ebc8893d"
    "1c00000089f9e8fcffffffeb0c89e9ba00010000e8fcffffffe8fcffffff8f05a4bdbd00eb0c89e9"
    "ba80000000e8fcffffffc7050800000000000000619d8d642404c3519c6089cd833d080000000075"
    "eb833d00000000010f85dafeffff833da076e500020f85cdfeffff85ed0f84b6feffff85d20f84ae"
    "feffff8b850001000083f8200f839ffeffff3954c5000f8595feffff833d103aa800000f8588feff"
    "ff833db0bdbd00010f857bfeffffa1a0bdbd0085c00f8449feffff83f8070f8440feffff83f8080f"
    "8437feffffe957feffff"
)
RELOCATIONS = (
    (2, 1, 'state', 0),
    (9, 1, 'state', 0),
    (19, 1, 'state', 0),
    (34, 1, 'state', 0),
    (40, 1, 'state', 0),
    (56, 2, 'mark_played_native', 0),
    (71, 2, 'mark_sim_native', 0),
    (96, 1, 'state', 0),
    (105, 1, 'state', 0),
    (115, 1, 'state', 0),
    (125, 2, 'allocate_native', 0),
    (137, 1, 'state', 0),
    (151, 1, 'strings', 0),
    (156, 2, 'notice_native', 0),
    (165, 2, 'copy_settings_native', 0),
    (185, 1, 'state', 0),
    (223, 1, 'state', 0),
    (246, 1, 'state', 0),
    (256, 1, 'state', 0),
    (266, 1, 'state', 0),
    (311, 1, 'state', 0),
    (321, 1, 'state', 0),
    (338, 1, 'state', 0),
    (348, 1, 'state', 0),
    (358, 1, 'state', 0),
    (398, 1, 'state', 0),
    (435, 1, 'state', 0),
    (477, 1, 'state', 0),
    (483, 1, 'state', 0),
    (494, 1, 'state', 0),
    (532, 1, 'state', 0),
    (542, 1, 'state', 0),
    (550, 1, 'state', 0),
    (564, 2, 'desk_native', 0),
    (576, 1, 'state', 0),
    (589, 1, 'state', 0),
    (710, 1, 'state', 0),
    (723, 1, 'state', 0),
    (732, 1, 'state', 0),
    (747, 1, 'state', 0),
    (762, 1, 'state', 0),
    (774, 1, 'state', 0),
    (784, 1, 'state', 0),
    (794, 1, 'state', 0),
    (804, 1, 'state', 0),
    (841, 2, 'init_devices_native', 0),
    (858, 1, 'state', 0),
    (879, 2, 'select_device_native', 0),
    (934, 1, 'state', 0),
    (960, 1, 'state', 0),
    (967, 2, 'save_native', 0),
    (976, 1, 'strings', 0),
    (981, 2, 'notice_native', 0),
    (986, 2, 'close_devices_native', 0),
    (1001, 1, 'strings', 0),
    (1006, 2, 'notice_native', 0),
    (1012, 1, 'state', 0),
    (1034, 1, 'state', 0),
    (1043, 1, 'state', 0),
    (240, 2, 'camera_size_native', 0),
    (283, 2, 'load_continue', 0),
    (332, 2, 'league_native', 0),
    (387, 2, 'mode_nonzero', 0),
    (392, 2, 'mode_zero', 0),
    (510, 2, 'dialog_native', 0),
)
LABELS = {
    'allocate': 124,
    'allocate_done': 160,
    'attempt_done': 1010,
    'career_complete': 1027,
    'close_device': 985,
    'desk': 562,
    'desk_attempt': 772,
    'desk_cancel': 760,
    'desk_done': 1020,
    'desk_state_ok': 708,
    'desk_wait': 745,
    'device_found': 877,
    'device_loop': 857,
    'getter': 33,
    'load_begin': 244,
    'load_settings': 199,
    'load_settings_done': 237,
    'load_slot': 287,
    'load_slot_done': 309,
    'mark': 85,
    'mark_done': 123,
    'missing_device': 973,
    'missing_slot': 998,
    'mode_change': 336,
    'mode_replay': 381,
    'name_loop': 930,
    'next_slot': 955,
    'ordinary_dialog': 509,
    'overwrite_dialog': 492,
    'played': 55,
    'remember': 396,
    'remember_copy': 432,
    'remember_done': 491,
    'remember_scan': 418,
    'save_slot': 958,
    'serialize': 163,
    'serialize_done': 192,
    'simulated': 70,
    'slot_loop': 902,
    'success_dialog': 514,
    'success_not_franchise': 546,
    'toggle': 0,
    'value_text': 39,
}
