"""Generated by tools/nfl2k5_abilities_runtime_assemble.py. EXPERIMENTAL / UNWITNESSED."""

CODE = bytes.fromhex(
    "8d4101d1e8745fa10000000083f8ff741a833da076e500027511833da476e5000875083b05b476e5"
    "00743b0fb741526625e01e53520fb65153c1ea068a923605000089c385db740ad1eb73f8feca79f4"
    "31c00fb65153d1ea7309c1ea050a823a0500005a5bc331c0c3e892ffffff0b0508050000c3a10805"
    "00006625c01e663dc01ec3cc31f631d28d430183f801763b8b73108d460183f801762c8b530c8d42"
    "0183f8017623833db802e6000e751ca100fce5004083f8017611483918750c837b1c017506f9c331"
    "f631d2f8c38b0283f8ff741a83f80377136bc02c8b8060b9a90083f808740783f80a7402f8c3f9c3"
    "31ff83f95c741683f95d741183e91883f91377080fb73c4d00000000c3bf80000000c385f6741583"
    "a690000000fcc7464400000000c74648000080bf85d27404836218fbc3e83bffffff7443e843ffff"
    "ff733e8b4b3ce81effffff89c5a940000000750525fff7ffffa9801e000074218b869000000083e0"
    "0383f80175118b0ee87bffffff85ff740821fd39fd7502f9c3e88dfffffff8c3e8a8ffffffe8f2fe"
    "ffff732de834ffffff73268b4a1ce84dffffff85ff741a8b4b3ce8bafeffff21f839f8740cc7421c"
    "00000000e852ffffffc351ff742408e8fcffffff599c6083ec0cd91c24c7442404a4707d3fe887fe"
    "ffffa92000000074270fb6413683e86483f81b771b83c06489442408db442408d80d04000000d954"
    "2404d80c24d91c248b042485c078133d0000807f730c3b442404760b8b442404eb0231c0890424d9"
    "042483c40c619dc20400e8fcffffff9c60e842ffffff619dc39c6089cbe836ffffff619d8b410c8b"
    "781c89fae9fcffffff9c6089cbe81afeffff7377e85cfeffff73708b6c24148b0e83f95d77093b2c"
    "8df067ad00742b8b4a1c83f95d77093b2c8df067ad00741abfd0040000b9070000003b2f740783c7"
    "08e2f7eb368b7f04eb05e839feffff85ff74288b4b3ce8a6fdffff21f839f8741ac7442414ecf450"
    "00c70600000000c7421c00000000e830feffff619d53565789cfe9fcffffff9c6089cbe83dfeffff"
    "730c619da180ffe500e9fcffffff619dc39c6089cbe823feffff73f2619d8b41108b8890000000e9"
    "fcffffff9c6089cbe848fdffff7451e850fdffff73588b442424bf00000000b90f0000003b077407"
    "83c708e2f7eb3f8b6f0485ed74388b0e83f95d77318b048df067ad003968047525e882fdffff85ff"
    "741c8b4b3ce8effcffff21f839f8750e619d568b7110d94644e9fcffffffe880fdffff619dc35251"
    "ff74240ce8790000009c608b4c24248b542428833db802e6000e755d83fa12775889d6e840fcffff"
    "668504751005000074470fb64153c1e806743e83ec0889442404d91c248b042485c07e273d000080"
    "3f7320db442404d80d0c050000d80424d91c24813c240000803f7607c704240000803fd9042483c4"
    "08619d8d642408c2040083ec088b4130e9fcffffffccccccffffffff0ad7233c0010001040080002"
    "00028000800000008000800080000004c000c000c000c000c000c000c000c000cbd2180000000000"
    "81df18000000000043771e0000000000a77b1e0000000000d019230000000000a008290080082900"
    "651d290000000000d1bb2d00c0bb2d0008c82d00f0c72d0098cf2d0070cf2d00fc6d3000e06d3000"
    "1785300000000000c7d23000a0d23000aced30000000000042793100000000004801530000100000"
    "08cb510040080000f80053008002000064105300000400005c0f5300c00000003401530080000000"
    "2001530080020000000000000ad7a33c000080000010000800000000000000000000000000000000"
    "00040000000000000000000000020702040700000000"
)
RELOCATIONS = (
    (8, 1, 'code', 1064),
    (62, 1, 'code', 0),
    (95, 1, 'code', 0),
    (112, 1, 'code', 0),
    (118, 1, 'code', 0),
    (264, 1, 'code', 1072),
    (456, 2, 'retail_attribute', 0),
    (514, 1, 'code', 1064),
    (571, 2, 'retail_decode', 0),
    (665, 1, 'code', 0),
    (827, 1, 'code', 1112),
    (964, 1, 'code', 0),
    (1009, 1, 'code', 0),
    (605, 2, 'retail_account', 0),
    (747, 2, 'retail_initialize_tail', 0),
    (770, 2, 'retail_generate_tail', 0),
    (800, 2, 'retail_ai_tail', 0),
    (906, 2, 'retail_consume_tail', 0),
    (1057, 2, 'retail_attribute_tail', 0),
)
LABELS = {
    'ai_ready': 777,
    'attribute': 918,
    'attribute_body': 1050,
    'attribute_done': 1041,
    'attribute_load': 1035,
    'carrier': 132,
    'carrier_bad_state': 199,
    'carrier_bad_steer': 201,
    'carrier_no': 203,
    'clear_charge': 275,
    'clear_done': 308,
    'clear_request': 300,
    'code_end': 1342,
    'config': 1064,
    'consume': 804,
    'consume_allowed': 896,
    'consume_denied': 910,
    'consume_find': 836,
    'consume_found': 847,
    'consumers': 1112,
    'decode': 570,
    'dispatch': 585,
    'effect_masks': 1296,
    'effect_step': 1292,
    'effective': 0,
    'effective_read': 43,
    'effective_zero': 102,
    'families': 1232,
    'filter': 392,
    'filter_done': 449,
    'generate': 751,
    'generate_denied': 774,
    'grant_done': 99,
    'initialize': 609,
    'initialize_check': 695,
    'initialize_done': 739,
    'initialize_family': 664,
    'initialize_family_found': 685,
    'initialize_find': 674,
    'initialize_mask': 690,
    'initialize_steer': 647,
    'instructions_end': 1061,
    'maintain': 309,
    'maintain_any': 345,
    'maintain_carrier': 316,
    'maintain_clear': 385,
    'maintain_head': 309,
    'maintain_state': 364,
    'maintain_test': 345,
    'maintain_yes': 383,
    'mask_done': 268,
    'mask_juke': 269,
    'move_mask': 240,
    'move_masks': 1072,
    'permissions': 105,
    'running': 205,
    'running_no': 236,
    'running_yes': 238,
    'speed': 450,
    'speed_bound': 528,
    'speed_load': 559,
    'speed_store': 556,
    'speed_zero': 554,
    'tier_count': 68,
    'tier_done': 82,
    'tier_grants': 1338,
    'tier_limits': 1334,
    'unlocked_mask': 1288,
    'unlocked_moves': 117,
}
