"""Generated by tools/nfl2k5_rules_assemble.py. EXPERIMENTAL / UNWITNESSED."""

CODE = bytes.fromhex(
    "9c50833db802e6000e752a833db402e6000475218b470c85c0741a8338ff75158b473c85c0740e80"
    "7835007508d80d00000000eb06d80d6c694e00589dc3"
)
RELOCATIONS = (
    (47, 1, 'factor', 0),
)
LABELS = {
    'done': 59,
    'retail': 53,
    'threshold': 0,
}
