"""Generated by tools/nfl2k5_espn25_more_moments_assemble.py. EXPERIMENTAL / UNWITNESSED."""

CODE = bytes.fromhex(
    "833d5818bf001972435657558b6c241031ff81ff00000000732f89fec1e60481c6000000000fb706"
    "39c3750e8b560c89e9e8fcffffff85c0750347ebd58d87000001005d5f5ec204005d5f5e8b0d1829"
    "b700e9fcffffff81f9000001007234568b351829b700ff7658ff765cc7465800000000c7465c0000"
    "000081e900000100e8fcffffff8b351829b7008f465c8f46585ec3e9fcffffff8b0d5818bf00b801"
    "000000d3e083f920730b0905cc18bf00e9fcffffff090500000000e9fcffffffa15818bf0083e819"
    "72143d00000000730d8d0485000000008338007401c3e9fcffffff"
)
RELOCATIONS = (
    (20, 1, 'team_count', 0),
    (33, 1, 'table', 0),
    (50, 2, 'name_equal', 0),
    (111, 1, 'team_count', 0),
    (118, 1, 'table', 0),
    (129, 2, 'historic_load', 0),
    (183, 1, 'session', 0),
    (203, 1, 'venue_count', 0),
    (212, 1, 'venue_table', 0),
    (83, 2, 'search_resume', 0),
    (148, 2, 'historic_load', 0),
    (177, 2, 'after_set', 0),
    (188, 2, 'after_set', 0),
    (223, 2, 'stadium_get', 0),
)
LABELS = {
    'load_retail': 147,
    'load_team': 87,
    'mark_high': 181,
    'mark_set': 152,
    'search': 0,
    'search_hit': 61,
    'search_next': 18,
    'search_plain': 76,
    'search_retail': 73,
    'search_skip': 58,
    'venue_name': 192,
    'venue_retail': 222,
}

DISPLAY_CODE = bytes.fromhex(
    "0fb68900000000e9fcffffff890d000000000fb6b90000000089f9e9fcffffff8b1500000000c3"
)
DISPLAY_RELOCATIONS = (
    (3, 1, 'display_map', 0),
    (14, 1, 'display_selected', 0),
    (21, 1, 'display_map', 0),
    (34, 1, 'display_selected', 0),
    (8, 2, 'record_get', 0),
    (28, 2, 'record_get', 0),
)
DISPLAY_LABELS = {
    'display_caption': 0,
    'display_return': 32,
    'display_select': 12,
}
