"""Generated by tools/nfl2k5_accelerated_clock_assemble.py. EXPERIMENTAL / UNWITNESSED."""

CODE = bytes.fromhex(
    "e8fcffffff9c833d00000000010f856801000060833d00000000000f8559010000c7050000000001"
    "000000833db802e6000c0f8542010000a1b402e60083e80383f8010f87310100008b3dc402e60085"
    "ff0f8e230100008b1d9402e6008b358c02e60085db0f840f01000085f60f8407010000f643180c0f"
    "85fd0000008b43103d000020420f87ef0000008b46103d00401c460f87e10000008b150400000083"
    "fa050f82d200000083fa190f87c900000083ec440f1104240f114c24100f115424200f115c24300f"
    "ae5c2440f30f2adaf30f1043100f2ec30f8681000000f30f5cc3f30f104e100f28d183ff01740583"
    "ff037514a1b002e6003d00401c46775ff30f5815b002e600b878000000f30f2ac80f2ed17649f646"
    "180e753e833db402e600047535a18002e60085c074318b400c85c0742a8b400c85c07423f74004c0"
    "0140007515f30f104e10f30f5cc80f57d2f30f5fcaf30f114e10f30f115b100fae5424400f100424"
    "0f104c24100f105424200f105c243083c444619dc39c833d00000000017514817c240415700b0075"
    "0ac70500000000000000009d8b0d9402e600e9fcffffff9c833d0000000001750ac7050000000001"
    "0000009da1b002e600e9fcffffff9c833d0000000001750ac70500000000010000009d538b1d8402"
    "e600e9fcffffff"
)
RELOCATIONS = (
    (1, 2, 'native_restart', 0),
    (8, 1, 'options', 0),
    (22, 1, 'latch', 0),
    (35, 1, 'latch', 0),
    (155, 1, 'options', 0),
    (384, 1, 'options', 0),
    (403, 1, 'latch', 0),
    (426, 1, 'options', 0),
    (435, 1, 'latch', 0),
    (457, 1, 'options', 0),
    (466, 1, 'latch', 0),
    (419, 2, 'stop_tail', 0),
    (450, 2, 'period_tail', 0),
    (483, 2, 'no_huddle_tail', 0),
)
LABELS = {
    'code_end': 487,
    'complete': 0,
    'complete_flags': 379,
    'complete_regs': 378,
    'complete_simd': 351,
    'half_add': 244,
    'half_ready': 264,
    'no_huddle': 454,
    'no_huddle_original': 474,
    'period_original': 443,
    'period_reset': 423,
    'play_only': 346,
    'stop_clock': 381,
    'stop_original': 411,
}
