#!/usr/bin/env python3
"""Classify APF's first XenonRecomp translation probe without claiming a port."""

from __future__ import annotations

import argparse
from collections import Counter
import hashlib
import json
from pathlib import Path
import re
import subprocess
import tomllib


SCHEMA = "apf2k8_static_recomp_probe/v1"
EXPECTED_XEX_SHA256 = (
    "981a57143b0a665b2220f72366e1368c5374b91c77a22d93945439d51a2cd28f"
)
EXPECTED_VENDOR_COMMIT = "ddd128bcca99fe8bfbb99bea583c972351fa6ace"
UNRECOGNIZED = re.compile(
    r"^Unrecognized instruction at (0x[0-9A-Fa-f]+): ([A-Za-z0-9_.]+)$"
)
SWITCH_ERROR = re.compile(
    r"^ERROR: Switch case at ([0-9A-Fa-f]+) is trying to jump outside "
    r"function: ([0-9A-Fa-f]+)$"
)
MISSING_SWITCH = re.compile(
    r"^Found a switch jump table at ([0-9A-Fa-f]+) with no switch table entry present$"
)


class ProbeError(ValueError):
    """Raised when an input or recovered invariant changes."""


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ProbeError(message)


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def pin(path: Path) -> dict[str, object]:
    data = path.read_bytes()
    return {"path": str(path), "size": len(data), "sha256": digest(data)}


def render_switches(switches: list[dict[str, object]]) -> str:
    parts = [
        "# Generated by XenonAnalyse; 22 impossible 32767-label false positives removed\n"
    ]
    for row in switches:
        parts.extend([
            "[[switch]]\n",
            f"base = 0x{int(row['base']):08X}\n",
            f"r = {int(row['r'])}\n",
            f"default = 0x{int(row['default']):08X}\n",
            "labels = [\n",
        ])
        parts.extend(f"    0x{int(label):08X},\n" for label in row["labels"])
        parts.extend(["]\n\n"])
    return "".join(parts)


def tree_summary(path: Path) -> dict[str, object]:
    files = sorted(item for item in path.iterdir() if item.is_file())
    require(files, "XenonRecomp output directory is empty")
    state = hashlib.sha256()
    total = 0
    for item in files:
        data = item.read_bytes()
        total += len(data)
        state.update(item.name.encode("utf-8") + b"\0")
        state.update(len(data).to_bytes(8, "big"))
        state.update(hashlib.sha256(data).digest())
    cpp = [item for item in files if item.suffix == ".cpp"]
    largest = max(cpp, key=lambda item: item.stat().st_size)
    return {
        "file_count": len(files),
        "cpp_file_count": len(cpp),
        "total_file_bytes": total,
        "tree_sha256": state.hexdigest(),
        "largest_cpp_name": largest.name,
        "largest_cpp_size": largest.stat().st_size,
        "largest_cpp_sha256": digest(largest.read_bytes()),
    }


def syntax_check(args: argparse.Namespace, source: Path) -> dict[str, object]:
    command = [
        args.clang, "-std=c++20", "-O0", "-fsyntax-only",
        f"-I{args.output_dir}", f"-I{args.xenon_utils}",
        f"-I{args.simde}", str(source),
    ]
    completed = subprocess.run(command, capture_output=True, text=True, check=False)
    return {
        "source": source.name,
        "source_sha256": digest(source.read_bytes()),
        "return_code": completed.returncode,
        "stderr": completed.stderr,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--xex", type=Path, required=True)
    parser.add_argument("--xex-report", type=Path, required=True)
    parser.add_argument("--ghidra-report", type=Path, required=True)
    parser.add_argument("--raw-switches", type=Path, required=True)
    parser.add_argument("--filtered-switches", type=Path, required=True)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--log", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--vendor-root", type=Path, required=True)
    parser.add_argument("--xenon-utils", type=Path, required=True)
    parser.add_argument("--simde", type=Path, required=True)
    parser.add_argument("--clang", default="clang++-18")
    parser.add_argument("--json", type=Path, required=True)
    args = parser.parse_args()

    xex = args.xex.read_bytes()
    require(digest(xex) == EXPECTED_XEX_SHA256, "APF retail XEX changed")
    xex_report = json.loads(args.xex_report.read_text(encoding="utf-8"))
    import_count = int(xex_report["imports"]["logical_count"])
    require(import_count == 347, "APF import count changed")
    ghidra_report = json.loads(args.ghidra_report.read_text(encoding="utf-8"))
    ghidra_function_count = int(ghidra_report["text_function_count"])
    require(ghidra_function_count == 21347, "APF Ghidra function count changed")

    commit = subprocess.run(
        ["git", "-C", str(args.vendor_root), "rev-parse", "HEAD"],
        capture_output=True, text=True, check=True,
    ).stdout.strip()
    require(commit == EXPECTED_VENDOR_COMMIT, "vendored XenonRecomp commit changed")

    raw_document = tomllib.loads(args.raw_switches.read_text(encoding="utf-8"))
    raw_switches = raw_document["switch"]
    pathological = [row for row in raw_switches if len(row["labels"]) == 32767]
    filtered = [row for row in raw_switches if len(row["labels"]) != 32767]
    require(len(raw_switches) == 992 and len(pathological) == 22, (
        "XenonAnalyse raw switch-table result changed"
    ))
    require(render_switches(filtered) == args.filtered_switches.read_text(encoding="utf-8"),
            "filtered switch-table file is not the deterministic projection")

    lines = args.log.read_text(encoding="utf-8").splitlines()
    unsupported: list[dict[str, str]] = []
    switch_errors: Counter[str] = Counter()
    missing: list[str] = []
    for line in lines:
        match = UNRECOGNIZED.match(line)
        if match:
            unsupported.append({"address": match.group(1).upper().replace("0X", "0x"),
                                "mnemonic": match.group(2)})
            continue
        match = SWITCH_ERROR.match(line)
        if match:
            switch_errors[f"0x{match.group(1).upper()}"] += 1
            continue
        match = MISSING_SWITCH.match(line)
        if match:
            missing.append(f"0x{match.group(1).upper()}")
    require(lines[-1] == "Recompiling functions... 100%", "recompiler did not finish")
    require(len(unsupported) == 172 and len(switch_errors) == 196 and
            sum(switch_errors.values()) == 3337 and missing == ["0x84BC849C"],
            "filtered XenonRecomp diagnostic result changed")

    unsupported_counts = Counter(row["mnemonic"] for row in unsupported)
    output = tree_summary(args.output_dir)
    require((output["file_count"], output["cpp_file_count"]) == (240, 237),
            "generated C++ file count changed")
    mapping_text = (args.output_dir / "ppc_func_mapping.cpp").read_text(encoding="utf-8")
    shared_text = (args.output_dir / "ppc_recomp_shared.h").read_text(encoding="utf-8")
    mapping_count = len(re.findall(r"^\s*\{ 0x", mapping_text, re.MULTILINE))
    implementation_count = sum(
        len(re.findall(r"^PPC_FUNC_IMPL\(", item.read_text(encoding="utf-8"), re.MULTILINE))
        for item in args.output_dir.glob("*.cpp")
    )
    require((mapping_count, implementation_count) == (60731, 60397),
            "generated function mapping/implementation count changed")
    require("PPC_EXTERN_FUNC(sub_84630000)" in shared_text,
            "generated shared declaration file differs")

    syntax_sources = [
        args.output_dir / "ppc_recomp.0.cpp",
        args.output_dir / str(output["largest_cpp_name"]),
    ]
    syntax = [syntax_check(args, source) for source in syntax_sources]
    require(all(row["return_code"] == 0 and row["stderr"] == "" for row in syntax),
            "generated C++ syntax check failed")

    report = {
        "schema": SCHEMA,
        "result": {
            "xenon_analyse_completed": True,
            "xenon_recomp_completed": True,
            "generated_cpp_syntax_sample_passed": True,
            "generated_code_semantically_complete": False,
            "title_runtime_exists": False,
            "native_gameplay_boot_proved": False,
            "turnkey_static_recomp_port": False,
        },
        "save_restore_helpers": {
            "restgprlr_14": "0x84BD6E00", "savegprlr_14": "0x84BD6DB0",
            "restfpr_14": "0x84BD73AC", "savefpr_14": "0x84BD7360",
            "restvmx_14": "0x84BD7698", "savevmx_14": "0x84BD7400",
            "restvmx_64": "0x84BD772C", "savevmx_64": "0x84BD7494",
        },
        "switch_analysis": {
            "raw_switch_count": len(raw_switches),
            "raw_label_count": sum(len(row["labels"]) for row in raw_switches),
            "pathological_32767_label_table_count": len(pathological),
            "filtered_switch_count": len(filtered),
            "filtered_label_count": sum(len(row["labels"]) for row in filtered),
            "filtered_max_label_count": max(len(row["labels"]) for row in filtered),
            "remaining_out_of_function_error_count": sum(switch_errors.values()),
            "remaining_out_of_function_switch_count": len(switch_errors),
            "missing_switch_sites": missing,
            "out_of_function_errors_by_switch": dict(switch_errors.most_common()),
        },
        "instruction_gaps": {
            "site_count": len(unsupported),
            "unique_mnemonic_count": len(unsupported_counts),
            "mnemonic_counts": dict(unsupported_counts.most_common()),
            "sites": unsupported,
            "effect": "XenonRecomp emits comments without state updates at these sites",
        },
        "generated_output": {
            **output,
            "function_mapping_count": mapping_count,
            "function_implementation_count": implementation_count,
            "ghidra_recovered_text_function_count": ghidra_function_count,
            "generated_to_ghidra_function_ratio": round(
                implementation_count / ghidra_function_count, 6
            ),
            "boundary_interpretation": (
                "The 60,397 generated implementations are 2.83x Ghidra's 21,347 "
                "recovered text functions, reinforcing that automatic boundaries "
                "need reconciliation before translated code can be trusted."
            ),
            "syntax_checks": syntax,
        },
        "runtime_gap": {
            "xex_import_count": import_count,
            "xenonrecomp_readme_boundary": (
                "XenonRecomp converts PPC to C++ but explicitly provides no runtime"
            ),
            "required": [
                "correct function and switch boundaries",
                "implement 11 missing PPC/VMX mnemonics at 172 sites",
                "implement/hook 347 XEX imports and statically linked XDK behavior",
                "provide guest memory, threads, exceptions, filesystem, input, XMA and timing",
                "replace or emulate Xenos command streams, shaders and MMIO",
                "validate title state, rendering and audio against Xenia/hardware",
            ],
        },
        "interpretation": {
            "worked": (
                "The retail APF XEX can be translated mechanically into a large, "
                "syntactically valid C++ corpus after removing 22 obvious analyzer "
                "false-positive switch tables."
            ),
            "failed": (
                "The output still has 3,337 switch/function-boundary violations, one "
                "missing switch definition and 172 omitted instruction semantics; it "
                "has no title runtime and cannot boot the game."
            ),
            "conclusion": (
                "Static recompilation is a viable accelerator for CPU translation, "
                "not a shortcut that makes APF natively playable in days."
            ),
        },
        "sources": {
            "xex": pin(args.xex), "xex_report": pin(args.xex_report),
            "ghidra_report": pin(args.ghidra_report),
            "raw_switches": pin(args.raw_switches),
            "filtered_switches": pin(args.filtered_switches),
            "config": pin(args.config), "recompiler_log": pin(args.log),
            "generator": pin(Path(__file__)),
            "xenonrecomp_readme": pin(args.vendor_root / "README.md"),
            "xenonrecomp_recompiler": pin(
                args.vendor_root / "build/XenonRecomp/XenonRecomp"
            ),
            "xenonrecomp_commit": commit,
        },
        "portme": [
            "// PORTME: replace XenonAnalyse's 196 remaining cross-function switch results with Ghidra-validated function/switch boundaries and add missing table 0x84BC849C.",
            "// PORTME: implement and differentially test all 11 missing PPC/VMX mnemonics at the 172 omitted sites before executing translated code.",
            "// PORTME: build the APF-specific Linux runtime; generated C++ alone has no XEX imports, Xenos, MMIO, threads, filesystem, input, XMA or title bootstrap implementation.",
        ],
    }
    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(
        "APF_STATIC_RECOMP_PROBE_COMPLETE "
        f"switches={len(filtered)} switch_errors={sum(switch_errors.values())} "
        f"unsupported={len(unsupported)} cpp={output['cpp_file_count']} runtime=no"
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (ProbeError, OSError, KeyError, ValueError, subprocess.SubprocessError) as exc:
        raise SystemExit(f"error: {exc}") from exc
