#!/usr/bin/env python3
"""Rebuild the Player Card honors runtime (job F5) with GNU gcc/binutils; development use only.

EXPERIMENTAL / UNWITNESSED. The generated ``mod_editor/core/nfl2k5_honors_code.py`` is checked in, so Studio users
never need a compiler. The ELF32 tables are read with the standard library. ``--check`` fails if the checked-in
template differs from a fresh build (same gcc/binutils as the generator: gcc 13.3, binutils 2.42).
"""
from __future__ import annotations

from pathlib import Path
import argparse
import struct
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path(__file__).resolve().parent / "nfl2k5_honors"
TARGET = ROOT / "mod_editor/core/nfl2k5_honors_code.py"
FLAGS = ["-m32", "-Os", "-ffreestanding", "-fno-builtin", "-fno-strict-aliasing", "-fno-pic", "-fno-pie",
         "-fno-stack-protector", "-fno-asynchronous-unwind-tables", "-fno-unwind-tables", "-fomit-frame-pointer",
         "-fno-jump-tables", "-mpreferred-stack-boundary=2", "-mno-sse", "-mno-mmx", "-Wall", "-Wextra", "-Werror"]
EXTERNAL = {"honors_state": "state"}
ENTRIES = ("honors_page_input", "honors_page_enter", "honors_page_ratings", "honors_page_bio",
           "honors_season_hook", "honors_sb_hook", "honors_fold_rule")


def generate(source: Path = SOURCE) -> str:
    source = Path(source).resolve()
    with tempfile.TemporaryDirectory(prefix="nfl2k5-honors-") as folder:
        d = Path(folder).resolve()
        subprocess.run(["gcc", *FLAGS, "-c", str(source / "runtime.c"), "-o", str(d / "c.o")], check=True)
        subprocess.run(["as", "--32", "-o", str(d / "s.o"), str(source / "stubs.S")], check=True)
        (d / "link.ld").write_text("SECTIONS { .text 0 : { *(.text*) *(.rodata*) } "
                                  "/DISCARD/ : { *(.comment) *(.note*) *(.eh_frame*) } }")
        subprocess.run(["ld", "-r", "-m", "elf_i386", "-T", str(d / "link.ld"), "-o", str(d / "honors.o"),
                        str(d / "s.o"), str(d / "c.o")], check=True)
        data = (d / "honors.o").read_bytes()
    if data[:6] != b"\x7fELF\x01\x01":
        raise ValueError("expected little-endian ELF32")
    shoff = struct.unpack_from("<I", data, 32)[0]
    entsize, count, strings = struct.unpack_from("<3H", data, 46)
    sections = [struct.unpack_from("<10I", data, shoff + i * entsize) for i in range(count)]

    def content(s):
        return data[s[4]:s[4] + s[5]]

    def name(table, off):
        return table[off:table.index(0, off)].decode("ascii")

    names = content(sections[strings])
    by_name = {name(names, s[0]): (i, s) for i, s in enumerate(sections)}
    for n in (".data", ".bss"):
        if n in by_name and by_name[n][1][5]:
            raise ValueError("mutable runtime data must use the owner's RW block (honors_state)")
    text_index, text_section = by_name[".text"]
    symtab = by_name[".symtab"][1]
    symnames = content(sections[symtab[6]])
    symbols, labels = [], {}
    for off in range(0, symtab[5], 16):
        n, value, _, _, _, section = struct.unpack_from("<IIIBBH", content(symtab), off)
        n = name(symnames, n)
        symbols.append((n, value, section))
        if section == text_index and n and not n.startswith(".L"):
            if n in labels and labels[n] != value:
                raise ValueError(f"ambiguous symbol: {n}")
            labels[n] = value
    relocations = []
    for off, info in struct.iter_unpack("<II", content(by_name[".rel.text"][1])):
        n, value, section = symbols[info >> 8]
        kind = info & 255
        if kind not in (1, 2):
            raise ValueError("unsupported i386 relocation")
        if section == text_index:
            n = "code"
        elif section == 0 and n in EXTERNAL:
            n = EXTERNAL[n]
        else:
            raise ValueError(f"unexpected relocation target {n!r} in section {section}")
        relocations.append((off, kind, n, value))
    missing = [e for e in ENTRIES if e not in labels]
    if missing:
        raise ValueError(f"entry points missing: {missing}")
    code = content(text_section)
    lines = ['"""Generated by tools/nfl2k5_honors_build.py (gcc 13.3, binutils 2.42). EXPERIMENTAL / UNWITNESSED."""',
             "", "CODE = bytes.fromhex("]
    lines += ['    "' + code[i:i + 40].hex() + '"' for i in range(0, len(code), 40)]
    lines += [")", "RELOCATIONS = ("] + [f"    {r!r}," for r in sorted(relocations)]
    lines += [")", "LABELS = {"] + [f"    {n!r}: {v}," for n, v in sorted(labels.items())]
    return "\n".join(lines + ["}", ""])


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = generate()
    if args.check:
        if TARGET.read_text(encoding="utf-8") != result:
            raise SystemExit("honors runtime template is stale")
        print("honors runtime template verified")
    else:
        TARGET.write_text(result, encoding="utf-8", newline="\n")
        print("honors runtime template generated")


if __name__ == "__main__":
    main()
