#!/usr/bin/env python3
"""The 2026 team marks on NFL 2K5's menu logo surfaces (job u3). EXPERIMENTAL / UNWITNESSED.

Surfaces (style 0, the style every current team draws; texture names from the game's own loaders):
  logos.cdf     logo_<code>_0          256 P8   full logo with a soft drop shadow (menus, wrap-up, player card)
  mini.cdf      logo_s<code>_0          64 P8   the same logo, compact (FRMINI menus)
  flipchip.cdf  <code>_flipchip_00_h0   64 P8   a close crop of the logo (menu chips)
  team package  <code>_teamlogo_00_h0  256 P8   the full logo again (franchise office, ESPN.com)
  team package  pdalogo                 64 P8   the draft PDA's green LCD art: nickname over the logo
  mini.cdf      mini_h<code>_0          64 P8   the home helmet, facing left (schedule rows)
  mini.cdf      mini_a<code>_0          64 P8   the away helmet, facing right

Every image is drawn once at 4x (the master, for the 2K5 Edition texture pack) from the official club mark (NFL.com
club logo files rendered to 2048 px) and box-reduced to the retail size (the native, which the Studio's P8 writer
quantizes into the retail slot). The mini helmets are rendered, not drawn: the game's own helmet model (the Models
tab's hi_head glTF export) wearing each team's finished 2026 helmet texture (the kit writer's art), in Blender, at 4x
with the tool's fixed camera and lights, then box-reduced the same way. The helmet cards stay with the kit writer.

Commands:
  author  --marks DIR --retail DIR --teams JSON --out DIR   masters, natives, manifest.json, review sheets
  minis   --model GLTF --helmets JSON --out DIR [--blender B] mini helmet masters, natives, minis_manifest.json
  project --art DIR --out project.json                      a nfl2k5_visual_mod_project/v1 of p8_texture edits
  pack    --art DIR --catalog TSV --out DIR                  an x2 texture-pack source manifest of the 4x masters
                                                             (names and archive files from a catalog; the keys come
                                                             from x2 build against the catalog of the played disc)

The art is derived from trademarks and stays outside the repository (the research drive); only this tool and the
recipe are committed. Nothing is generated by an image model.
"""
from __future__ import annotations

import argparse
import colorsys
import json
from pathlib import Path
import subprocess
import sys
import tempfile

import numpy as np
from PIL import Image, ImageDraw, ImageFilter, ImageFont

ROOT = Path(__file__).resolve().parents[1]
INVENTORY = ROOT / "reports/assets/nfl2k5_p8_texture_inventory.json"
MASTER = 4
FONT = Path("/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-Bold.ttf")
# Retail framing (measured on the 32 retail logo_<code>_0): centred at (128, 130.5), largest side 176 to 256
# (median 226). The drop shadow: grey (40, 40, 40) under the mark, down-right.
LOGO_BOX = 232
LOGO_CENTRE = (128.0, 130.0)
SHADOW_OFFSET = 3.0
SHADOW_BLUR = 1.5
SHADOW_RGBA = (40, 40, 40, 150)
# The flip chip shows about 0.6 of the mark's larger side around its focal point (retail chips are hand-cropped;
# the focal points below put the head or the emblem in the chip, the rest are centred).
CHIP_SPAN = 0.6
CHIP_FOCUS = {  # 2026 abbreviation: (x, y) as fractions of the mark's box
    "SEA": (0.68, 0.45), "NE": (0.70, 0.45), "BAL": (0.62, 0.45), "DEN": (0.70, 0.40), "CAR": (0.70, 0.45),
    "PHI": (0.35, 0.40), "BUF": (0.55, 0.45), "TB": (0.52, 0.35), "ARI": (0.45, 0.40), "LAC": (0.55, 0.50),
    "DET": (0.45, 0.40), "MIA": (0.45, 0.50), "CHI": (0.50, 0.45), "LV": (0.50, 0.62), "PIT": (0.63, 0.50),
}
CHIP_SPAN_OVERRIDE = {"NYG": 1.0, "IND": 0.9, "NFL": 1.0, "AFC": 1.0, "NFC": 1.0}   # whole marks, as retail
# The draft PDA LCD (retail pdalogo): background and ink.
LCD_BG = (127, 155, 123)
LCD_INK = (42, 48, 49)


def load_rgba(path: Path) -> np.ndarray:
    return np.asarray(Image.open(path).convert("RGBA")).astype(np.float32) / 255.0


def tight(mark: Image.Image) -> Image.Image:
    box = mark.getbbox()
    if box is None:
        raise ValueError("empty mark")
    return mark.crop(box)


def premultiplied_resize(image: Image.Image, size: tuple[int, int]) -> Image.Image:
    """Resize without dark fringes: work in premultiplied alpha."""
    a = np.asarray(image.convert("RGBA")).astype(np.float32) / 255.0
    rgb = a[..., :3] * a[..., 3:4]
    stack = np.concatenate([rgb, a[..., 3:4]], axis=2)
    channels = [Image.fromarray((stack[..., k] * 255).clip(0, 255).astype(np.uint8)).resize(size, Image.LANCZOS)
                for k in range(4)]
    out = np.stack([np.asarray(c).astype(np.float32) / 255.0 for c in channels], axis=2)
    alpha = out[..., 3:4]
    colour = np.where(alpha > 1e-4, out[..., :3] / np.maximum(alpha, 1e-4), 0)
    return Image.fromarray((np.concatenate([colour, alpha], axis=2) * 255 + 0.5).clip(0, 255).astype(np.uint8), "RGBA")


def box_reduce(master: Image.Image, factor: int = MASTER) -> Image.Image:
    """The native: an exact box filter of the master (premultiplied), so the 4x pack and the disc agree."""
    a = np.asarray(master.convert("RGBA")).astype(np.float32) / 255.0
    h, w = a.shape[0] // factor, a.shape[1] // factor
    rgb = (a[..., :3] * a[..., 3:4]).reshape(h, factor, w, factor, 3).mean(axis=(1, 3))
    alpha = a[..., 3].reshape(h, factor, w, factor).mean(axis=(1, 3))[..., None]
    colour = np.where(alpha > 1e-4, rgb / np.maximum(alpha, 1e-4), 0)
    return Image.fromarray((np.concatenate([colour, alpha], axis=2) * 255 + 0.5).clip(0, 255).astype(np.uint8), "RGBA")


def full_logo(mark: Image.Image, size: int = 256 * MASTER) -> Image.Image:
    """The retail-style full logo: the mark fitted to the retail box, centred, over a soft down-right shadow."""
    scale = size / 256.0
    m = tight(mark)
    fit = LOGO_BOX * scale / max(m.size)
    w, h = max(1, round(m.size[0] * fit)), max(1, round(m.size[1] * fit))
    m = premultiplied_resize(m, (w, h))
    canvas = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    x = round(LOGO_CENTRE[0] * scale - w / 2 - SHADOW_OFFSET * scale / 2)
    y = round(LOGO_CENTRE[1] * scale - h / 2 - SHADOW_OFFSET * scale / 2)
    shadow = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    alpha = Image.new("L", (size, size), 0)
    alpha.paste(m.getchannel("A"), (x + round(SHADOW_OFFSET * scale), y + round(SHADOW_OFFSET * scale)))
    alpha = alpha.filter(ImageFilter.GaussianBlur(SHADOW_BLUR * scale))
    alpha = alpha.point(lambda v: v * SHADOW_RGBA[3] // 255)
    shadow.paste(Image.new("RGBA", (size, size), SHADOW_RGBA[:3] + (255,)), (0, 0), alpha)
    canvas.alpha_composite(shadow)
    canvas.alpha_composite(m, (x, y))
    return canvas


def flip_chip(mark: Image.Image, abbr: str, size: int = 64 * MASTER) -> Image.Image:
    m = tight(mark)
    fx, fy = CHIP_FOCUS.get(abbr, (0.5, 0.5))
    span = CHIP_SPAN_OVERRIDE.get(abbr, CHIP_SPAN) * max(m.size)
    cx, cy = fx * m.size[0], fy * m.size[1]
    left, top = cx - span / 2, cy - span / 2
    # keep the window on the mark
    left = min(max(left, min(0.0, m.size[0] - span)), max(0.0, m.size[0] - span))
    top = min(max(top, min(0.0, m.size[1] - span)), max(0.0, m.size[1] - span))
    window = m.crop((round(left), round(top), round(left + span), round(top + span)))
    return premultiplied_resize(window, (size, size))


def pda_logo(mark: Image.Image, nickname: str, size: int = 64 * MASTER) -> Image.Image:
    """The draft PDA art: the nickname over the mark, in LCD ink on the LCD green (opaque, like retail)."""
    scale = size / 64.0
    canvas = Image.new("RGB", (size, size), LCD_BG)
    # the mark: luminance -> ink weight (dark areas dark, white stays LCD)
    m = tight(mark)
    fit = min(54 * scale / m.size[0], 40 * scale / m.size[1])
    m = premultiplied_resize(m, (max(1, round(m.size[0] * fit)), max(1, round(m.size[1] * fit))))
    a = np.asarray(m).astype(np.float32) / 255.0
    lum = 0.2126 * a[..., 0] + 0.7152 * a[..., 1] + 0.0722 * a[..., 2]
    weight = (1.0 - lum) * a[..., 3]
    weight = np.maximum(weight, a[..., 3] * 0.18)          # light parts still read as a faint LCD shape
    bg = np.asarray(canvas).astype(np.float32) / 255.0
    ox, oy = (size - m.size[0]) // 2, round(21 * scale)
    region = bg[oy:oy + m.size[1], ox:ox + m.size[0]]
    ink = np.array(LCD_INK, dtype=np.float32) / 255.0
    region[:] = region * (1 - weight[..., None]) + ink * weight[..., None]
    canvas = Image.fromarray((bg * 255 + 0.5).clip(0, 255).astype(np.uint8), "RGB")
    # the nickname
    draw = ImageDraw.Draw(canvas)
    text = nickname.upper()
    points = round(13 * scale)
    while points > 4:
        font = ImageFont.truetype(str(FONT), points)
        box = draw.textbbox((0, 0), text, font=font)
        if box[2] - box[0] <= 58 * scale and box[3] - box[1] <= 11 * scale:
            break
        points -= 1
    width = box[2] - box[0]
    draw.text(((size - width) / 2 - box[0], 4 * scale - box[1]), text, fill=LCD_INK, font=font)
    return canvas.convert("RGBA")


# Mini helmets: camera fitted to the retail minis (home faces left, away mirrored), lights calibrated so the retail
# helmet textures render at the retail minis' mean colour (KC, PIT and DAL within a few levels); glossy shell with a
# sky-over-field reflection; the chin strap and jaw pads (the accessories mesh) stay hidden as on the retail minis.
MINI_VIEW = {"yaw": 90, "pitch": 2, "roll": 22, "dist": 0.6, "fov": 30, "target": [0, -0.11, 0.43], "shift_x": -0.05}
MINI_LIGHT = {"ambient": 1.0, "world_bottom": [0.02, 0.03, 0.02], "world_top": [1.2, 1.25, 1.3], "horizon": [0.3, 0.9],
              "sun": 1.5, "sun_cam": [25, -50], "roughness": 0.3, "specular": 0.5, "coat": 1.0, "coat_roughness": 0.03}
MINI_SHELL, MINI_FACEMASK, MINI_SATURATION = "A", "FACEMASK07", 1.2
BLENDER_SCRIPT = Path(__file__).resolve().with_name("nfl2k5_mini_helmet_blender.py")


def mini_view(side: str, out: Path) -> dict:
    view = dict(MINI_VIEW, out=str(out))
    if side == "a":
        view.update(yaw=-MINI_VIEW["yaw"], roll=-MINI_VIEW["roll"], shift_x=-MINI_VIEW["shift_x"])
    return view


def saturate(image: Image.Image, factor: float = MINI_SATURATION) -> Image.Image:
    """Scale HLS saturation of the colour channels; alpha untouched."""
    a = np.asarray(image.convert("RGBA")).astype(np.float32) / 255.0
    rgb = a[..., :3].reshape(-1, 3)
    out = np.empty_like(rgb)
    for i, (r, g, b) in enumerate(rgb):
        h, l, sat = colorsys.rgb_to_hls(r, g, b)
        out[i] = colorsys.hls_to_rgb(h, l, min(1.0, sat * factor))
    a[..., :3] = out.reshape(a.shape[:2] + (3,))
    return Image.fromarray((a * 255 + 0.5).clip(0, 255).astype(np.uint8), "RGBA")


def _inventory_targets() -> dict[str, dict]:
    data = json.loads(INVENTORY.read_text())
    return {t["asset_id"]: t for t in data["targets"]}


def _package_outer(targets: dict[str, dict], code: str) -> int:
    hits = [t for t in targets.values() if t["texture"] == f"{code}_teamlogo_00_h0"]
    if len(hits) != 1:
        raise ValueError(f"no single franchise package for asset code {code}")
    return hits[0]["outer_index"]


def cmd_author(args) -> int:
    marks, retail, out = Path(args.marks), Path(args.retail), Path(args.out).resolve()
    if out == ROOT or ROOT in out.parents:
        raise SystemExit("author writes trademark-derived art: choose a folder outside the repository")
    teams = json.loads(Path(args.teams).read_text())
    targets = _inventory_targets()
    items = []
    for team in teams:
        code, abbr, nickname = team["asset_code"], team["mark"], team["nickname"]
        mark = Image.open(marks / f"{abbr}.png").convert("RGBA")
        outer = _package_outer(targets, code)
        surfaces = [
            ("logo", f"p8:3102:logo_{code}_0", full_logo(mark)),
            ("logo_s", f"p8:3103:logo_s{code}_0", full_logo(mark)),
            ("flipchip", f"p8:3096:{code}_flipchip_00_h0", flip_chip(mark, abbr)),
            ("teamlogo", f"p8:{outer}:{code}_teamlogo_00_h0", full_logo(mark)),
            ("pdalogo", f"p8:{outer}:pdalogo", pda_logo(mark, nickname)),
        ]
        for surface, asset_id, master in surfaces:
            target = targets[asset_id]
            size = (target["width"], target["height"])
            factor = master.size[0] // size[0]
            if factor != MASTER:
                master = premultiplied_resize(master, (size[0] * MASTER, size[1] * MASTER))
            native = box_reduce(master)
            name = asset_id.replace(":", "_")
            (out / "masters").mkdir(parents=True, exist_ok=True)
            (out / "native").mkdir(parents=True, exist_ok=True)
            master.save(out / "masters" / f"{name}.png")
            native.save(out / "native" / f"{name}.png")
            items.append({"code": code, "abbreviation": abbr, "surface": surface, "asset_id": asset_id,
                          "texture": target["texture"], "outer_index": target["outer_index"],
                          "size": list(size), "master": f"masters/{name}.png", "native": f"native/{name}.png"})
    manifest = {"schema": "nfl2k5_team_logos_2026/v1", "experimental": True, "witnessed": False,
                "source": "NFL.com club logo files (static.www.nfl.com/league/api/clubs/logos/<ABBR>.svg) and the "
                          "NFL.com shield, rendered to 2048 px; no generated images",
                "master_scale": MASTER, "items": items}
    (out / "manifest.json").write_text(json.dumps(manifest, indent=1) + "\n", encoding="utf-8", newline="\n")
    print(f"author: {len(items)} textures for {len(teams)} marks -> {out}")
    return 0


def cmd_minis(args) -> int:
    out = Path(args.out).resolve()
    if out == ROOT or ROOT in out.parents:
        raise SystemExit("minis writes trademark-derived art: choose a folder outside the repository")
    helmets = json.loads(Path(args.helmets).read_text())
    targets = _inventory_targets()
    renders = out / "render"
    for sub in ("masters", "native", "render"):
        (out / sub).mkdir(parents=True, exist_ok=True)
    items, jobs = [], []
    for team in helmets:
        code = team["asset_code"]
        fm = team["facemask"].lstrip("#")
        rgb = [int(fm[i:i + 2], 16) for i in (0, 2, 4)]
        for side, key in (("h", "home"), ("a", "away")):
            asset_id = f"p8:3103:mini_{side}{code}_0"
            target = targets[asset_id]
            size = (target["width"], target["height"])
            jobs.append(dict(MINI_LIGHT, texture00=str(Path(team[key]).resolve()), facemask_rgb=rgb, shell=MINI_SHELL,
                             facemask=MINI_FACEMASK, accessories=False,
                             views=[mini_view(side, renders / f"mini_{side}{code}.png")]))
            items.append({"code": code, "abbreviation": team["abbreviation"], "surface": f"mini_{side}",
                          "asset_id": asset_id, "texture": target["texture"], "outer_index": target["outer_index"],
                          "size": list(size), "helmet_texture": team[key], "facemask": "#" + fm.upper(),
                          "facemask_source": team.get("facemask_source", ""),
                          "master": f"masters/{asset_id.replace(':', '_')}.png",
                          "native": f"native/{asset_id.replace(':', '_')}.png"})
    size = {tuple(i["size"]) for i in items}
    if len(size) != 1:
        raise SystemExit(f"mini helmet targets differ in size: {sorted(size)}")
    width = next(iter(size))[0]
    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as handle:
        json.dump({"gltf": str(Path(args.model).resolve()), "size": width * MASTER, "items": jobs}, handle)
        job = handle.name
    try:
        subprocess.run([args.blender, "-b", "-P", str(BLENDER_SCRIPT), "--", job], check=True,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    finally:
        Path(job).unlink(missing_ok=True)
    for item in items:
        side, code = item["surface"][-1], item["code"]
        master = saturate(Image.open(renders / f"mini_{side}{code}.png"))
        master.save(out / item["master"])
        box_reduce(master).save(out / item["native"])
    manifest = {"schema": "nfl2k5_team_minis_2026/v1", "experimental": True, "witnessed": False,
                "source": "the game's hi_head helmet model wearing each team's 2026 helmet texture (kit writer's art), "
                          "rendered in Blender; no generated images",
                "master_scale": MASTER, "view": MINI_VIEW, "light": MINI_LIGHT, "saturation": MINI_SATURATION,
                "items": items}
    (out / "minis_manifest.json").write_text(json.dumps(manifest, indent=1) + "\n", encoding="utf-8", newline="\n")
    print(f"minis: {len(items)} textures for {len(helmets)} teams -> {out}")
    return 0


def cmd_project(args) -> int:
    edits = []
    for art in map(lambda a: Path(a).resolve(), args.art):
        for name in ("manifest.json", "minis_manifest.json"):
            if (art / name).exists():
                manifest = json.loads((art / name).read_text())
                edits += [{"kind": "p8_texture", "asset_id": item["asset_id"], "png": str(art / item["native"])}
                          for item in manifest["items"]]
    ids = [e["asset_id"] for e in edits]
    if len(ids) != len(set(ids)):
        raise SystemExit("project: an asset appears twice across the art folders")
    project = {"schema": "nfl2k5_visual_mod_project/v1", "edits": edits,
               "purpose": "2026 team marks on the menu logo surfaces and the mini helmets (job u3)"}
    Path(args.out).write_text(json.dumps(project, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n")
    print(f"project: {len(edits)} edits -> {args.out}")
    return 0


def cmd_pack(args) -> int:
    import csv
    import os
    files: dict[tuple[str, int], set[str]] = {}
    with open(args.catalog, encoding="utf-8", newline="") as handle:
        rows = csv.DictReader((line for line in handle if not line.startswith("#")), delimiter="\t")
        for row in rows:
            if row["kind"] == "TXTR":
                files.setdefault((row["name"], int(row["outer"])), set()).add(row["file"])
    out = Path(args.out).resolve()
    out.mkdir(parents=True, exist_ok=True)
    entries, problems = [], []
    for art in map(lambda a: Path(a).resolve(), args.art):
        for name in ("manifest.json", "minis_manifest.json"):
            if not (art / name).exists():
                continue
            for item in json.loads((art / name).read_text())["items"]:
                found = files.get((item["texture"], int(item["outer_index"])), set())
                if len(found) != 1:
                    problems.append(f"{item['texture']} in outer {item['outer_index']}: {len(found)} archive files")
                    continue
                entries.append({"image": os.path.relpath(art / item["master"], out),
                                "target": {"name": item["texture"], "file": next(iter(found))},
                                "group": "menus", "label": f"{item['abbreviation']} {item['surface']}"})
    doc = {"name": args.name, "priority": args.priority,
           "description": "4x masters of the 2026 menu logos and mini helmets (job u3); keys resolve against the "
                          "played disc", "entries": entries}
    (out / "manifest.json").write_text(json.dumps(doc, indent=1) + "\n", encoding="utf-8", newline="\n")
    print(f"pack manifest: {len(entries)} entries, {len(problems)} problems -> {out}")
    for problem in problems:
        print("  PROBLEM " + problem)
    return 1 if problems else 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    a = sub.add_parser("author")
    a.add_argument("--marks", required=True)
    a.add_argument("--retail", required=True)
    a.add_argument("--teams", required=True, help="JSON list: asset_code, mark (file stem), nickname")
    a.add_argument("--out", required=True)
    m = sub.add_parser("minis")
    m.add_argument("--model", required=True, help="the Models tab's hi_head glTF export")
    m.add_argument("--helmets", required=True,
                   help="JSON list: asset_code, abbreviation, home and away helmet_helmet00 PNGs, facemask #RRGGBB")
    m.add_argument("--out", required=True)
    m.add_argument("--blender", default="blender")
    p = sub.add_parser("project")
    p.add_argument("--art", required=True, action="append", help="an author or minis output folder (repeatable)")
    p.add_argument("--out", required=True)
    k = sub.add_parser("pack")
    k.add_argument("--art", required=True, action="append", help="an author or minis output folder (repeatable)")
    k.add_argument("--catalog", required=True, help="an x2 texture catalog TSV (names and archive files)")
    k.add_argument("--out", required=True)
    k.add_argument("--name", default="2026 menu logos and mini helmets (u3)")
    k.add_argument("--priority", type=int, default=0)
    args = parser.parse_args(argv)
    return {"author": cmd_author, "minis": cmd_minis, "project": cmd_project, "pack": cmd_pack}[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
