"""Reproduce the Playbook pair kernel byte template with GNU as; development use only.

EXPERIMENTAL / UNWITNESSED. Reads ELF32 section/symbol/relocation tables using
the standard library, so no compiler or ELF package is a runtime dependency.
"""
from __future__ import annotations

from pathlib import Path
import argparse
import struct
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "mod_editor/core/nfl2k5_playbook_pair_code.py"


def generate() -> str:
    with tempfile.TemporaryDirectory(prefix="playbook-pair-") as directory:
        obj = Path(directory).resolve() / "screen.o"
        folder = Path(directory).resolve()
        cobj, sobj = folder / "kernel.o", folder / "adapter.o"
        subprocess.run(["gcc", "-m32", "-Os", "-ffreestanding", "-fno-builtin", "-fno-pic", "-fno-pie",
                        "-fno-stack-protector", "-fno-asynchronous-unwind-tables", "-fno-unwind-tables",
                        "-fno-jump-tables", "-mpreferred-stack-boundary=2", "-mno-sse", "-mno-mmx",
                        "-Wall", "-Wextra", "-Werror", "-c", str(ROOT / "tools/nfl2k5_playbook_pair.c"),
                        "-o", str(cobj)], check=True)
        subprocess.run(["as", "--32", "-o", str(sobj), str(ROOT / "tools/nfl2k5_playbook_pair.S")], check=True)
        script = folder / "link.ld"
        script.write_text("SECTIONS { .text : { *(.text*) *(.rodata*) } /DISCARD/ : { *(.comment) *(.note*) *(.eh_frame*) } }", encoding="ascii")
        subprocess.run(["ld", "-m", "elf_i386", "-r", "-T", str(script), "-o", str(obj), str(cobj), str(sobj)], check=True)
        data = obj.read_bytes()
    if data[:6] != b"\x7fELF\x01\x01":
        raise ValueError("expected little-endian ELF32")
    shoff = struct.unpack_from("<I", data, 32)[0]
    entsize, count, strings = struct.unpack_from("<3H", data, 46)
    sections = [struct.unpack_from("<10I", data, shoff + i * entsize) for i in range(count)]

    def content(section):
        return data[section[4]:section[4] + section[5]]

    def name(table, offset):
        return table[offset:table.index(0, offset)].decode("ascii")

    names = content(sections[strings])
    by_name = {name(names, section[0]): (i, section) for i, section in enumerate(sections)}
    for n in (".bss", ".data"):
        if n in by_name and by_name[n][1][5]:
            raise ValueError("mutable compiler output must use the owned workspace")
    text_index, text_section = by_name[".text"]
    symbols_section = by_name[".symtab"][1]
    symbol_names = content(sections[symbols_section[6]])
    symbols = []
    labels = {}
    for off in range(0, symbols_section[5], 16):
        n, value, _size, _info, _other, section = struct.unpack_from("<IIIBBH", content(symbols_section), off)
        n = name(symbol_names, n)
        symbols.append((n, value, section))
        if section == text_index and n:
            labels[n] = value
    relocations = []
    for offset, info in struct.iter_unpack("<II", content(by_name[".rel.text"][1])):
        symbol, kind = info >> 8, info & 255
        n, value, section = symbols[symbol]
        if section == text_index:
            n = "code"
        elif section != 0:
            raise ValueError("unexpected relocation section")
        if kind not in (1, 2):
            raise ValueError("unsupported i386 relocation")
        relocations.append((offset, kind, n, value))
    blob = content(text_section)
    lines = ['"""Generated by tools/nfl2k5_playbook_pair_assemble.py. EXPERIMENTAL / UNWITNESSED."""',
             "", "CODE = bytes.fromhex("]
    lines += ['    "' + blob[i:i + 40].hex() + '"' for i in range(0, len(blob), 40)]
    lines += [")", "RELOCATIONS = ("]
    lines += [f"    {r!r}," for r in relocations]
    lines += [")", "LABELS = {"]
    lines += [f"    {n!r}: {v}," for n, v in sorted(labels.items())]
    lines += ["}", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = generate()
    if args.check:
        if TARGET.read_text(encoding="utf-8") != result:
            raise SystemExit("Playbook pair kernel byte template is stale")
    else:
        TARGET.write_text(result, encoding="utf-8")
    print("Playbook pair kernel template verified" if args.check else "Playbook pair kernel template generated")


if __name__ == "__main__":
    main()
