"""Reproduce the CPU money downs byte templates with GNU as; development use only.

EXPERIMENTAL / UNWITNESSED. Reads ELF32 section/symbol/relocation tables using
the standard library, so no compiler or ELF package is a runtime dependency.

Two templates share the owner's 2048-byte allocation: ``nfl2k5_cpu_money_downs.S`` (levels Modern and Aggressive,
byte-identical to the beta-76.5 / v0.5 code) and ``nfl2k5_cpu_money_downs_m2.S`` (level Modern 2, b77 p9). The Modern 2
tables are written to ``nfl2k5_cpu_money_downs_m2_tables.inc`` from the sourced data file
``docs/mod_editor/nfl2k5_cpu_decisions_modern2_sources.json``.
"""
from __future__ import annotations

from pathlib import Path
import argparse
import json
import struct
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "mod_editor/core/nfl2k5_cpu_money_downs_code.py"
SOURCES = ROOT / "docs/mod_editor/nfl2k5_cpu_decisions_modern2_sources.json"
TABLES_INC = ROOT / "tools/nfl2k5_cpu_money_downs_m2_tables.inc"


def tables_inc() -> str:
    tables = json.loads(SOURCES.read_text(encoding="utf-8"))["tables"]
    assert len(tables["limit_x"]) == 81 and len(tables["shift"]) == 126 and len(tables["thr10"]) == 33
    lines = ["/* Generated by tools/nfl2k5_cpu_money_downs_assemble.py from docs/mod_editor/nfl2k5_cpu_decisions_modern2_sources.json. */"]
    for name, values, note in (
            ("limit_x", tables["limit_x"], "typical go limit by whole yards to the opponent goal line, 0..80 (ESPN Analytics chart)"),
            ("shift", tables["shift"], "signed shift [t*7+m][r*3]: t clock class 0..5, m margin class 0..6, r region P/M/F (nfl4th); 100 = always go"),
            ("thr", tables["thr10"], "two-point threshold by margin -16..+16 in 10 s of game left; 0 never, 255 always (ESPN Analytics)")):
        lines.append(f"/* {note} */")
        lines.append(f"{name}:")
        for i in range(0, len(values), 21):
            lines.append("    .byte " + ", ".join(str(v) for v in values[i:i + 21]))
    return "\n".join(lines) + "\n"


def _assemble(source: Path) -> tuple[bytes, list, dict]:
    with tempfile.TemporaryDirectory(prefix="cpu_money_downs-") as directory:
        obj = Path(directory).resolve() / "cpu_money_downs.o"
        subprocess.run(["as", "--32", "-I", str(source.parent), "-o", str(obj), str(source)], check=True)
        data = obj.read_bytes()
    if data[:6] != b"\x7fELF\x01\x01":
        raise ValueError("expected little-endian ELF32")
    shoff = struct.unpack_from("<I", data, 32)[0]
    entsize, count, strings = struct.unpack_from("<3H", data, 46)
    sections = [struct.unpack_from("<10I", data, shoff + i * entsize) for i in range(count)]

    def content(section):
        return data[section[4]:section[4] + section[5]]

    def name(table, offset):
        return table[offset:table.index(0, offset)].decode("ascii")

    names = content(sections[strings])
    by_name = {name(names, section[0]): (i, section) for i, section in enumerate(sections)}
    text_index, text_section = by_name[".text"]
    symbols_section = by_name[".symtab"][1]
    symbol_names = content(sections[symbols_section[6]])
    symbols = []
    labels = {}
    for off in range(0, symbols_section[5], 16):
        n, value, _size, _info, _other, section = struct.unpack_from("<IIIBBH", content(symbols_section), off)
        n = name(symbol_names, n)
        symbols.append((n, value, section))
        if section == text_index and n:
            labels[n] = value
    relocations = []
    for offset, info in struct.iter_unpack("<II", content(by_name[".rel.text"][1])):
        symbol, kind = info >> 8, info & 255
        n, value, section = symbols[symbol]
        if section == text_index:
            n = "code"
        elif section != 0:
            raise ValueError("unexpected relocation section")
        if kind not in (1, 2):
            raise ValueError("unsupported i386 relocation")
        relocations.append((offset, kind, n, value))
    return content(text_section), relocations, labels


def _emit(suffix: str, blob: bytes, relocations: list, labels: dict) -> list[str]:
    lines = [f"CODE{suffix} = bytes.fromhex("]
    lines += ['    "' + blob[i:i + 40].hex() + '"' for i in range(0, len(blob), 40)]
    lines += [")", f"RELOCATIONS{suffix} = ("]
    lines += [f"    {r!r}," for r in relocations]
    lines += [")", f"LABELS{suffix} = {{"]
    lines += [f"    {n!r}: {v}," for n, v in sorted(labels.items())]
    lines += ["}"]
    return lines


def generate() -> str:
    blob, relocations, labels = _assemble(ROOT / "tools/nfl2k5_cpu_money_downs.S")
    lines = ['"""Generated by tools/nfl2k5_cpu_money_downs_assemble.py. EXPERIMENTAL / UNWITNESSED."""', ""]
    lines += _emit("", blob, relocations, labels)
    # Modern 2 template: the tables include is regenerated first so the object always matches the data file.
    TABLES_INC.write_text(tables_inc(), encoding="utf-8", newline="\n")
    blob2, relocations2, labels2 = _assemble(ROOT / "tools/nfl2k5_cpu_money_downs_m2.S")
    lines += [""] + _emit("2", blob2, relocations2, labels2)
    lines += [""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        include = TABLES_INC.read_text(encoding="utf-8") if TABLES_INC.exists() else None
        result = generate()
        if TARGET.read_text() != result or include != TABLES_INC.read_text(encoding="utf-8"):
            raise SystemExit("CPU money downs byte template is stale")
    else:
        TARGET.write_text(generate())
    print("CPU money downs template verified" if args.check else "CPU money downs template generated")


if __name__ == "__main__":
    main()
