#!/usr/bin/env bash
set -euo pipefail

root=$(cd "$(dirname "$0")/.." && pwd)
cd "$root"

report=reports/assets/apf_player_shadow_surface_materials.json
vertices=reports/assets/apf_player_shadow_surface_vertices.tsv
samplers=reports/assets/apf_player_shadow_shader_samplers.tsv
links=reports/assets/apf_player_shadow_static_texture_links.tsv
trace=reports/assets/apf_player_shadow_surface_material_ghidra/player_shadow_surface_material_trace.txt
pseudo=reports/assets/apf_player_shadow_surface_material_ghidra/player_shadow_surface_material_pseudo_c.c
gltf=assets/intermediate/apf2k8/skinned/1310_0415_player_shadow_surface.gltf
bin=assets/intermediate/apf2k8/skinned/1310_0415_player_shadow_surface.bin
canonical_gltf=assets/intermediate/apf2k8/skinned/1310_0415_player_shadow_skin.gltf
canonical_bin=assets/intermediate/apf2k8/skinned/1310_0415_player_shadow_skin.bin
doc=docs/research/apf_player_shadow_surface_materials.md

for required in \
  "$report" "$vertices" "$samplers" "$links" "$trace" "$pseudo" \
  "$gltf" "$bin" "$canonical_gltf" "$canonical_bin" "$doc" \
  tools/apf_player_shadow_surface_materials.py \
  tools/apf_player_shadow_surface_assimp_validate.cpp \
  tools/ghidra_scripts/apf/ApfPlayerShadowSurfaceMaterialTrace.java \
  tools/apf_outer.py tools/apf_inner.py \
  extracted/'All-Pro Football 2K8 (USA)'/0A \
  extracted/'All-Pro Football 2K8 (USA)'/default.xex \
  reports/assets/apf_scene_inventory.json; do
  test -f "$required"
done

python3 -m py_compile tools/apf_player_shadow_surface_materials.py
bash -n "$0"
pkg-config --exists assimp

temporary=$(mktemp -d /tmp/apf-player-shadow-surface.XXXXXX)
trap 'rm -rf "$temporary"' EXIT

build_assimp_validator() {
  local cxx=$1
  local label=$2
  "$cxx" -std=c++20 -O2 -Wall -Wextra \
    tools/apf_player_shadow_surface_assimp_validate.cpp \
    $(pkg-config --cflags --libs assimp) \
    -o "$temporary/assimp-$label"
  "$temporary/assimp-$label" "$gltf"
}

build_assimp_validator c++ gcc
compiler_count=1
if command -v clang++-18 >/dev/null 2>&1; then
  build_assimp_validator clang++-18 clang
  compiler_count=2
fi

generate() {
  local seed=$1
  PYTHONHASHSEED=$seed python3 tools/apf_player_shadow_surface_materials.py
}

# Use the published destinations for both seeds so provenance paths in the
# report are identical, then compare every generated byte.
generate 1
cp "$report" "$temporary/report-one.json"
cp "$vertices" "$temporary/vertices-one.tsv"
cp "$samplers" "$temporary/samplers-one.tsv"
cp "$links" "$temporary/links-one.tsv"
cp "$gltf" "$temporary/surface-one.gltf"
cp "$bin" "$temporary/surface-one.bin"
generate 777
cmp "$temporary/report-one.json" "$report"
cmp "$temporary/vertices-one.tsv" "$vertices"
cmp "$temporary/samplers-one.tsv" "$samplers"
cmp "$temporary/links-one.tsv" "$links"
cmp "$temporary/surface-one.gltf" "$gltf"
cmp "$temporary/surface-one.bin" "$bin"

python3 - "$report" "$vertices" "$samplers" "$links" "$trace" "$pseudo" \
  "$gltf" "$bin" "$canonical_bin" <<'PY'
import csv
import hashlib
import json
import math
from pathlib import Path
import struct
import sys

report_path, vertices_path, samplers_path, links_path, trace_path, pseudo_path, \
    gltf_path, bin_path, canonical_bin_path = map(Path, sys.argv[1:])
report = json.loads(report_path.read_text(encoding="utf-8"))
vertices = list(csv.DictReader(vertices_path.open(encoding="utf-8"), delimiter="\t"))
samplers = list(csv.DictReader(samplers_path.open(encoding="utf-8"), delimiter="\t"))
links = list(csv.DictReader(links_path.open(encoding="utf-8"), delimiter="\t"))
trace = trace_path.read_text(encoding="utf-8")
pseudo = pseudo_path.read_text(encoding="utf-8")
document = json.loads(gltf_path.read_text(encoding="utf-8"))
binary = bin_path.read_bytes()
canonical_binary = canonical_bin_path.read_bytes()

def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

def f32(value):
    return struct.unpack("<f", struct.pack("<f", value))[0]

def snorm16(value):
    return f32(max(value / 32767.0, -1.0))

assert report["schema"] == "apf_player_shadow_surface_materials/v1"
selection = report["selection"]
assert selection["outer_table_index"] == 1310
assert selection["outer_name"] == "global.iff"
assert selection["inner_file_index"] == 415
assert selection["inner_name"] == "player_shadow"
assert selection["inner_type"] == "SCNE"
assert selection["parts"] == [{
    "block": "DRAM", "block_index": 0, "length": 23424, "offset": 3633664,
}]
assert selection["has_vram_part"] is False
assert selection["system_sha256"] == \
    "2042ce844a84a3f4b311bd8554b81744555d3efd6f2e4b5cac6c28a2e0735819"

decision = report["decision"]
for key in (
    "exact_iff_ownership_proved",
    "normal_and_packed_uv_authoring_contract_proved_for_all_vertices",
    "shader_sampler_interface_and_dimensions_proved",
    "draw_to_runtime_material_indirection_proved",
    "separate_no_material_surface_gltf_emitted",
):
    assert decision[key] is True
for key in (
    "concrete_txtr_or_render_target_bindings_proved",
    "exact_sampler_filter_and_address_modes_proved",
    "mod_ready_png_and_gltf_material_safe_to_emit",
    "png_emitted",
    "gltf_material_emitted",
):
    assert decision[key] is False
assert len(report["portme"]) == 4
assert report["portme"][0].startswith("// PORTME before 0x84B27AD0")
assert report["portme"][1].startswith("// PORTME at 0x84B15488")
assert report["portme"][2].startswith("// PORTME at 0x84B14DA0 -> 0x84B28EA0")
assert report["portme"][3].startswith("// PORTME at 0x84AA4728")

shader = report["pixel_shader"]
assert shader["sha256"] == \
    "c7e1ed011010fef44591c7c477ac3c18582282cd2fe205dd9489b0b6c77ad383"
assert shader["creator"] == "2.0.5426.0" and shader["target"] == "ps_3_0"
assert len(shader["constants"]) == 17 and len(shader["samplers"]) == 5
assert shader["xenosrecomp"]["generated_vertex_hlsl_sha256"] == \
    "8cd25351644ea47b9b2c274f386a7e8df41daf4bfd58a95851763d050175913e"
assert shader["xenosrecomp"]["generated_pixel_hlsl_sha256"] == \
    "89da3cf04a5061841b97659ece0ea74d51dd6eff90c994bbf5fe064b77c7e4fe"
expected_samplers = [
    ("BaseMap", "0", "sampler2D"),
    ("NormalMap", "1", "sampler2D"),
    ("GlossOcclusionMap", "2", "sampler2D"),
    ("GroundShadowSampler", "3", "sampler2D"),
    ("SpecularLightmapSampler", "4", "samplerCUBE"),
]
assert [(row["name"], row["register"], row["kind"]) for row in samplers] == \
    expected_samplers
assert all(row["concrete_resource"].startswith("PORTME") for row in samplers)

scan = report["static_file_id_scan"]
assert scan["aligned_u32_offsets_scanned"] == 5856
assert scan["global_iff_file_count"] == 442 and scan["txtr_matches"] == 0
assert [(row["system_offset"], row["value"], row["inner_file_index"],
         row["name"], row["type"], row["classification"]) for row in links] == [
    ("0x0164", "0xea7614f3", "415", "player_shadow", "SCNE", "self-reference"),
    ("0x0254", "0xea7614f3", "415", "player_shadow", "SCNE", "self-reference"),
    ("0x0274", "0xea7614f3", "415", "player_shadow", "SCNE", "self-reference"),
]

assert len(vertices) == 351
normal_values = []
uv_values = []
for index, row in enumerate(vertices):
    assert int(row["vertex"]) == index
    normal_raw = tuple(map(int, row["normal_raw_i16"].split(",")))
    tangent_raw = tuple(map(int, row["tangent_raw_i16"].split(",")))
    normal = tuple(snorm16(value) for value in normal_raw)
    tangent = tuple(snorm16(value) for value in tangent_raw)
    uv = (f32(2.0 * normal[3]), f32(2.0 * tangent[3]))
    exported_normal = tuple(float(row[name]) for name in ("normal_x", "normal_y", "normal_z"))
    exported_uv = (float(row["uv_u"]), float(row["uv_v"]))
    assert exported_normal == normal[:3]
    assert exported_uv == uv
    assert abs(math.sqrt(sum(value * value for value in normal[:3])) - 1.0) < 0.001
    assert abs(math.sqrt(sum(value * value for value in tangent[:3])) - 1.0) < 0.001
    normal_values.append(exported_normal)
    uv_values.append(exported_uv)
assert len(set(uv_values)) == 278
assert min(value[0] for value in uv_values) == 0.06280709058046341
assert max(value[0] for value in uv_values) == 1.6275521516799927
assert min(value[1] for value in uv_values) == -0.6275215744972229
assert max(value[1] for value in uv_values) == 1.000030517578125

assert document["asset"]["version"] == "2.0"
assert document["buffers"] == [{"byteLength": 23268, "uri": bin_path.name}]
assert len(document["bufferViews"]) == 7 and len(document["accessors"]) == 7
primitive = document["meshes"][0]["primitives"][0]
assert primitive["attributes"] == {
    "JOINTS_0": 2, "NORMAL": 5, "POSITION": 0, "TEXCOORD_0": 6, "WEIGHTS_0": 3,
}
assert "material" not in primitive
for forbidden in ("materials", "images", "textures", "samplers"):
    assert forbidden not in document
assert len(binary) == 23268
assert binary[:len(canonical_binary)] == canonical_binary
assert len(canonical_binary) == 16248
decoded_normals = [struct.unpack_from("<3f", binary, 16248 + index * 12)
                   for index in range(351)]
decoded_uvs = [struct.unpack_from("<2f", binary, 20460 + index * 8)
               for index in range(351)]
assert decoded_normals == normal_values
assert decoded_uvs == uv_values

artifacts = report["artifacts"]
assert artifacts["surface_vertices_tsv"]["sha256"] == sha(vertices_path)
assert artifacts["shader_samplers_tsv"]["sha256"] == sha(samplers_path)
assert artifacts["static_texture_links_tsv"]["sha256"] == sha(links_path)
assert artifacts["gltf"]["gltf_sha256"] == sha(gltf_path)
assert artifacts["gltf"]["bin_sha256"] == sha(bin_path)
assert artifacts["gltf"]["canonical_prefix_byte_identical"] is True
assert artifacts["gltf"]["has_material"] is False

for needle in (
    "RAW32 0x849CF2D0 0x80AB007C",
    "RAW32 0x84B107B8 0x816B0020",
    "RAW32 0x84B107BC 0x1D6B00F0",
    "RAW32 0x84B14F98 0x3BE4008C",
    "RAW32 0x84B14FA4 0x2F0B0008",
    "RAW32 0x84B15AB8 0x817B00AC",
    "RAW32 0x84B15AF4 0x7C8BF214",
    "RAW32 0x84B15B28 0x2F1C0008",
    "RAW32 0x84B47818 0x4BFCDC71",
):
    assert needle in trace
for needle in (
    "material + 0x50 + 0x14*n",
    "PORTME at 0x84B15488",
    "PORTME at 0x84B14DA0 -> 0x84B28EA0",
    "PORTME at 0x84AA4728",
):
    assert needle in pseudo
PY

test "$(sha256sum "$report" | cut -d' ' -f1)" = \
  def110c3bd0119e6b8fcf23cd91a48e30eb8be2afc69d8a43f5ed12890983472
test "$(sha256sum "$vertices" | cut -d' ' -f1)" = \
  3d7804af488827a226a6690c0785501741bbb9aa8171690b53b87f387ceacc3c
test "$(sha256sum "$samplers" | cut -d' ' -f1)" = \
  dd52c9817da9837de1cbdcce5f56808ccb4a1b5c2707b88973f29a0daa269df3
test "$(sha256sum "$links" | cut -d' ' -f1)" = \
  668425a0d80f92cd73669dd0dfba9c9d8c891420099668f012b52c291c52516d
test "$(sha256sum "$trace" | cut -d' ' -f1)" = \
  6d028f199ab0fd1062605802148b0b2f140b2cf8d0aeab1745d830c23cfa3084
test "$(sha256sum "$pseudo" | cut -d' ' -f1)" = \
  75a6d7cba7bb8ff85919d459fda7a68038195e0e9c6e34bed5faf95a1d741e54
test "$(sha256sum "$gltf" | cut -d' ' -f1)" = \
  ffc5570c6205ea3bbaa7714eba6bee0ba5f4df7196996ae5a9473e0c4525abfc
test "$(sha256sum "$bin" | cut -d' ' -f1)" = \
  d72016179707c752979d8e079295b1e2ed28a33031b6c5d5ac7176f59aaf9029
test "$(sha256sum "$doc" | cut -d' ' -f1)" = \
  589ffa96a5d58f6f26c8a1c921c40910423f5653bb80f6a50d5c906e57d2e7ae
test "$(wc -l < "$vertices")" -eq 352
test "$(wc -l < "$samplers")" -eq 6
test "$(wc -l < "$links")" -eq 4
test "$(wc -l < "$trace")" -eq 2072
test "$(wc -l < "$pseudo")" -eq 75

if [[ "${APF_PLAYER_SHADOW_SURFACE_FULL:-0}" == 1 ]]; then
  mkdir -p "$temporary/ghidra"
  env HOME="$root/tools/ghidra-home" \
    XDG_CONFIG_HOME="$root/tools/ghidra-home/.config" \
    JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 \
    tools/vendor/ghidra_12.1.2_PUBLIC/support/analyzeHeadless \
      "$root/ghidra_projects" apf2k8 \
      -process default.xex -readOnly -noanalysis \
      -scriptPath "$root/tools/ghidra_scripts/apf" \
      -postScript ApfPlayerShadowSurfaceMaterialTrace.java \
        "$temporary/ghidra"
  cmp "$temporary/ghidra/player_shadow_surface_material_trace.txt" "$trace"
  cmp "$temporary/ghidra/player_shadow_surface_material_pseudo_c.c" "$pseudo"
  echo APF_PLAYER_SHADOW_SURFACE_GHIDRA_REGEN_PASS
fi

echo "APF_PLAYER_SHADOW_SURFACE_MATERIALS_VALIDATION_PASS compilers=$compiler_count vertices=351 uv=278 samplers=5 static_txtr_links=0 material=false png=false surface_gltf=true"
