#!/usr/bin/env python3
"""PROVED OFFLINE: compile all 64 receipts and certify exact D screen pins."""
import argparse
from concurrent.futures import ProcessPoolExecutor
import hashlib
import json
import pprint
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT), str(ROOT/'tools')]
from mod_editor.core import nfl2k5_playbook_pack as packs
from mod_editor.core import nfl2k5_play_intents as intents
from mod_editor.core import nfl2k5_qb_spy_runtime as spy
from mod_editor.core import nfl2k5_screen_timing as timing
from pb.defense.verify import IMAGE, OuterImage, BOOK_ENTRIES


def certify_screens(raw, pack):
    book = packs.parse_playbook_resource(raw)
    screens = [p for p in pack.plays if p.concept == 'RB Slip']
    assert screens
    declared = [p for p in book.plays if 'screen' in p.name.casefold()]
    assert {p.index for p in declared} == {p.replace_index for p in screens}
    for p in declared:
        chains = timing._chains(book, p)
        holds = [ch[timing._hold_index(ch)] for ch in chains[1:6]
                 if timing._hold_index(ch) is not None]
        assert len(holds) == 3 and all(abs(n.operands[1]-.8)<.001 for n in holds)
        moves = [n for n in chains[0] if n.op == 4]
        passes = [n for n in chains[0] if n.op == 6]
        assert len(moves)==len(passes)==1
        assert abs(moves[0].operands[2]+7*timing.codec.YD_CM)<.001
        assert abs(passes[0].operands[5]-.6)<.001
    assert not timing._requests(book, 'D')[0]
    return book, len(screens)


def compile_team(row):
    with OuterImage(IMAGE) as archive:
        team = row['team']
        off = packs.load_pack(ROOT/row['pack'])
        a = packs.apply_pack_to_resource(archive.read_entry(BOOK_ENTRIES[team]), off, asset_id='book:'+team, xbe=IMAGE)
        defense = packs.load_pack(ROOT/f'data/playbooks/softdrink_{team.lower()}_defense.2k5book')
        b = packs.apply_pack_to_resource(a.replacement, defense, asset_id='book:'+team, xbe=IMAGE)
    print('PROVED OFFLINE:', team, 'compiled', flush=True)
    return team, off, a, b


def compile_books():
    rows = json.loads((ROOT/'pb/league_manifest.json').read_text())['teams']
    # DESIGN: independent read-only team resources; no shared worker writes.
    with ProcessPoolExecutor(max_workers=4) as pool:
        result = list(pool.map(compile_team, rows))
    return result


def main():
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--write-pins', action='store_true')
    ap.add_argument('--refresh-manifest', action='store_true')
    args=ap.parse_args()
    rows=compile_books(); pins={}; report={}; pairs=[]
    if args.refresh_manifest:
        from pb.defense.build import semantic
        manifest=[]
        keys=('schema','source_sha256','replacement_sha256','old_node_count','new_node_count',
              'old_formation_count','new_formation_count','old_play_count','new_play_count',
              'replaced_formation_indices','replaced_play_indices')
        for team,_,_,b in rows:
            path=f'data/playbooks/softdrink_{team.lower()}_defense.2k5book'
            pack=packs.load_pack(ROOT/path)
            manifest.append(dict(team=team,pack=path,semantic_sha256=semantic(pack),
                plays=len(pack.plays),formations=len(pack.formations),
                compile={k:b.report[k] for k in keys if k in b.report}))
        (ROOT/'pb/defense_manifest.json').write_text(json.dumps(dict(status='PROVED OFFLINE',teams=manifest),indent=2)+'\n')
    for team, off, a, b in rows:
        book,count=certify_screens(a.replacement, off)
        certify_screens(b.replacement, off)
        signature=timing._signature(book)
        assert timing._signature(b.parsed_replacement)==signature
        pins[hashlib.sha256(book.book_name.encode()).hexdigest()]=signature
        for compiled in (a,b):
            intents.intent_requests(compiled.replacement,compiled.report)
            pairs.append((compiled.replacement,compiled.report))
        report[team]=dict(screens=count,screen_signature=signature,
            offense_sha256=a.replacement_sha256,defense_sha256=b.replacement_sha256,
            spy_records=b.report['spy_intent']['records'])
    if args.write_pins:
        path=ROOT/'mod_editor/core/nfl2k5_screen_authored_pins.py'
        path.write_text('"""PROVED OFFLINE: shipped D screen hashes, generated by pb/phase4.py.\n'
                        'All declared screens are checked for the three D timing values before pinning.\n'
                        '"""\n\nCOMPLETE_OFFENSE_D_PINS = '+pprint.pformat(pins, width=160, sort_dicts=True)+'\n')
        timing.COMPLETE_OFFENSE_D_PINS.clear(); timing.COMPLETE_OFFENSE_D_PINS.update(pins)
    assert pins==timing.COMPLETE_OFFENSE_D_PINS
    table,receipt=spy.compile_intent_table(pairs)
    assert spy.validate_intent_table(table)==1
    for _,_,a,b in rows:
        for raw in (a.replacement,b.replacement):
            result,screen=timing.apply(raw,'D')
            assert result==raw and screen['status']=='applied' and screen['already_applied']
    out=dict(status='PROVED OFFLINE',compiler_receipts=len(pairs),teams=report,spy=receipt,
             screens=sum(r['screens'] for r in report.values()),runtime_witness=False)
    (ROOT/'pb/receipts/phase4/contracts.json').write_text(json.dumps(out,indent=2)+'\n')


if __name__=='__main__':main()
