#!/usr/bin/env python3
"""Make cited, human-readable summaries from the offline audit. No network."""
import csv
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PFR = dict(ARZ='crd', ATL='atl', BAL='rav', BUF='buf', CAR='car', CHI='chi', CIN='cin',
           CLE='cle', DAL='dal', DEN='den', DET='det', GB='gnb', HOU='htx', IND='clt',
           JAX='jax', KC='kan', MIA='mia', MIN='min', NE='nwe', NO='nor', NYG='nyg',
           NYJ='nyj', OAK='rai', PHI='phi', PIT='pit', SD='sdg', SEA='sea', SF='sfo',
           STL='ram', TB='tam', TEN='oti', WAS='was')
OFFICIAL = dict(ARZ='azcardinals.com', ATL='atlantafalcons.com', BAL='baltimoreravens.com',
 BUF='buffalobills.com', CAR='panthers.com', CHI='chicagobears.com', CIN='bengals.com',
 CLE='clevelandbrowns.com', DAL='dallascowboys.com', DEN='denverbroncos.com', DET='detroitlions.com',
 GB='packers.com', HOU='houstontexans.com', IND='colts.com', JAX='jaguars.com', KC='chiefs.com',
 MIA='miamidolphins.com', MIN='vikings.com', NE='patriots.com', NO='neworleanssaints.com',
 NYG='giants.com', NYJ='newyorkjets.com', OAK='raiders.com', PHI='philadelphiaeagles.com',
 PIT='steelers.com', SD='chargers.com', SEA='seahawks.com', SF='49ers.com', STL='therams.com',
 TB='buccaneers.com', TEN='tennesseetitans.com', WAS='commanders.com')


def dump(path, data):
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False)+'\n')


def main():
    audit = json.loads((ROOT/'ht/evidence/retail_audit.json').read_text())
    draft = json.loads((ROOT/'data/nfl2k5_historic_rosters/manifest.json').read_text())
    moment = json.loads((ROOT/'data/nfl2k5_espn25_moment_rosters/manifest.json').read_text())
    lines = ['# Historic roster audit, all 75 retail teams', '',
      '**PROVED OFFLINE:** Retail fields were decoded from the pinned resources. All 53 slots, 28 rating bytes, '
      'sizes, equipment and source candidates are in [retail_audit.json](evidence/retail_audit.json). '
      'The summary below is generated by [summarize.py](tools/summarize.py).', '',
      '**INFERRED:** A unique number plus compatible position is a candidate identity, not proof that the developer '
      'intended that person. "Missing" means absent from those unique candidates. Ambiguous and unmatched slots '
      'must not be silently called proper players. Named stars below means names in the supplied article\'s '
      'Pro Bowl/All-Pro infobox fields; this is not an exhaustive fame ranking.', '',
      '**DESIGN:** Drafts retain unresolved rows and are not playable rosters. Fewer than 53 source people or a '
      'scarce position is a data/model gap, not authority to duplicate a person or borrow from another season. '
      'No listed starters means the parser found no supported explicit starter list, not that the team had none.', '']
    counts, fetch = [], []
    for t, d in zip(audit['teams'], draft['teams']):
        assert t['filename']==d['filename']
        c = Counter(s['name_state'] for s in t['slots'])
        summary = dict(team=t['name'], season=t['year'], filename=t['filename'], outer=t['outer'],
          real_names=c['real_name'], placeholders=c['placeholder'], unverified_names=c['unverified_name'],
          unique_candidates=t['summary'].get('unique_number_position',0),
          ambiguous=t['summary'].get('ambiguous',0), unmatched=t['summary'].get('unmatched',0),
          wikipedia_people=t['source_counts']['wikipedia'], nflverse_people=t['source_counts']['nflverse'],
          source_starters=len(t['starters']), missing_starters=len(t['missing_starters']),
          draft_blocked_slots=sum(bool(p['blockers']) for p in d['players']),
          shared_with_moments=t['moment_resource'], wikipedia_url=t['source']['url'],
          nflverse_url=f"https://github.com/nflverse/nflverse-data/releases/download/rosters/roster_{t['year']}.csv")
        counts.append(summary)
        names = lambda rows: ', '.join(r['name'] for r in rows) or 'None identified by this parser.'
        lines += [f"## {t['index']+1}. {t['name']}", '',
          f"**PROVED OFFLINE:** `{t['filename']}`, outer {t['outer']}, 53 slots; "
          f"{c['placeholder']} placeholders, {c['real_name']} source-matching names, {c['unverified_name']} unverified names. "
          f"Source roster rows: Wikipedia {t['source_counts']['wikipedia']}, nflverse {t['source_counts']['nflverse']}. "
          f"[Article]({summary['wikipedia_url']}); [season CSV]({summary['nflverse_url']}). "
          'Source line numbers and hashes are retained in the JSON.', '',
          f"**INFERRED:** {summary['unique_candidates']} unique number/position candidates; "
          f"{summary['ambiguous']} ambiguous and {summary['unmatched']} unmatched slots.", '',
          f"**PROVED OFFLINE, source extraction:** Explicit starters: {names(t['starters'])}", '',
          f"**INFERRED:** Missing from unique retail matches: {names(t['missing_starters'])}", '',
          f"**PROVED OFFLINE, source extraction:** Named Pro Bowl/All-Pro players: {names(t['featured_source_players'])}", '',
          f"**INFERRED:** Missing named Pro Bowl/All-Pro players: {names(t['missing_featured_players'])}", '',
          '**INFERRED:** All source players without a unique retail match: '+', '.join(t['missing_source_players'])+'.', '',
          f"**DESIGN:** {summary['draft_blocked_slots']} draft slots blocked; "
          f"shared moment resource: {'yes' if t['moment_resource'] else 'no'}. "
          '[Per-player draft](../data/nfl2k5_historic_rosters/manifest.json).', '']
        if t['name']=="Cardinals '75":
            lines += ['**PROVED OFFLINE:** The supplied article is baseball. It contributed zero football rows. '
                      'The nflverse football rows remain independent evidence. The displayed article link above '
                      'identifies the rejected input, not a football citation.', '']
        fetch.append(dict(team=t['name'], label='DESIGN',
          url=f"https://www.pro-football-reference.com/teams/{PFR[t['franchise']]}/{t['year']}_roster.htm",
          status='Exact requested URL; not fetched or verified in this offline job',
          need='Number, position, height, weight, games and starts; compare all unresolved names with the audit',
          blocked_slots=summary['draft_blocked_slots']))
    (ROOT/'ht/TEAM_AUDIT.md').write_text('\n'.join(lines).rstrip()+'\n')
    with (ROOT/'ht/evidence/team_summary.csv').open('w',newline='') as f:
        w=csv.DictWriter(f,fieldnames=list(counts[0]),lineterminator='\n');w.writeheader();w.writerows(counts)
    dump(ROOT/'ht/source_requests.json', dict(label='DESIGN',
      corrected_article=dict(url='https://en.wikipedia.org/wiki/1975_St._Louis_Cardinals_(NFL)_season',
        need='Football roster; replace the downloaded baseball article',status='not fetched'),
      season_rosters=fetch,
      all_time=[dict(franchise=k, url=f'https://www.{domain}/',
        sitemap_url=f'https://www.{domain}/sitemap.xml', status='Discovery endpoint only; unverified offline',
        need='Official all-time or anniversary selection with selection date, complete player list and positions; '
             'retain the direct canonical article URL and any archived official PDF. If none exists, record that '
             'instead of treating a fan roster, Hall of Fame list or all-time appearance register as a selection.')
        for k,domain in OFFICIAL.items()],
      limitation='The 32 direct official selection URLs are not known from these inputs. The endpoints above '
                 'are explicit discovery requests, not verified official all-time roster pages.'))
    ids=list(range(171,174))+list(range(224,250))+list(range(252,255))
    assert len(ids)==len(OFFICIAL)==32 and len(set(ids))==32
    dump(ROOT/'ht/all_time_catalog_design.json',dict(label='DESIGN',implemented=False,ready=False,
      catalog='Independent transient local catalog; do not add rows to the MAX_TEAMS=50 moment table',
      rows=[dict(franchise=k,provisional_identity=i,resource='HTA-'+k+'.iff',
        official_selection_url=None,official_discovery_url='https://www.'+domain+'/',
        roster_authored=False,representative_seasons_required=True,
        equipment='Per-player representative season; keep classic retail geometry and modern-era equipment distinct')
        for i,(k,domain) in zip(ids,OFFICIAL.items())],
      provisional_capacity=dict(descriptors_bytes=32*16,rosters=32,players_if_53_each=32*53,
        transient_two_sides_players=106,existing_spare_pool=155,
        directory_entries_with_m1_styles_e2books_ht_aliases_alltime=95+32+35+15+32,
        spare_directory_entries_retail=101,extra_directory_bytes=(95+32+35+15+32-101)*12),
      prerequisite='Finalize IDs against the integrated e2 allocation registry; prove directory relocation, '
                   'the all-time picker and filename adapter, player counts/depth charts, owner readback and '
                   'main live games. Official source discovery and authoring are still missing.'))
    conflicts=[]
    for m in moment['moments']:
        for side,s in m['sides'].items():
            if s.get('shared_season_conflict'):
                conflicts.append(dict(moment=m['moment'], side=side, game_date=m['game_date'],
                  filename=s['filename'], chosen_moment=s['chosen_moment'],
                  source=s.get('boxscore_url'), private_filename=f"HTG-{m['moment']:02d}-{side}.iff",
                  label='DESIGN', action='Private game-side ROST; route by moment index and side; '
                   'keep art code, historic equipment class and E2R stock-book label independent.'))
    dump(ROOT/'ht/moment_routing_design.json',dict(label='DESIGN',implemented=False,
      season_aliases=[dict(descriptor=t['index'], retail=t['filename'],
        season_resource='HTS-'+t['filename'], preserve_moment_resource=True) for t in audit['teams'] if t['moment_resource']],
      conflicts=conflicts,
      rule='H1 local selection uses HTS aliases for the 35 shared files; the other 40 canonical files may be '
           'authored for their descriptor season. Moment loader selects HTG only for the conflicting side. '
           'Do not reassign a moment to a season roster or overwrite the chosen shared roster. '
           'Do not add these rows to the more-moments MAX_TEAMS=50 table.'))
    print(json.dumps(dict(teams=len(counts),conflicts=len(conflicts),
      names=dict(sum((Counter(s['name_state'] for s in t['slots']) for t in audit['teams']),Counter())),
      explicit_starter_teams=sum(bool(t['starters']) for t in audit['teams']),
      draft_blocked_slots=sum(r['draft_blocked_slots'] for r in counts)),indent=2))


if __name__=='__main__':
    main()
